from django.urls import path
from django.views.generic import TemplateView

from .views import (
    IndexView,
    log,
    ALTCreate,
    ALTDetail,
    ALTList,
    ALTUpdate,
    ASTCreate,
    ASTDetail,
    ASTList,
    ASTUpdate,
    UrateCreate,
    UrateDetail,
    UrateList,
    UrateUpdate,
    PlateletCreate,
    PlateletDetail,
    PlateletList,
    PlateletUpdate,
    WBCCreate,
    WBCDetail,
    WBCList,
    WBCUpdate,
    HemoglobinCreate,
    HemoglobinDetail,
    HemoglobinList,
    HemoglobinUpdate,
    CreatinineCreate,
    CreatinineDetail,
    CreatinineList,
    CreatinineUpdate,
)

app_name = "lab"
urlpatterns = [
    path("", view=IndexView.as_view(), name="index"),
    path("log/", TemplateView.as_view(template_name='lab/log.html'), name="log"),
    path("urate/<int:pk>/update/", view=UrateUpdate.as_view(), name="urate-update"),    
    path("urate/", view=UrateList.as_view(), name="urate-list"),
    path("urate/create/", view=UrateCreate.as_view(), name="urate-create"),
    path("urate/<int:pk>/", view=UrateDetail.as_view(), name="urate-detail"),
    path("ALT/<int:pk>/update/", view=ALTUpdate.as_view(), name="ALT-update"),    
    path("ALT/", view=ALTList.as_view(), name="ALT-list"),
    path("ALT/create/", view=ALTCreate.as_view(), name="ALT-create"),
    path("ALT/<int:pk>/", view=ALTDetail.as_view(), name="ALT-detail"),
    path("AST/<int:pk>/update/", view=ASTUpdate.as_view(), name="AST-update"),    
    path("AST/", view=ASTList.as_view(), name="AST-list"),
    path("AST/create/", view=ASTCreate.as_view(), name="AST-create"),
    path("AST/<int:pk>/", view=ASTDetail.as_view(), name="AST-detail"),
    path("platelet/<int:pk>/update/", view=PlateletUpdate.as_view(), name="platelet-update"),    
    path("platelet/", view=PlateletList.as_view(), name="platelet-list"),
    path("platelet/create/", view=PlateletCreate.as_view(), name="platelet-create"),
    path("platelet/<int:pk>/", view=PlateletDetail.as_view(), name="platelet-detail"),
    path("WBC/<int:pk>/update/", view=WBCUpdate.as_view(), name="WBC-update"),
    path("WBC/", view=WBCList.as_view(), name="WBC-list"),
    path("WBC/create/", view=WBCCreate.as_view(), name="WBC-create"),
    path("WBC/<int:pk>/", view=WBCDetail.as_view(), name="WBC-detail"),
    path("hemoglobin/<int:pk>/update/", view=HemoglobinUpdate.as_view(), name="hemoglobin-update"),
    path("hemoglobin/", view=HemoglobinList.as_view(), name="hemoglobin-list"),
    path("hemoglobin/create/", view=HemoglobinCreate.as_view(), name="hemoglobin-create"),
    path("hemoglobin/<int:pk>/", view=HemoglobinDetail.as_view(), name="hemoglobin-detail"),
    path("creatinine/<int:pk>/update/", view=CreatinineUpdate.as_view(), name="creatinine-update"),
    path("creatinine/", view=CreatinineList.as_view(), name="creatinine-list"),
    path("creatinine/create/", view=CreatinineCreate.as_view(), name="creatinine-create"),
    path("creatinine/<int:pk>/", view=CreatinineDetail.as_view(), name="creatinine-detail"),
]
