# Generated by Django 3.1.7 on 2022-01-08 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lab', '__first__'),
        ('history', '0001_initial'),
        ('flare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flare',
            name='CHF',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.chf'),
        ),
        migrations.AddField(
            model_name='flare',
            name='PVD',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.pvd'),
        ),
        migrations.AddField(
            model_name='flare',
            name='angina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.angina'),
        ),
        migrations.AddField(
            model_name='flare',
            name='heartattack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.heartattack'),
        ),
        migrations.AddField(
            model_name='flare',
            name='hypertension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.hypertension'),
        ),
        migrations.AddField(
            model_name='flare',
            name='stroke',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.stroke'),
        ),
        migrations.AddField(
            model_name='flare',
            name='urate',
            field=models.OneToOneField(blank=True, help_text='Did you get your uric acid checked at the time of your flare?', null=True, on_delete=django.db.models.deletion.CASCADE, to='lab.urate'),
        ),
    ]
