# Generated by Django 3.1.7 on 2022-02-14 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('history', '0001_initial'),
        ('flare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flare',
            name='CHF',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.chf'),
        ),
        migrations.AddField(
            model_name='flare',
            name='PVD',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.pvd'),
        ),
        migrations.AddField(
            model_name='flare',
            name='angina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.angina'),
        ),
    ]
