# Generated by Django 3.1.7 on 2021-12-02 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_auto_20211202_1017'),
        ('history', '0006_auto_20211202_1017'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flare', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flare',
            name='celecoxib',
        ),
        migrations.RemoveField(
            model_name='flare',
            name='colchicine',
        ),
        migrations.RemoveField(
            model_name='flare',
            name='ibuprofen',
        ),
        migrations.RemoveField(
            model_name='flare',
            name='labs',
        ),
        migrations.RemoveField(
            model_name='flare',
            name='meloxicam',
        ),
        migrations.RemoveField(
            model_name='flare',
            name='methylprednisolone',
        ),
        migrations.RemoveField(
            model_name='flare',
            name='naproxen',
        ),
        migrations.RemoveField(
            model_name='flare',
            name='othertreat',
        ),
        migrations.RemoveField(
            model_name='flare',
            name='prednisone',
        ),
        migrations.RemoveField(
            model_name='flare',
            name='tinctureoftime',
        ),
        migrations.AddField(
            model_name='flare',
            name='CHF',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.chf'),
        ),
        migrations.AddField(
            model_name='flare',
            name='PVD',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.pvd'),
        ),
        migrations.AddField(
            model_name='flare',
            name='cardiacdisease',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Angina', 'Angina'), ('Hypertension', 'Hypertension'), ('Stroke / TIA', 'Stroke / TIA'), ('Heart failure', 'Heart Failure'), ('Peripheral vascular disease', 'Peripheral Vascular Disease'), ('Heart attack', 'Heart Attack')], help_text='Do you have a history of hypertension or cardiac disease(s)?', max_length=87, null=True),
        ),
        migrations.AddField(
            model_name='flare',
            name='firstmtp',
            field=models.BooleanField(blank=True, choices=[('', '-----'), (True, 'Yes'), (False, 'No')], default=False, help_text='Is the ', null=True, verbose_name='Is your big toe the painful joint?'),
        ),
        migrations.AddField(
            model_name='flare',
            name='heartattack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.heartattack'),
        ),
        migrations.AddField(
            model_name='flare',
            name='hypertension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.hypertension'),
        ),
        migrations.AddField(
            model_name='flare',
            name='male',
            field=models.BooleanField(blank=True, choices=[('', '-----'), (True, 'Yes'), (False, 'No')], default=False, help_text='Are you male (biologically from birth or medically after birth)?', null=True, verbose_name='Male?'),
        ),
        migrations.AddField(
            model_name='flare',
            name='monoarticular',
            field=models.BooleanField(blank=True, choices=[('', '-----'), (True, 'Yes'), (False, 'No')], default=False, help_text='Does your gout flare involve only 1 joint?', null=True, verbose_name='Monoarticular'),
        ),
        migrations.AddField(
            model_name='flare',
            name='onset',
            field=models.BooleanField(blank=True, choices=[('', '-----'), (True, 'Yes'), (False, 'No')], default=False, help_text='Did your symptoms start and reach maximum intensity within 1 day?', null=True, verbose_name='Rapid Onset (1 day)'),
        ),
        migrations.AddField(
            model_name='flare',
            name='prior_gout',
            field=models.BooleanField(blank=True, choices=[('', '-----'), (True, 'Yes'), (False, 'No')], default=False, help_text="Have you had a prior <a href='/flare/about/' target='_blank'>gout flare</a>or other sudden onset arthritis attack consistent with gout?", null=True, verbose_name='Prior Gout Flare'),
        ),
        migrations.AddField(
            model_name='flare',
            name='redness',
            field=models.BooleanField(blank=True, choices=[('', '-----'), (True, 'Yes'), (False, 'No')], default=False, help_text='Is(are) the joint(s) red (erythematous)?', null=True, verbose_name='Redness'),
        ),
        migrations.AddField(
            model_name='flare',
            name='stroke',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.stroke'),
        ),
        migrations.AlterField(
            model_name='flare',
            name='location',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Right great toe', 'Right great toe'), ('Right second toe', 'Right second toe'), ('Right third toe', 'Right third toe'), ('Right fourth toe', 'Right fourth toe'), ('Right little toe', 'Right little toe'), ('Left great toe', 'Left great toe'), ('Left secont toe', 'Left second toe'), ('Left third toe', 'Left third toe'), ('Left fourth toe', 'Left fourth toe'), ('Left little toe', 'Left little toe'), ('Right first MTP', 'Right first MTP'), ('Right second MTP', 'Right second MTP'), ('Right third MTP', 'Right third MTP'), ('Right fourth MTP', 'Right fourth MTP'), ('Right fifth MTP', 'Right fifth MTP'), ('Left first MTP', 'Left first MTP'), ('Left second MTP', 'Left second MTP'), ('Left third MTP', 'Left third MTP'), ('Left fourth MTP', 'Left fourth MTP'), ('Left fifth MTP', 'Left fifth MTP'), ('Right ankle', 'Right ankle'), ('Left ankle', 'Left ankle'), ('Right talonavicular', 'Right talonavicular'), ('Left talonavicular', 'Left talonavicular'), ('Right midfoot', 'Right midfoot'), ('Left midfoot', 'Left midfoot'), ('Right knee', 'Right knee'), ('Left knee', 'Left knee'), ('Right hip', 'Right hip'), ('Left hip', 'Left hip'), ('Right thumb', 'Right thumb'), ('Right index finger', 'Right index finger'), ('Right middle finger', 'Right middle finger'), ('Right ring finger', 'Right ring finger'), ('Right little finger', 'Right little finger'), ('Left thumb', 'Left thumb'), ('Left index finger', 'Left index finger'), ('Left middle finger', 'Left middle finger'), ('Left ring finger', 'Left ring finger'), ('Left little finger', 'Left little finger'), ('Right first MCP', 'Right first MCP'), ('Right second MCP', 'Right second MCP'), ('Right third MCP', 'Right third MCP'), ('Right fourth MCP', 'Right fourth MCP'), ('Right fifth MCP', 'Right fifth MCP'), ('Left first MCP', 'Left first MCP'), ('Left second MCP', 'Left second MCP'), ('Left third MCP', 'Left third MCP'), ('Left fourth MCP', 'Left fourth MCP'), ('Left fifth MCP', 'Left fifth MCP'), ('Left first CMC', 'Left first CMC'), ('Right first CMC', 'Right first CMC'), ('Right wrist', 'Right wrist'), ('Left wrist', 'Left wrist'), ('Right elbow', 'Right elbow'), ('Left elbow', 'Left elbow'), ('Right shoulder', 'Right shoulder'), ('Left shoulder', 'Left shoulder'), ('Right acromioclacivular', 'Right acromioclacivular'), ('Left acromioclavicular', 'Left acromioclavicular'), ('Right sternoclavicular', 'Right sternoclavicular'), ('Left sternoclavicular', 'Left sternoclavicular'), ('Right temporomandibular', 'Right temporomandibular'), ('Left temporomandibular', 'Left temporomandibular')], help_text='What joint did the flare occur in?', max_length=1025, null=True),
        ),
        migrations.AlterField(
            model_name='flare',
            name='urate',
            field=models.OneToOneField(blank=True, help_text='Did you get your uric acid checked at the time of your flare?', null=True, on_delete=django.db.models.deletion.CASCADE, to='lab.urate'),
        ),
        migrations.AlterField(
            model_name='flare',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
