# Generated by Django 3.1.7 on 2021-10-14 16:34

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flare',
            name='labs',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Urate', 'Urate')], help_text='Did you get your uric acid checked during your flare?', max_length=5, null=True),
        ),
    ]
