# Generated by Django 3.1.7 on 2021-10-04 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lab', '0001_initial'),
        ('treatment', '0001_initial'),
        ('flare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flare',
            name='celecoxib',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='treatment.celecoxib'),
        ),
        migrations.AddField(
            model_name='flare',
            name='colchicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='treatment.colchicine'),
        ),
        migrations.AddField(
            model_name='flare',
            name='ibuprofen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='treatment.ibuprofen'),
        ),
        migrations.AddField(
            model_name='flare',
            name='meloxicam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='treatment.meloxicam'),
        ),
        migrations.AddField(
            model_name='flare',
            name='methylprednisolone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='treatment.methylprednisolone'),
        ),
        migrations.AddField(
            model_name='flare',
            name='naproxen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='treatment.naproxen'),
        ),
        migrations.AddField(
            model_name='flare',
            name='othertreat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='treatment.othertreat'),
        ),
        migrations.AddField(
            model_name='flare',
            name='prednisone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='treatment.prednisone'),
        ),
        migrations.AddField(
            model_name='flare',
            name='tinctureoftime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='treatment.tinctureoftime'),
        ),
        migrations.AddField(
            model_name='flare',
            name='urate',
            field=models.OneToOneField(blank=True, help_text='What was the uric acid at the time of the flare?', null=True, on_delete=django.db.models.deletion.CASCADE, to='lab.urate'),
        ),
    ]
