# Generated by Django 3.1.7 on 2021-12-02 10:50

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flare', '0002_auto_20211202_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flare',
            name='cardiacdisease',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Hypertension', 'Hypertension'), ('Heart attack', 'Heart Attack'), ('Angina', 'Angina'), ('Heart failure', 'Heart Failure'), ('Peripheral vascular disease', 'Peripheral Vascular Disease'), ('Stroke / TIA', 'Stroke / TIA')], help_text='Do you have a history of hypertension or cardiac disease(s)?', max_length=87, null=True),
        ),
    ]
