# Generated by Django 3.1.7 on 2021-04-30 17:47

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import goutdotcom.treatment.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('treatment', '0010_auto_20210430_1747'),
        ('lab', '0003_auto_20210427_2027'),
        ('flare', '0002_delete_ult'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='created', unique=True, verbose_name='Flare Detail')),
                ('location', models.CharField(blank=True, choices=[('Right great toe', 'Right great toe'), ('Right second toe', 'Right second toe'), ('Right third toe', 'Right third toe'), ('Right fourth toe', 'Right fourth toe'), ('Right little toe', 'Right little toe'), ('Left great toe', 'Left great toe'), ('Left secont toe', 'Left secont toe'), ('Left third toe', 'Left third toe'), ('Left fourth toe', 'Left fourth toe'), ('Left little toe', 'Left little toe'), ('Right ankle', 'Right ankle'), ('Left ankle', 'Left ankle'), ('Right knee', 'Right knee'), ('Left knee', 'Left knee'), ('Right hip', 'Right hip'), ('Left hip', 'Left hip'), ('Right thumb', 'Right thumb'), ('Right index finger', 'Right index finger'), ('Right middle finger', 'Right middle finger'), ('Right ring finger', 'Right ring finger'), ('Right little finger', 'Right little finger'), ('Left thumb', 'Left thumb'), ('Left index finger', 'Left index finger'), ('Left middle finger', 'Left middle finger'), ('Left ring finger', 'Left ring finger'), ('Left little finger', 'Left little finger'), ('Right wrist', 'Right wrist'), ('Left wrist', 'Left wrist'), ('Right elbow', 'Right elbow'), ('Left elbow', 'Left elbow'), ('Right shoulder', 'Right shoulder'), ('Left shoulder', 'Left shoulder')], help_text='What joint did the flare occur in?', max_length=60)),
                ('treatment', models.CharField(choices=[(goutdotcom.treatment.models.Colchicine, 'Colchicine'), (goutdotcom.treatment.models.Ibuprofen, 'Ibuprofen'), (goutdotcom.treatment.models.Naproxen, 'Naproxen'), (goutdotcom.treatment.models.Celecoxib, 'Celecoxib'), (goutdotcom.treatment.models.Meloxicam, 'Meloxicam'), (goutdotcom.treatment.models.Prednisone, 'Prednisone'), (goutdotcom.treatment.models.Methylprednisolone, 'Methylprednisolone'), ('Tincture of time', 'Tincture of time'), ('Other', 'Other')], help_text='What was the flare treated with?', max_length=60)),
                ('duration', models.IntegerField(help_text='How long did it last? (days)')),
                ('urate_draw', models.BooleanField(default=False, help_text='Did you get your uric acid checked during your flare?')),
                ('celecoxib', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='treatment.celecoxib')),
                ('colchicine', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='treatment.colchicine')),
                ('ibuprofen', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='treatment.ibuprofen')),
                ('meloxicam', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='treatment.meloxicam')),
                ('methylprednisolone', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='treatment.methylprednisolone')),
                ('naproxen', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='treatment.naproxen')),
                ('prednisone', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='treatment.prednisone')),
                ('urate', models.OneToOneField(blank=True, help_text='What was the uric acid at the time of the flare?', null=True, on_delete=django.db.models.deletion.CASCADE, to='lab.urate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
