# Generated by Django 3.1.7 on 2022-02-19 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('history', '0001_initial'),
        ('lab', '0001_initial'),
        ('flare', '0002_auto_20220219_1527'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='flare',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flare_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flare',
            name='heartattack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.heartattack'),
        ),
        migrations.AddField(
            model_name='flare',
            name='hypertension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.hypertension'),
        ),
        migrations.AddField(
            model_name='flare',
            name='stroke',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.stroke'),
        ),
        migrations.AddField(
            model_name='flare',
            name='urate',
            field=models.OneToOneField(blank=True, help_text='Did you get your uric acid checked at the time of your flare?', null=True, on_delete=django.db.models.deletion.CASCADE, to='lab.urate'),
        ),
        migrations.AddField(
            model_name='flare',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
