# Generated by Django 3.1.7 on 2021-08-18 05:40

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flare', '0002_auto_20210817_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='flare',
            name='labs',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Urate', 'Urate'), ('ALT', 'ALT'), ('AST', 'AST'), ('Creatinine', 'Creatinine'), ('Hemoglobin', 'Hemoglobin'), ('White blood cells', 'White blood cells'), ('Platelets', 'Platelets')], help_text='Did you get your labs checked during your flare?', max_length=63, null=True),
        ),
    ]
