# Generated by Django 3.1.7 on 2021-10-14 23:27

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_auto_20211014_2327'),
        ('flare', '0002_auto_20211014_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flare',
            name='labs',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Urate', 'Urate')], help_text='Check if so', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='flare',
            name='urate',
            field=models.OneToOneField(blank=True, help_text='Typically reported in mg/dL', null=True, on_delete=django.db.models.deletion.CASCADE, to='lab.urate'),
        ),
    ]
