# Generated by Django 3.1.7 on 2021-12-02 15:21

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flare', '0003_auto_20211202_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flare',
            name='cardiacdisease',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(True, 'Yes'), (False, 'No')], help_text='Do you have a history of hypertension or cardiac disease(s)?', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='flare',
            name='firstmtp',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Is the ', null=True, verbose_name='Is your big toe the painful joint?'),
        ),
        migrations.AlterField(
            model_name='flare',
            name='location',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Right foot', 'Right foot'), ('Left foot', 'Left foot'), ('Right ankle', 'Right ankle'), ('Left ankle', 'Left ankle'), ('Right knee', 'Right knee'), ('Left knee', 'Left knee'), ('Right hip', 'Right hip'), ('Left hip', 'Left hip'), ('Right hand', 'Right hand'), ('Left hand', 'Left hand'), ('Right wrist', 'Right wrist'), ('Left wrist', 'Left wrist'), ('Right elbow', 'Right elbow'), ('Left elbow', 'Left elbow'), ('Right shoulder', 'Right shoulder'), ('Left shoulder', 'Left shoulder')], help_text='What joint did the flare occur in?', max_length=179, null=True),
        ),
        migrations.AlterField(
            model_name='flare',
            name='male',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Are you male (biologically from birth or medically after birth)?', null=True, verbose_name='Male?'),
        ),
        migrations.AlterField(
            model_name='flare',
            name='monoarticular',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Does your gout flare involve only 1 joint?', null=True, verbose_name='Monoarticular'),
        ),
        migrations.AlterField(
            model_name='flare',
            name='onset',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Did your symptoms start and reach maximum intensity within 1 day?', null=True, verbose_name='Rapid Onset (1 day)'),
        ),
        migrations.AlterField(
            model_name='flare',
            name='prior_gout',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, help_text="Have you had a prior <a href='/flare/about/' target='_blank'>gout flare</a>or other sudden onset arthritis attack consistent with gout?", null=True, verbose_name='Prior Gout Flare'),
        ),
        migrations.AlterField(
            model_name='flare',
            name='redness',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Is(are) the joint(s) red (erythematous)?', null=True, verbose_name='Redness'),
        ),
    ]
