# Generated by Django 3.1.7 on 2021-10-15 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flare', '0003_auto_20211014_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decisionaid',
            name='NSAID_contraindication',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default='', help_text='Contraindications to NSAIDs', null=True, verbose_name="Have you ever had a heart attack, stroke, congestive heart failure (CHF), Crohn's disease, ulcerative colitis, or a gastrointestinal bleed? Are you on blood thinners?"),
        ),
        migrations.AlterField(
            model_name='decisionaid',
            name='ckd',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default='', help_text='Do you have CKD?', null=True, verbose_name='Do you have CKD?'),
        ),
        migrations.AlterField(
            model_name='decisionaid',
            name='colchicine_contraindication',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default='', help_text='Contraindications to colchicine', null=True, verbose_name='Are you on simvastatin, diltiazem, or clarithromycin?'),
        ),
        migrations.AlterField(
            model_name='decisionaid',
            name='diabetes',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default='', help_text='Type I or type II', null=True, verbose_name='Do you have diabetes?'),
        ),
        migrations.AlterField(
            model_name='decisionaid',
            name='monoarticular',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default='', help_text='Meaning just a toe, knee, etc.', null=True, verbose_name='Is your flare in just a single joint?'),
        ),
        migrations.AlterField(
            model_name='decisionaid',
            name='osteoporosis',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default='', help_text='Brittle bones', null=True, verbose_name='Do you have osteoporosis?'),
        ),
        migrations.AlterField(
            model_name='decisionaid',
            name='perfect_health',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default='', help_text='Meaning no chronic medical problems', null=True, verbose_name='Are you in perfect health?'),
        ),
    ]
