# Generated by Django 3.1.7 on 2021-08-18 08:46

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flare', '0003_flare_labs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flare',
            name='treatment',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Colcrys', 'Colchicine'), ('Advil', 'Ibuprofen'), ('Aleve', 'Naproxen'), ('Celebrex', 'Celecoxib'), ('Mobic', 'Meloxicam'), ('Prednisone', 'Prednisone'), ('Methylprednisolone', 'Methylprednisolone'), ('Tincture of time', 'Tincture of time'), ('Other treatment', 'Other treatment')], help_text='What was the flare treated with?', max_length=97, null=True),
        ),
    ]
