# Generated by Django 3.1.7 on 2022-02-09 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flare', '0004_flare_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='flare',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
