# Generated by Django 3.1.7 on 2021-12-03 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flare', '0004_auto_20211202_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flare',
            name='cardiacdisease',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default='', help_text='Do you have a history of hypertension or cardiac disease(s)?', null=True, verbose_name='Cardiac disease or equivalents'),
        ),
    ]
