# Generated by Django 3.1.7 on 2021-10-22 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flare', '0004_auto_20211015_0008'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DecisionAid',
        ),
    ]
