# Generated by Django 3.1.7 on 2021-04-30 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flare', '0004_auto_20210430_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flare',
            name='slug',
        ),
    ]
