# Generated by Django 3.1.7 on 2021-04-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flare', '0005_remove_flare_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flare',
            name='urate_draw',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Did you get your uric acid checked during your flare?'),
        ),
    ]
