# Generated by Django 3.1.7 on 2021-10-04 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_auto_20211004_1817'),
        ('flare', '0005_auto_20211004_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decisionaid',
            name='diabetes',
            field=models.ForeignKey(blank=True, help_text='Type I or type II', null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.diabetes', verbose_name='Do you have diabetes?'),
        ),
    ]
