# Generated by Django 3.1.7 on 2021-12-03 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flare', '0006_auto_20211203_0456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flare',
            name='cardiacdisease',
        ),
    ]
