# Generated by Django 3.1.7 on 2021-05-01 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flare', '0006_auto_20210430_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='flare',
            name='treatment_log',
            field=models.CharField(choices=[('No', 'No'), ('Already logged it', 'Already logged it'), ('Will log it now', 'Will log it now')], default='Already logged it', help_text='Do you want to or have you already logged you treatment?', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flare',
            name='urate_log',
            field=models.CharField(choices=[('No', 'No'), ('Already logged it', 'Already logged it'), ('Will log it now', 'Will log it now')], default='Already logged it', help_text='Do you want to log or have you already logged your uric acid?', max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flare',
            name='location',
            field=models.CharField(blank=True, choices=[('Right great toe', 'Right great toe'), ('Right second toe', 'Right second toe'), ('Right third toe', 'Right third toe'), ('Right fourth toe', 'Right fourth toe'), ('Right little toe', 'Right little toe'), ('Left great toe', 'Left great toe'), ('Left secont toe', 'Left second toe'), ('Left third toe', 'Left third toe'), ('Left fourth toe', 'Left fourth toe'), ('Left little toe', 'Left little toe'), ('Right ankle', 'Right ankle'), ('Left ankle', 'Left ankle'), ('Right knee', 'Right knee'), ('Left knee', 'Left knee'), ('Right hip', 'Right hip'), ('Left hip', 'Left hip'), ('Right thumb', 'Right thumb'), ('Right index finger', 'Right index finger'), ('Right middle finger', 'Right middle finger'), ('Right ring finger', 'Right ring finger'), ('Right little finger', 'Right little finger'), ('Left thumb', 'Left thumb'), ('Left index finger', 'Left index finger'), ('Left middle finger', 'Left middle finger'), ('Left ring finger', 'Left ring finger'), ('Left little finger', 'Left little finger'), ('Right wrist', 'Right wrist'), ('Left wrist', 'Left wrist'), ('Right elbow', 'Right elbow'), ('Left elbow', 'Left elbow'), ('Right shoulder', 'Right shoulder'), ('Left shoulder', 'Left shoulder')], help_text='What joint did the flare occur in?', max_length=60),
        ),
    ]
