# Generated by Django 3.1.7 on 2021-10-04 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_auto_20211004_1817'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flare', '0007_auto_20211004_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decisionaid',
            name='ckd',
            field=models.ForeignKey(blank=True, help_text='Stage?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.ckd', verbose_name='Do you have CKD?'),
        ),
        migrations.AlterField(
            model_name='decisionaid',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
