# Generated by Django 3.1.7 on 2021-05-10 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flare', '0007_auto_20210501_0624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flare',
            name='treatment_log',
        ),
        migrations.RemoveField(
            model_name='flare',
            name='urate_draw',
        ),
        migrations.RemoveField(
            model_name='flare',
            name='urate_log',
        ),
    ]
