# Generated by Django 3.1.7 on 2021-12-10 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0007_angina'),
        ('flare', '0010_auto_20211207_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='flare',
            name='angina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.angina'),
        ),
    ]
