# Generated by Django 3.1.7 on 2021-04-13 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allopurinol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_started', models.DateField(default=datetime.datetime.now)),
                ('date_ended', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('generic_name', models.CharField(choices=[('allopurinol', 'Allopurinol'), ('febuxostat', 'Febuxostat'), ('prednisone', 'Prednisone'), ('colchicine', 'Colchicine'), ('probenacid', 'Probenacid'), ('pegloticase', 'Pegloticase'), ('ibuprofen', 'Ibuprofen'), ('naproxen', 'Naproxen'), ('meloxicam', 'Meloxicam'), ('celecoxib', 'Celecoxib')], default='allopurinol', max_length=60)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
