# Generated by Django 3.1.7 on 2021-10-04 12:49

import datetime
from decimal import Decimal
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allopurinol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('date_started', models.DateField(default=datetime.datetime.now)),
                ('date_ended', models.DateField(blank=True, null=True)),
                ('generic_name', models.CharField(choices=[('allopurinol', 'Allopurinol'), ('febuxostat', 'Febuxostat'), ('prednisone', 'Prednisone'), ('colchicine', 'Colchicine'), ('probenecid', 'Probenecid'), ('pegloticase', 'Pegloticase'), ('ibuprofen', 'Ibuprofen'), ('naproxen', 'Naproxen'), ('meloxicam', 'Meloxicam'), ('celecoxib', 'Celecoxib'), ('methylprednisolone', 'Methylprednisolone'), ('tinctureoftime', 'Tinctureoftime'), ('other', 'Other')], default='allopurinol', max_length=60)),
                ('dose', models.IntegerField(choices=[(50, '50 mg'), (100, '100 mg'), (150, '150 mg'), (200, '200 mg'), (250, '250 mg'), (300, '300 mg'), (350, '350 mg'), (400, '400 mg'), (450, '450 mg'), (500, '500 mg'), (550, '550 mg'), (600, '600 mg'), (650, '650 mg'), (700, '700 mg'), (750, '750 mg'), (800, '800 mg'), (850, '850 mg'), (900, '900 mg')])),
                ('freq', models.CharField(choices=[('qday', 'Once daily'), ('bid', 'Twice daily'), ('tid', 'Three times daily'), ('q2weeks', 'Every 2 weeks'), ('once', 'Once')], default='qday', max_length=50)),
                ('side_effects', models.CharField(blank=True, choices=[('Rash', 'Rash'), ('Hypersensitivity syndrome', 'Hypersensitivity syndrome'), ('Elevated LFTs', 'Elevated LFTs'), ('Cytopenias', 'Cytopenias'), ('GI upset', 'GI upset'), ('None', 'None')], help_text='Have you had any side effects?', max_length=100, null=True)),
                ('de_sensitized', models.BooleanField(blank=True, help_text='Have you been de-sensitized to allopurinol?', null=True)),
                ('drug_class', models.CharField(choices=[('urate-lowering therapy', 'Urate-lowering therapy'), ('systemic steroid', 'Systemic steroid'), ('anti-inflammatory', 'Anti-inflammatory'), ('nonsteroidal anti-inflammatory drug', 'Nonsteroidal anti-inflammatory drug'), ('urate extreagogue', 'Urate excretagogue'), ('local steroid', 'Local steroid'), ('recombinant uricase', 'Recombinant uricase'), ('other', 'Other')], default='urate-lowering therapy', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Celecoxib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('date_ended', models.DateField(blank=True, null=True)),
                ('date_started', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('prn', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=True, help_text='Do you take this medication only as needed (PRN)?', null=True)),
                ('as_prophylaxis', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Is this for flare prophylaxis while initiating ULT?', null=True, verbose_name='Flare prophylaxis?')),
                ('generic_name', models.CharField(choices=[('allopurinol', 'Allopurinol'), ('febuxostat', 'Febuxostat'), ('prednisone', 'Prednisone'), ('colchicine', 'Colchicine'), ('probenecid', 'Probenecid'), ('pegloticase', 'Pegloticase'), ('ibuprofen', 'Ibuprofen'), ('naproxen', 'Naproxen'), ('meloxicam', 'Meloxicam'), ('celecoxib', 'Celecoxib'), ('methylprednisolone', 'Methylprednisolone'), ('tinctureoftime', 'Tinctureoftime'), ('other', 'Other')], default='celecoxib', max_length=60)),
                ('dose', models.IntegerField(blank=True, choices=[(200, '200 mg'), (400, '400 mg')], null=True)),
                ('freq', models.CharField(blank=True, choices=[('qday', 'Once daily'), ('bid', 'Twice daily'), ('tid', 'Three times daily'), ('q2weeks', 'Every 2 weeks'), ('once', 'Once')], default='qday', max_length=50)),
                ('side_effects', models.CharField(blank=True, choices=[('Rash', 'Rash'), ('Kidney failure', 'Kidney failure'), ('Stomach ulcer', 'Stomach ulcer'), ('GI upset', 'GI upset'), ('Medication interaction', 'Medication interaction'), ('None', 'None')], help_text='Have you had any side effects?', max_length=100)),
                ('drug_class', models.CharField(choices=[('urate-lowering therapy', 'Urate-lowering therapy'), ('systemic steroid', 'Systemic steroid'), ('anti-inflammatory', 'Anti-inflammatory'), ('nonsteroidal anti-inflammatory drug', 'Nonsteroidal anti-inflammatory drug'), ('urate extreagogue', 'Urate excretagogue'), ('local steroid', 'Local steroid'), ('recombinant uricase', 'Recombinant uricase'), ('other', 'Other')], default='nonsteroidal anti-inflammatory drug', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Colchicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('date_ended', models.DateField(blank=True, null=True)),
                ('date_started', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('prn', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=True, help_text='Do you take this medication only as needed (PRN)?', null=True)),
                ('as_prophylaxis', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Is this for flare prophylaxis while initiating ULT?', null=True, verbose_name='Flare prophylaxis?')),
                ('generic_name', models.CharField(choices=[('allopurinol', 'Allopurinol'), ('febuxostat', 'Febuxostat'), ('prednisone', 'Prednisone'), ('colchicine', 'Colchicine'), ('probenecid', 'Probenecid'), ('pegloticase', 'Pegloticase'), ('ibuprofen', 'Ibuprofen'), ('naproxen', 'Naproxen'), ('meloxicam', 'Meloxicam'), ('celecoxib', 'Celecoxib'), ('methylprednisolone', 'Methylprednisolone'), ('tinctureoftime', 'Tinctureoftime'), ('other', 'Other')], default='colchicine', max_length=60)),
                ('dose', models.DecimalField(blank=True, choices=[(Decimal('0.6'), '0.6 mg')], decimal_places=1, max_digits=2, null=True)),
                ('freq', models.CharField(blank=True, choices=[('qday', 'Once daily'), ('bid', 'Twice daily'), ('tid', 'Three times daily'), ('q2weeks', 'Every 2 weeks'), ('once', 'Once')], default='qday', max_length=50)),
                ('side_effects', models.CharField(blank=True, choices=[('GI upset', 'GI upset'), ('Medication interaction', 'Medication interaction'), ('None', 'None')], help_text='Have you had any side effects?', max_length=100)),
                ('drug_class', models.CharField(choices=[('urate-lowering therapy', 'Urate-lowering therapy'), ('systemic steroid', 'Systemic steroid'), ('anti-inflammatory', 'Anti-inflammatory'), ('nonsteroidal anti-inflammatory drug', 'Nonsteroidal anti-inflammatory drug'), ('urate extreagogue', 'Urate excretagogue'), ('local steroid', 'Local steroid'), ('recombinant uricase', 'Recombinant uricase'), ('other', 'Other')], default='anti-inflammatory', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Febuxostat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('date_started', models.DateField(default=datetime.datetime.now)),
                ('date_ended', models.DateField(blank=True, null=True)),
                ('generic_name', models.CharField(choices=[('allopurinol', 'Allopurinol'), ('febuxostat', 'Febuxostat'), ('prednisone', 'Prednisone'), ('colchicine', 'Colchicine'), ('probenecid', 'Probenecid'), ('pegloticase', 'Pegloticase'), ('ibuprofen', 'Ibuprofen'), ('naproxen', 'Naproxen'), ('meloxicam', 'Meloxicam'), ('celecoxib', 'Celecoxib'), ('methylprednisolone', 'Methylprednisolone'), ('tinctureoftime', 'Tinctureoftime'), ('other', 'Other')], default='febuxostat', max_length=60)),
                ('dose', models.IntegerField(choices=[(20, '20 mg'), (40, '40 mg'), (60, '60 mg'), (80, '80 mg'), (100, '100 mg'), (120, '120 mg')])),
                ('freq', models.CharField(choices=[('qday', 'Once daily'), ('bid', 'Twice daily'), ('tid', 'Three times daily'), ('q2weeks', 'Every 2 weeks'), ('once', 'Once')], default='qday', max_length=50)),
                ('side_effects', models.CharField(blank=True, choices=[('Rash', 'Rash'), ('Hypersensitivity syndrome', 'Hypersensitivity syndrome'), ('Elevated LFTs', 'Elevated LFTs'), ('Cytopenias', 'Cytopenias'), ('GI upset', 'GI upset'), ('None', 'None')], help_text='Have you had any side effects?', max_length=100, null=True)),
                ('drug_class', models.CharField(choices=[('urate-lowering therapy', 'Urate-lowering therapy'), ('systemic steroid', 'Systemic steroid'), ('anti-inflammatory', 'Anti-inflammatory'), ('nonsteroidal anti-inflammatory drug', 'Nonsteroidal anti-inflammatory drug'), ('urate extreagogue', 'Urate excretagogue'), ('local steroid', 'Local steroid'), ('recombinant uricase', 'Recombinant uricase'), ('other', 'Other')], default='urate-lowering therapy', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ibuprofen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('date_ended', models.DateField(blank=True, null=True)),
                ('date_started', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('prn', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=True, help_text='Do you take this medication only as needed (PRN)?', null=True)),
                ('as_prophylaxis', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Is this for flare prophylaxis while initiating ULT?', null=True, verbose_name='Flare prophylaxis?')),
                ('generic_name', models.CharField(choices=[('allopurinol', 'Allopurinol'), ('febuxostat', 'Febuxostat'), ('prednisone', 'Prednisone'), ('colchicine', 'Colchicine'), ('probenecid', 'Probenecid'), ('pegloticase', 'Pegloticase'), ('ibuprofen', 'Ibuprofen'), ('naproxen', 'Naproxen'), ('meloxicam', 'Meloxicam'), ('celecoxib', 'Celecoxib'), ('methylprednisolone', 'Methylprednisolone'), ('tinctureoftime', 'Tinctureoftime'), ('other', 'Other')], default='ibuprofen', max_length=60)),
                ('dose', models.IntegerField(blank=True, choices=[(200, '200 mg'), (400, '400 mg'), (600, '600 mg'), (800, '800 mg')], null=True)),
                ('freq', models.CharField(blank=True, choices=[('qday', 'Once daily'), ('bid', 'Twice daily'), ('tid', 'Three times daily'), ('q2weeks', 'Every 2 weeks'), ('once', 'Once')], default='qday', max_length=50)),
                ('side_effects', models.CharField(blank=True, choices=[('Rash', 'Rash'), ('Kidney failure', 'Kidney failure'), ('Stomach ulcer', 'Stomach ulcer'), ('GI upset', 'GI upset'), ('Medication interaction', 'Medication interaction'), ('None', 'None')], help_text='Have you had any side effects?', max_length=100, null=True)),
                ('drug_class', models.CharField(choices=[('urate-lowering therapy', 'Urate-lowering therapy'), ('systemic steroid', 'Systemic steroid'), ('anti-inflammatory', 'Anti-inflammatory'), ('nonsteroidal anti-inflammatory drug', 'Nonsteroidal anti-inflammatory drug'), ('urate extreagogue', 'Urate excretagogue'), ('local steroid', 'Local steroid'), ('recombinant uricase', 'Recombinant uricase'), ('other', 'Other')], default='nonsteroidal anti-inflammatory drug', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Meloxicam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('date_ended', models.DateField(blank=True, null=True)),
                ('date_started', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('prn', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=True, help_text='Do you take this medication only as needed (PRN)?', null=True)),
                ('as_prophylaxis', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Is this for flare prophylaxis while initiating ULT?', null=True, verbose_name='Flare prophylaxis?')),
                ('generic_name', models.CharField(choices=[('allopurinol', 'Allopurinol'), ('febuxostat', 'Febuxostat'), ('prednisone', 'Prednisone'), ('colchicine', 'Colchicine'), ('probenecid', 'Probenecid'), ('pegloticase', 'Pegloticase'), ('ibuprofen', 'Ibuprofen'), ('naproxen', 'Naproxen'), ('meloxicam', 'Meloxicam'), ('celecoxib', 'Celecoxib'), ('methylprednisolone', 'Methylprednisolone'), ('tinctureoftime', 'Tinctureoftime'), ('other', 'Other')], default='meloxicam', max_length=60)),
                ('dose', models.DecimalField(blank=True, choices=[(Decimal('7.5'), '7.5 mg'), (Decimal('15'), '15 mg')], decimal_places=1, max_digits=3, null=True)),
                ('freq', models.CharField(blank=True, choices=[('qday', 'Once daily'), ('bid', 'Twice daily'), ('tid', 'Three times daily'), ('q2weeks', 'Every 2 weeks'), ('once', 'Once')], default='qday', max_length=50)),
                ('side_effects', models.CharField(blank=True, choices=[('Rash', 'Rash'), ('Kidney failure', 'Kidney failure'), ('Stomach ulcer', 'Stomach ulcer'), ('GI upset', 'GI upset'), ('Medication interaction', 'Medication interaction'), ('None', 'None')], help_text='Have you had any side effects?', max_length=100)),
                ('drug_class', models.CharField(choices=[('urate-lowering therapy', 'Urate-lowering therapy'), ('systemic steroid', 'Systemic steroid'), ('anti-inflammatory', 'Anti-inflammatory'), ('nonsteroidal anti-inflammatory drug', 'Nonsteroidal anti-inflammatory drug'), ('urate extreagogue', 'Urate excretagogue'), ('local steroid', 'Local steroid'), ('recombinant uricase', 'Recombinant uricase'), ('other', 'Other')], default='nonsteroidal anti-inflammatory drug', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Methylprednisolone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('date_ended', models.DateField(blank=True, null=True)),
                ('date_started', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('prn', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=True, help_text='Do you take this medication only as needed (PRN)?', null=True)),
                ('as_prophylaxis', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Is this for flare prophylaxis while initiating ULT?', null=True, verbose_name='Flare prophylaxis?')),
                ('generic_name', models.CharField(choices=[('allopurinol', 'Allopurinol'), ('febuxostat', 'Febuxostat'), ('prednisone', 'Prednisone'), ('colchicine', 'Colchicine'), ('probenecid', 'Probenecid'), ('pegloticase', 'Pegloticase'), ('ibuprofen', 'Ibuprofen'), ('naproxen', 'Naproxen'), ('meloxicam', 'Meloxicam'), ('celecoxib', 'Celecoxib'), ('methylprednisolone', 'Methylprednisolone'), ('tinctureoftime', 'Tinctureoftime'), ('other', 'Other')], default='methylprednisolone', max_length=60)),
                ('dose', models.IntegerField(blank=True, choices=[(20, '20 mg'), (40, '40 mg'), (80, '80 mg')], null=True)),
                ('freq', models.CharField(blank=True, choices=[('qday', 'Once daily'), ('bid', 'Twice daily'), ('tid', 'Three times daily'), ('q2weeks', 'Every 2 weeks'), ('once', 'Once')], default='qday', max_length=50)),
                ('side_effects', models.CharField(blank=True, choices=[('Bleeding', 'Bleeding'), ('Infection', 'Infection'), ('None', 'None')], help_text='Have you had any side effects?', max_length=100)),
                ('drug_class', models.CharField(choices=[('urate-lowering therapy', 'Urate-lowering therapy'), ('systemic steroid', 'Systemic steroid'), ('anti-inflammatory', 'Anti-inflammatory'), ('nonsteroidal anti-inflammatory drug', 'Nonsteroidal anti-inflammatory drug'), ('urate extreagogue', 'Urate excretagogue'), ('local steroid', 'Local steroid'), ('recombinant uricase', 'Recombinant uricase'), ('other', 'Other')], default='local steroid', max_length=50)),
                ('as_injection', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Was this given by an injection into your joint?', null=True, verbose_name='Given by joint injection?')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Naproxen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('date_ended', models.DateField(blank=True, null=True)),
                ('date_started', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('prn', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=True, help_text='Do you take this medication only as needed (PRN)?', null=True)),
                ('as_prophylaxis', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Is this for flare prophylaxis while initiating ULT?', null=True, verbose_name='Flare prophylaxis?')),
                ('generic_name', models.CharField(choices=[('allopurinol', 'Allopurinol'), ('febuxostat', 'Febuxostat'), ('prednisone', 'Prednisone'), ('colchicine', 'Colchicine'), ('probenecid', 'Probenecid'), ('pegloticase', 'Pegloticase'), ('ibuprofen', 'Ibuprofen'), ('naproxen', 'Naproxen'), ('meloxicam', 'Meloxicam'), ('celecoxib', 'Celecoxib'), ('methylprednisolone', 'Methylprednisolone'), ('tinctureoftime', 'Tinctureoftime'), ('other', 'Other')], default='naproxen', max_length=60)),
                ('dose', models.IntegerField(blank=True, choices=[(220, '220 mg'), (250, '250 mg'), (440, '440 mg'), (500, '500 mg')], null=True)),
                ('freq', models.CharField(blank=True, choices=[('qday', 'Once daily'), ('bid', 'Twice daily'), ('tid', 'Three times daily'), ('q2weeks', 'Every 2 weeks'), ('once', 'Once')], default='qday', max_length=50)),
                ('side_effects', models.CharField(blank=True, choices=[('Rash', 'Rash'), ('Kidney failure', 'Kidney failure'), ('Stomach ulcer', 'Stomach ulcer'), ('GI upset', 'GI upset'), ('Medication interaction', 'Medication interaction'), ('None', 'None')], help_text='Have you had any side effects?', max_length=100)),
                ('drug_class', models.CharField(choices=[('urate-lowering therapy', 'Urate-lowering therapy'), ('systemic steroid', 'Systemic steroid'), ('anti-inflammatory', 'Anti-inflammatory'), ('nonsteroidal anti-inflammatory drug', 'Nonsteroidal anti-inflammatory drug'), ('urate extreagogue', 'Urate excretagogue'), ('local steroid', 'Local steroid'), ('recombinant uricase', 'Recombinant uricase'), ('other', 'Other')], default='nonsteroidal anti-inflammatory drug', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Othertreat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('date_ended', models.DateField(blank=True, null=True)),
                ('date_started', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('prn', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=True, help_text='Do you take this medication only as needed (PRN)?', null=True)),
                ('as_prophylaxis', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Is this for flare prophylaxis while initiating ULT?', null=True, verbose_name='Flare prophylaxis?')),
                ('generic_name', models.CharField(choices=[('allopurinol', 'Allopurinol'), ('febuxostat', 'Febuxostat'), ('prednisone', 'Prednisone'), ('colchicine', 'Colchicine'), ('probenecid', 'Probenecid'), ('pegloticase', 'Pegloticase'), ('ibuprofen', 'Ibuprofen'), ('naproxen', 'Naproxen'), ('meloxicam', 'Meloxicam'), ('celecoxib', 'Celecoxib'), ('methylprednisolone', 'Methylprednisolone'), ('tinctureoftime', 'Tinctureoftime'), ('other', 'Other')], default='other', max_length=60)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('dose', models.IntegerField(blank=True, help_text='Any optional information on your dose?', null=True)),
                ('freq', models.CharField(blank=True, choices=[('qday', 'Once daily'), ('bid', 'Twice daily'), ('tid', 'Three times daily'), ('q2weeks', 'Every 2 weeks'), ('once', 'Once')], default='qday', help_text='Any optional information on your frequency?', max_length=50, null=True)),
                ('side_effects', models.CharField(blank=True, help_text='Have you had any side effects? Please list', max_length=400)),
                ('drug_class', models.CharField(choices=[('urate-lowering therapy', 'Urate-lowering therapy'), ('systemic steroid', 'Systemic steroid'), ('anti-inflammatory', 'Anti-inflammatory'), ('nonsteroidal anti-inflammatory drug', 'Nonsteroidal anti-inflammatory drug'), ('urate extreagogue', 'Urate excretagogue'), ('local steroid', 'Local steroid'), ('recombinant uricase', 'Recombinant uricase'), ('other', 'Other')], default='other', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Prednisone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('date_ended', models.DateField(blank=True, null=True)),
                ('date_started', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('prn', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=True, help_text='Do you take this medication only as needed (PRN)?', null=True)),
                ('as_prophylaxis', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Is this for flare prophylaxis while initiating ULT?', null=True, verbose_name='Flare prophylaxis?')),
                ('generic_name', models.CharField(choices=[('allopurinol', 'Allopurinol'), ('febuxostat', 'Febuxostat'), ('prednisone', 'Prednisone'), ('colchicine', 'Colchicine'), ('probenecid', 'Probenecid'), ('pegloticase', 'Pegloticase'), ('ibuprofen', 'Ibuprofen'), ('naproxen', 'Naproxen'), ('meloxicam', 'Meloxicam'), ('celecoxib', 'Celecoxib'), ('methylprednisolone', 'Methylprednisolone'), ('tinctureoftime', 'Tinctureoftime'), ('other', 'Other')], default='prednisone', max_length=60)),
                ('dose', models.IntegerField(blank=True, null=True)),
                ('freq', models.CharField(blank=True, choices=[('qday', 'Once daily'), ('bid', 'Twice daily'), ('tid', 'Three times daily'), ('q2weeks', 'Every 2 weeks'), ('once', 'Once')], default='qday', max_length=50)),
                ('side_effects', models.CharField(blank=True, choices=[('Insomnia', 'Insomnia'), ('Weight gain', 'Weight gain'), ('Anxiety', 'Anxiety'), ('Hyperglycemia', 'Hyperglycemia'), ('Weakness', 'Weakness'), ('Easy bruising', 'Easy bruising'), ('Osteoporosis', 'Osteoporosis'), ('Cataract', 'Cataract'), ('Infection', 'Infection'), ('None', 'None')], help_text='Have you had any side effects?', max_length=100, null=True)),
                ('drug_class', models.CharField(choices=[('urate-lowering therapy', 'Urate-lowering therapy'), ('systemic steroid', 'Systemic steroid'), ('anti-inflammatory', 'Anti-inflammatory'), ('nonsteroidal anti-inflammatory drug', 'Nonsteroidal anti-inflammatory drug'), ('urate extreagogue', 'Urate excretagogue'), ('local steroid', 'Local steroid'), ('recombinant uricase', 'Recombinant uricase'), ('other', 'Other')], default='systemic steroid', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Probenecid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('date_started', models.DateField(default=datetime.datetime.now)),
                ('date_ended', models.DateField(blank=True, null=True)),
                ('generic_name', models.CharField(choices=[('allopurinol', 'Allopurinol'), ('febuxostat', 'Febuxostat'), ('prednisone', 'Prednisone'), ('colchicine', 'Colchicine'), ('probenecid', 'Probenecid'), ('pegloticase', 'Pegloticase'), ('ibuprofen', 'Ibuprofen'), ('naproxen', 'Naproxen'), ('meloxicam', 'Meloxicam'), ('celecoxib', 'Celecoxib'), ('methylprednisolone', 'Methylprednisolone'), ('tinctureoftime', 'Tinctureoftime'), ('other', 'Other')], default='probenecid', max_length=60)),
                ('dose', models.IntegerField(choices=[(250, '250 mg'), (500, '500 mg'), (750, '750 mg'), (1000, '1000 mg')])),
                ('freq', models.CharField(choices=[('qday', 'Once daily'), ('bid', 'Twice daily'), ('tid', 'Three times daily'), ('q2weeks', 'Every 2 weeks'), ('once', 'Once')], default='bid', max_length=50)),
                ('side_effects', models.CharField(blank=True, choices=[('Flushing', 'Flushing'), ('Headache', 'Headache'), ('None', 'None')], help_text='Have you had any side effects?', max_length=100, null=True)),
                ('drug_class', models.CharField(choices=[('urate-lowering therapy', 'Urate-lowering therapy'), ('systemic steroid', 'Systemic steroid'), ('anti-inflammatory', 'Anti-inflammatory'), ('nonsteroidal anti-inflammatory drug', 'Nonsteroidal anti-inflammatory drug'), ('urate extreagogue', 'Urate excretagogue'), ('local steroid', 'Local steroid'), ('recombinant uricase', 'Recombinant uricase'), ('other', 'Other')], default='urate extreagogue', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tinctureoftime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('date_ended', models.DateField(blank=True, null=True)),
                ('date_started', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('prn', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=True, help_text='Do you take this medication only as needed (PRN)?', null=True)),
                ('as_prophylaxis', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Is this for flare prophylaxis while initiating ULT?', null=True, verbose_name='Flare prophylaxis?')),
                ('generic_name', models.CharField(choices=[('allopurinol', 'Allopurinol'), ('febuxostat', 'Febuxostat'), ('prednisone', 'Prednisone'), ('colchicine', 'Colchicine'), ('probenecid', 'Probenecid'), ('pegloticase', 'Pegloticase'), ('ibuprofen', 'Ibuprofen'), ('naproxen', 'Naproxen'), ('meloxicam', 'Meloxicam'), ('celecoxib', 'Celecoxib'), ('methylprednisolone', 'Methylprednisolone'), ('tinctureoftime', 'Tinctureoftime'), ('other', 'Other')], default='tinctureoftime', max_length=60)),
                ('duration', models.IntegerField(blank=True, help_text='How long did it take to get better?', null=True)),
                ('dose', models.IntegerField(blank=True, help_text='Any optional information on your dose?', null=True)),
                ('freq', models.CharField(blank=True, choices=[('qday', 'Once daily'), ('bid', 'Twice daily'), ('tid', 'Three times daily'), ('q2weeks', 'Every 2 weeks'), ('once', 'Once')], default='qday', help_text='Any optional information on your frequency?', max_length=50, null=True)),
                ('side_effects', models.CharField(blank=True, help_text='Have you had any side effects? Please list', max_length=400, null=True)),
                ('drug_class', models.CharField(choices=[('urate-lowering therapy', 'Urate-lowering therapy'), ('systemic steroid', 'Systemic steroid'), ('anti-inflammatory', 'Anti-inflammatory'), ('nonsteroidal anti-inflammatory drug', 'Nonsteroidal anti-inflammatory drug'), ('urate extreagogue', 'Urate excretagogue'), ('local steroid', 'Local steroid'), ('recombinant uricase', 'Recombinant uricase'), ('other', 'Other')], default='tinctureoftime', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
