# Generated by Django 3.1.7 on 2021-08-10 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('treatment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tinctureoftime',
            name='duration',
        ),
        migrations.AddField(
            model_name='celecoxib',
            name='prn',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Do you take this medication only as needed (PRN)?', null=True),
        ),
        migrations.AddField(
            model_name='colchicine',
            name='prn',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Do you take this medication only as needed (PRN)?', null=True),
        ),
        migrations.AddField(
            model_name='ibuprofen',
            name='prn',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Do you take this medication only as needed (PRN)?', null=True),
        ),
        migrations.AddField(
            model_name='meloxicam',
            name='prn',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Do you take this medication only as needed (PRN)?', null=True),
        ),
        migrations.AddField(
            model_name='methylprednisolone',
            name='as_prophylaxis',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Is this for flare prophylaxis while initiating ULT?', null=True, verbose_name='Flare prophylaxis?'),
        ),
        migrations.AddField(
            model_name='methylprednisolone',
            name='prn',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Do you take this medication only as needed (PRN)?', null=True),
        ),
        migrations.AddField(
            model_name='naproxen',
            name='prn',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Do you take this medication only as needed (PRN)?', null=True),
        ),
        migrations.AddField(
            model_name='othertreat',
            name='as_prophylaxis',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Is this for flare prophylaxis while initiating ULT?', null=True, verbose_name='Flare prophylaxis?'),
        ),
        migrations.AddField(
            model_name='othertreat',
            name='dose',
            field=models.IntegerField(blank=True, help_text='Any optional information on your dose?', null=True),
        ),
        migrations.AddField(
            model_name='othertreat',
            name='drug_class',
            field=models.CharField(choices=[('urate-lowering therapy', 'Urate-lowering therapy'), ('systemic steroid', 'Systemic steroid'), ('anti-inflammatory', 'Anti-inflammatory'), ('nonsteroidal antiinflammatory drug', 'Nonsteroidal anti-inflammatory drug'), ('urate extreagogue', 'Urate excretagogue'), ('local steroid', 'Local steroid'), ('recombinant uricase', 'Recombinant uricase'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='othertreat',
            name='freq',
            field=models.CharField(blank=True, choices=[('qday', 'Once daily'), ('bid', 'Twice daily'), ('tid', 'Three times daily'), ('q2weeks', 'Every 2 weeks'), ('once', 'Once')], default='qday', help_text='Any optional information on your frequency?', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='othertreat',
            name='generic_name',
            field=models.CharField(choices=[('allopurinol', 'Allopurinol'), ('febuxostat', 'Febuxostat'), ('prednisone', 'Prednisone'), ('colchicine', 'Colchicine'), ('probenecid', 'Probenecid'), ('pegloticase', 'Pegloticase'), ('ibuprofen', 'Ibuprofen'), ('naproxen', 'Naproxen'), ('meloxicam', 'Meloxicam'), ('celecoxib', 'Celecoxib'), ('methylprednisolone', 'Methylprednisolone'), ('tinctureoftime', 'Tinctureoftime'), ('other', 'Other')], default='other', max_length=60),
        ),
        migrations.AddField(
            model_name='othertreat',
            name='prn',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Do you take this medication only as needed (PRN)?', null=True),
        ),
        migrations.AddField(
            model_name='othertreat',
            name='side_effects',
            field=models.CharField(blank=True, help_text='Have you had any side effects? Please list', max_length=400),
        ),
        migrations.AddField(
            model_name='prednisone',
            name='prn',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Do you take this medication only as needed (PRN)?', null=True),
        ),
        migrations.AddField(
            model_name='tinctureoftime',
            name='as_prophylaxis',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Is this for flare prophylaxis while initiating ULT?', null=True, verbose_name='Flare prophylaxis?'),
        ),
        migrations.AddField(
            model_name='tinctureoftime',
            name='dose',
            field=models.IntegerField(blank=True, help_text='Any optional information on your dose?', null=True),
        ),
        migrations.AddField(
            model_name='tinctureoftime',
            name='drug_class',
            field=models.CharField(choices=[('urate-lowering therapy', 'Urate-lowering therapy'), ('systemic steroid', 'Systemic steroid'), ('anti-inflammatory', 'Anti-inflammatory'), ('nonsteroidal antiinflammatory drug', 'Nonsteroidal anti-inflammatory drug'), ('urate extreagogue', 'Urate excretagogue'), ('local steroid', 'Local steroid'), ('recombinant uricase', 'Recombinant uricase'), ('other', 'Other')], default='tinctureoftime', max_length=50),
        ),
        migrations.AddField(
            model_name='tinctureoftime',
            name='freq',
            field=models.CharField(blank=True, choices=[('qday', 'Once daily'), ('bid', 'Twice daily'), ('tid', 'Three times daily'), ('q2weeks', 'Every 2 weeks'), ('once', 'Once')], default='qday', help_text='Any optional information on your frequency?', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tinctureoftime',
            name='generic_name',
            field=models.CharField(choices=[('allopurinol', 'Allopurinol'), ('febuxostat', 'Febuxostat'), ('prednisone', 'Prednisone'), ('colchicine', 'Colchicine'), ('probenecid', 'Probenecid'), ('pegloticase', 'Pegloticase'), ('ibuprofen', 'Ibuprofen'), ('naproxen', 'Naproxen'), ('meloxicam', 'Meloxicam'), ('celecoxib', 'Celecoxib'), ('methylprednisolone', 'Methylprednisolone'), ('tinctureoftime', 'Tinctureoftime'), ('other', 'Other')], default='tinctureoftime', max_length=60),
        ),
        migrations.AddField(
            model_name='tinctureoftime',
            name='prn',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Do you take this medication only as needed (PRN)?', null=True),
        ),
        migrations.AddField(
            model_name='tinctureoftime',
            name='side_effects',
            field=models.CharField(blank=True, help_text='Have you had any side effects? Please list', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='allopurinol',
            name='drug_class',
            field=models.CharField(choices=[('urate-lowering therapy', 'Urate-lowering therapy'), ('systemic steroid', 'Systemic steroid'), ('anti-inflammatory', 'Anti-inflammatory'), ('nonsteroidal antiinflammatory drug', 'Nonsteroidal anti-inflammatory drug'), ('urate extreagogue', 'Urate excretagogue'), ('local steroid', 'Local steroid'), ('recombinant uricase', 'Recombinant uricase'), ('other', 'Other')], default='urate-lowering therapy', max_length=50),
        ),
        migrations.AlterField(
            model_name='allopurinol',
            name='freq',
            field=models.CharField(choices=[('qday', 'Once daily'), ('bid', 'Twice daily'), ('tid', 'Three times daily'), ('q2weeks', 'Every 2 weeks'), ('once', 'Once')], default='qday', max_length=50),
        ),
        migrations.AlterField(
            model_name='allopurinol',
            name='generic_name',
            field=models.CharField(choices=[('allopurinol', 'Allopurinol'), ('febuxostat', 'Febuxostat'), ('prednisone', 'Prednisone'), ('colchicine', 'Colchicine'), ('probenecid', 'Probenecid'), ('pegloticase', 'Pegloticase'), ('ibuprofen', 'Ibuprofen'), ('naproxen', 'Naproxen'), ('meloxicam', 'Meloxicam'), ('celecoxib', 'Celecoxib'), ('methylprednisolone', 'Methylprednisolone'), ('tinctureoftime', 'Tinctureoftime'), ('other', 'Other')], default='allopurinol', max_length=60),
        ),
        migrations.AlterField(
            model_name='celecoxib',
            name='as_prophylaxis',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Is this for flare prophylaxis while initiating ULT?', null=True, verbose_name='Flare prophylaxis?'),
        ),
        migrations.AlterField(
            model_name='celecoxib',
            name='drug_class',
            field=models.CharField(choices=[('urate-lowering therapy', 'Urate-lowering therapy'), ('systemic steroid', 'Systemic steroid'), ('anti-inflammatory', 'Anti-inflammatory'), ('nonsteroidal antiinflammatory drug', 'Nonsteroidal anti-inflammatory drug'), ('urate extreagogue', 'Urate excretagogue'), ('local steroid', 'Local steroid'), ('recombinant uricase', 'Recombinant uricase'), ('other', 'Other')], default='nonsteroidal antiinflammatory drug', max_length=50),
        ),
        migrations.AlterField(
            model_name='celecoxib',
            name='freq',
            field=models.CharField(blank=True, choices=[('qday', 'Once daily'), ('bid', 'Twice daily'), ('tid', 'Three times daily'), ('q2weeks', 'Every 2 weeks'), ('once', 'Once')], default='qday', max_length=50),
        ),
        migrations.AlterField(
            model_name='celecoxib',
            name='generic_name',
            field=models.CharField(choices=[('allopurinol', 'Allopurinol'), ('febuxostat', 'Febuxostat'), ('prednisone', 'Prednisone'), ('colchicine', 'Colchicine'), ('probenecid', 'Probenecid'), ('pegloticase', 'Pegloticase'), ('ibuprofen', 'Ibuprofen'), ('naproxen', 'Naproxen'), ('meloxicam', 'Meloxicam'), ('celecoxib', 'Celecoxib'), ('methylprednisolone', 'Methylprednisolone'), ('tinctureoftime', 'Tinctureoftime'), ('other', 'Other')], default='celecoxib', max_length=60),
        ),
        migrations.AlterField(
            model_name='celecoxib',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='colchicine',
            name='drug_class',
            field=models.CharField(choices=[('urate-lowering therapy', 'Urate-lowering therapy'), ('systemic steroid', 'Systemic steroid'), ('anti-inflammatory', 'Anti-inflammatory'), ('nonsteroidal antiinflammatory drug', 'Nonsteroidal anti-inflammatory drug'), ('urate extreagogue', 'Urate excretagogue'), ('local steroid', 'Local steroid'), ('recombinant uricase', 'Recombinant uricase'), ('other', 'Other')], default='anti-inflammatory', max_length=50),
        ),
        migrations.AlterField(
            model_name='colchicine',
            name='freq',
            field=models.CharField(blank=True, choices=[('qday', 'Once daily'), ('bid', 'Twice daily'), ('tid', 'Three times daily'), ('q2weeks', 'Every 2 weeks'), ('once', 'Once')], default='qday', max_length=50),
        ),
        migrations.AlterField(
            model_name='colchicine',
            name='generic_name',
            field=models.CharField(choices=[('allopurinol', 'Allopurinol'), ('febuxostat', 'Febuxostat'), ('prednisone', 'Prednisone'), ('colchicine', 'Colchicine'), ('probenecid', 'Probenecid'), ('pegloticase', 'Pegloticase'), ('ibuprofen', 'Ibuprofen'), ('naproxen', 'Naproxen'), ('meloxicam', 'Meloxicam'), ('celecoxib', 'Celecoxib'), ('methylprednisolone', 'Methylprednisolone'), ('tinctureoftime', 'Tinctureoftime'), ('other', 'Other')], default='colchicine', max_length=60),
        ),
        migrations.AlterField(
            model_name='colchicine',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='febuxostat',
            name='drug_class',
            field=models.CharField(choices=[('urate-lowering therapy', 'Urate-lowering therapy'), ('systemic steroid', 'Systemic steroid'), ('anti-inflammatory', 'Anti-inflammatory'), ('nonsteroidal antiinflammatory drug', 'Nonsteroidal anti-inflammatory drug'), ('urate extreagogue', 'Urate excretagogue'), ('local steroid', 'Local steroid'), ('recombinant uricase', 'Recombinant uricase'), ('other', 'Other')], default='urate-lowering therapy', max_length=50),
        ),
        migrations.AlterField(
            model_name='febuxostat',
            name='freq',
            field=models.CharField(choices=[('qday', 'Once daily'), ('bid', 'Twice daily'), ('tid', 'Three times daily'), ('q2weeks', 'Every 2 weeks'), ('once', 'Once')], default='qday', max_length=50),
        ),
        migrations.AlterField(
            model_name='febuxostat',
            name='generic_name',
            field=models.CharField(choices=[('allopurinol', 'Allopurinol'), ('febuxostat', 'Febuxostat'), ('prednisone', 'Prednisone'), ('colchicine', 'Colchicine'), ('probenecid', 'Probenecid'), ('pegloticase', 'Pegloticase'), ('ibuprofen', 'Ibuprofen'), ('naproxen', 'Naproxen'), ('meloxicam', 'Meloxicam'), ('celecoxib', 'Celecoxib'), ('methylprednisolone', 'Methylprednisolone'), ('tinctureoftime', 'Tinctureoftime'), ('other', 'Other')], default='febuxostat', max_length=60),
        ),
        migrations.AlterField(
            model_name='ibuprofen',
            name='drug_class',
            field=models.CharField(choices=[('urate-lowering therapy', 'Urate-lowering therapy'), ('systemic steroid', 'Systemic steroid'), ('anti-inflammatory', 'Anti-inflammatory'), ('nonsteroidal antiinflammatory drug', 'Nonsteroidal anti-inflammatory drug'), ('urate extreagogue', 'Urate excretagogue'), ('local steroid', 'Local steroid'), ('recombinant uricase', 'Recombinant uricase'), ('other', 'Other')], default='nonsteroidal antiinflammatory drug', max_length=50),
        ),
        migrations.AlterField(
            model_name='ibuprofen',
            name='freq',
            field=models.CharField(blank=True, choices=[('qday', 'Once daily'), ('bid', 'Twice daily'), ('tid', 'Three times daily'), ('q2weeks', 'Every 2 weeks'), ('once', 'Once')], default='qday', max_length=50),
        ),
        migrations.AlterField(
            model_name='ibuprofen',
            name='generic_name',
            field=models.CharField(choices=[('allopurinol', 'Allopurinol'), ('febuxostat', 'Febuxostat'), ('prednisone', 'Prednisone'), ('colchicine', 'Colchicine'), ('probenecid', 'Probenecid'), ('pegloticase', 'Pegloticase'), ('ibuprofen', 'Ibuprofen'), ('naproxen', 'Naproxen'), ('meloxicam', 'Meloxicam'), ('celecoxib', 'Celecoxib'), ('methylprednisolone', 'Methylprednisolone'), ('tinctureoftime', 'Tinctureoftime'), ('other', 'Other')], default='ibuprofen', max_length=60),
        ),
        migrations.AlterField(
            model_name='ibuprofen',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meloxicam',
            name='as_prophylaxis',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Is this for flare prophylaxis while initiating ULT?', null=True, verbose_name='Flare prophylaxis?'),
        ),
        migrations.AlterField(
            model_name='meloxicam',
            name='drug_class',
            field=models.CharField(choices=[('urate-lowering therapy', 'Urate-lowering therapy'), ('systemic steroid', 'Systemic steroid'), ('anti-inflammatory', 'Anti-inflammatory'), ('nonsteroidal antiinflammatory drug', 'Nonsteroidal anti-inflammatory drug'), ('urate extreagogue', 'Urate excretagogue'), ('local steroid', 'Local steroid'), ('recombinant uricase', 'Recombinant uricase'), ('other', 'Other')], default='nonsteroidal antiinflammatory drug', max_length=50),
        ),
        migrations.AlterField(
            model_name='meloxicam',
            name='freq',
            field=models.CharField(blank=True, choices=[('qday', 'Once daily'), ('bid', 'Twice daily'), ('tid', 'Three times daily'), ('q2weeks', 'Every 2 weeks'), ('once', 'Once')], default='qday', max_length=50),
        ),
        migrations.AlterField(
            model_name='meloxicam',
            name='generic_name',
            field=models.CharField(choices=[('allopurinol', 'Allopurinol'), ('febuxostat', 'Febuxostat'), ('prednisone', 'Prednisone'), ('colchicine', 'Colchicine'), ('probenecid', 'Probenecid'), ('pegloticase', 'Pegloticase'), ('ibuprofen', 'Ibuprofen'), ('naproxen', 'Naproxen'), ('meloxicam', 'Meloxicam'), ('celecoxib', 'Celecoxib'), ('methylprednisolone', 'Methylprednisolone'), ('tinctureoftime', 'Tinctureoftime'), ('other', 'Other')], default='meloxicam', max_length=60),
        ),
        migrations.AlterField(
            model_name='meloxicam',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='methylprednisolone',
            name='drug_class',
            field=models.CharField(choices=[('urate-lowering therapy', 'Urate-lowering therapy'), ('systemic steroid', 'Systemic steroid'), ('anti-inflammatory', 'Anti-inflammatory'), ('nonsteroidal antiinflammatory drug', 'Nonsteroidal anti-inflammatory drug'), ('urate extreagogue', 'Urate excretagogue'), ('local steroid', 'Local steroid'), ('recombinant uricase', 'Recombinant uricase'), ('other', 'Other')], default='local steroid', max_length=50),
        ),
        migrations.AlterField(
            model_name='methylprednisolone',
            name='freq',
            field=models.CharField(blank=True, choices=[('qday', 'Once daily'), ('bid', 'Twice daily'), ('tid', 'Three times daily'), ('q2weeks', 'Every 2 weeks'), ('once', 'Once')], default='qday', max_length=50),
        ),
        migrations.AlterField(
            model_name='methylprednisolone',
            name='generic_name',
            field=models.CharField(choices=[('allopurinol', 'Allopurinol'), ('febuxostat', 'Febuxostat'), ('prednisone', 'Prednisone'), ('colchicine', 'Colchicine'), ('probenecid', 'Probenecid'), ('pegloticase', 'Pegloticase'), ('ibuprofen', 'Ibuprofen'), ('naproxen', 'Naproxen'), ('meloxicam', 'Meloxicam'), ('celecoxib', 'Celecoxib'), ('methylprednisolone', 'Methylprednisolone'), ('tinctureoftime', 'Tinctureoftime'), ('other', 'Other')], default='methylprednisolone', max_length=60),
        ),
        migrations.AlterField(
            model_name='methylprednisolone',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='naproxen',
            name='drug_class',
            field=models.CharField(choices=[('urate-lowering therapy', 'Urate-lowering therapy'), ('systemic steroid', 'Systemic steroid'), ('anti-inflammatory', 'Anti-inflammatory'), ('nonsteroidal antiinflammatory drug', 'Nonsteroidal anti-inflammatory drug'), ('urate extreagogue', 'Urate excretagogue'), ('local steroid', 'Local steroid'), ('recombinant uricase', 'Recombinant uricase'), ('other', 'Other')], default='nonsteroidal antiinflammatory drug', max_length=50),
        ),
        migrations.AlterField(
            model_name='naproxen',
            name='freq',
            field=models.CharField(blank=True, choices=[('qday', 'Once daily'), ('bid', 'Twice daily'), ('tid', 'Three times daily'), ('q2weeks', 'Every 2 weeks'), ('once', 'Once')], default='qday', max_length=50),
        ),
        migrations.AlterField(
            model_name='naproxen',
            name='generic_name',
            field=models.CharField(choices=[('allopurinol', 'Allopurinol'), ('febuxostat', 'Febuxostat'), ('prednisone', 'Prednisone'), ('colchicine', 'Colchicine'), ('probenecid', 'Probenecid'), ('pegloticase', 'Pegloticase'), ('ibuprofen', 'Ibuprofen'), ('naproxen', 'Naproxen'), ('meloxicam', 'Meloxicam'), ('celecoxib', 'Celecoxib'), ('methylprednisolone', 'Methylprednisolone'), ('tinctureoftime', 'Tinctureoftime'), ('other', 'Other')], default='naproxen', max_length=60),
        ),
        migrations.AlterField(
            model_name='naproxen',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prednisone',
            name='drug_class',
            field=models.CharField(choices=[('urate-lowering therapy', 'Urate-lowering therapy'), ('systemic steroid', 'Systemic steroid'), ('anti-inflammatory', 'Anti-inflammatory'), ('nonsteroidal antiinflammatory drug', 'Nonsteroidal anti-inflammatory drug'), ('urate extreagogue', 'Urate excretagogue'), ('local steroid', 'Local steroid'), ('recombinant uricase', 'Recombinant uricase'), ('other', 'Other')], default='systemic steroid', max_length=50),
        ),
        migrations.AlterField(
            model_name='prednisone',
            name='freq',
            field=models.CharField(blank=True, choices=[('qday', 'Once daily'), ('bid', 'Twice daily'), ('tid', 'Three times daily'), ('q2weeks', 'Every 2 weeks'), ('once', 'Once')], default='qday', max_length=50),
        ),
        migrations.AlterField(
            model_name='prednisone',
            name='generic_name',
            field=models.CharField(choices=[('allopurinol', 'Allopurinol'), ('febuxostat', 'Febuxostat'), ('prednisone', 'Prednisone'), ('colchicine', 'Colchicine'), ('probenecid', 'Probenecid'), ('pegloticase', 'Pegloticase'), ('ibuprofen', 'Ibuprofen'), ('naproxen', 'Naproxen'), ('meloxicam', 'Meloxicam'), ('celecoxib', 'Celecoxib'), ('methylprednisolone', 'Methylprednisolone'), ('tinctureoftime', 'Tinctureoftime'), ('other', 'Other')], default='prednisone', max_length=60),
        ),
        migrations.AlterField(
            model_name='prednisone',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='probenecid',
            name='drug_class',
            field=models.CharField(choices=[('urate-lowering therapy', 'Urate-lowering therapy'), ('systemic steroid', 'Systemic steroid'), ('anti-inflammatory', 'Anti-inflammatory'), ('nonsteroidal antiinflammatory drug', 'Nonsteroidal anti-inflammatory drug'), ('urate extreagogue', 'Urate excretagogue'), ('local steroid', 'Local steroid'), ('recombinant uricase', 'Recombinant uricase'), ('other', 'Other')], default='urate extreagogue', max_length=50),
        ),
        migrations.AlterField(
            model_name='probenecid',
            name='freq',
            field=models.CharField(choices=[('qday', 'Once daily'), ('bid', 'Twice daily'), ('tid', 'Three times daily'), ('q2weeks', 'Every 2 weeks'), ('once', 'Once')], default='bid', max_length=50),
        ),
        migrations.AlterField(
            model_name='probenecid',
            name='generic_name',
            field=models.CharField(choices=[('allopurinol', 'Allopurinol'), ('febuxostat', 'Febuxostat'), ('prednisone', 'Prednisone'), ('colchicine', 'Colchicine'), ('probenecid', 'Probenecid'), ('pegloticase', 'Pegloticase'), ('ibuprofen', 'Ibuprofen'), ('naproxen', 'Naproxen'), ('meloxicam', 'Meloxicam'), ('celecoxib', 'Celecoxib'), ('methylprednisolone', 'Methylprednisolone'), ('tinctureoftime', 'Tinctureoftime'), ('other', 'Other')], default='probenecid', max_length=60),
        ),
    ]
