# Generated by Django 3.1.7 on 2021-04-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allopurinol',
            name='dose',
            field=models.IntegerField(choices=[(50, '50 mg'), (100, '100 mg'), (150, '150 mg'), (200, '200 mg'), (250, '250 mg'), (300, '300 mg'), (350, '350 mg'), (400, '400 mg'), (450, '450 mg'), (500, '500 mg'), (550, '550 mg'), (600, '600 mg'), (650, '650 mg'), (700, '700 mg'), (750, '750 mg'), (800, '800 mg'), (850, '850 mg'), (900, '900 mg')], default=50),
            preserve_default=False,
        ),
    ]
