# Generated by Django 3.1.7 on 2021-04-13 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0002_allopurinol_dose'),
    ]

    operations = [
        migrations.AddField(
            model_name='allopurinol',
            name='de_sensitized',
            field=models.BooleanField(blank=True, help_text='Have you been de-sensitized to allopurinol?', null=True),
        ),
        migrations.AddField(
            model_name='allopurinol',
            name='drug_class',
            field=models.CharField(choices=[('urate-lowering therapy', 'Urate-lowering therapy'), ('systemic steroid', 'Systemic steroid'), ('anti-inflammatory', 'Anti-inflammatory'), ('nonsteroidal antiinflammatory drug', 'Nonsteroidal anti-inflammatory drug'), ('urate extreagogue', 'Urate excretagogue'), ('local steroid', 'Local steroid'), ('recombinant uricase', 'Recombinant uricase')], default='urate-lowering therapy', max_length=50),
        ),
        migrations.AddField(
            model_name='allopurinol',
            name='freq',
            field=models.CharField(choices=[('qday', 'Once daily'), ('bid', 'Twice daily'), ('tid', 'Three times daily'), ('qday prn', 'Once daily as needed'), ('bid prn', 'Twice daily as needed'), ('q2weeks', 'Every 2 weeks')], default='qday', max_length=50),
        ),
        migrations.AddField(
            model_name='allopurinol',
            name='side_effects',
            field=models.CharField(blank=True, choices=[('rash', 'rash'), ('Hypersensitivity syndrome', 'Hypersensitivity syndrome'), ('Elevated LFTs', 'Elevated LFTs'), ('Cytopenias', 'Cytopenias'), ('GI upset', 'GI upset')], help_text='Have you had any side effects?', max_length=100, null=True),
        ),
    ]
