# Generated by Django 3.1.7 on 2021-08-11 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('treatment', '0002_auto_20210810_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allopurinol',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='celecoxib',
            name='prn',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=True, help_text='Do you take this medication only as needed (PRN)?', null=True),
        ),
        migrations.AlterField(
            model_name='celecoxib',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='colchicine',
            name='prn',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=True, help_text='Do you take this medication only as needed (PRN)?', null=True),
        ),
        migrations.AlterField(
            model_name='colchicine',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='febuxostat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ibuprofen',
            name='prn',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=True, help_text='Do you take this medication only as needed (PRN)?', null=True),
        ),
        migrations.AlterField(
            model_name='ibuprofen',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meloxicam',
            name='prn',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=True, help_text='Do you take this medication only as needed (PRN)?', null=True),
        ),
        migrations.AlterField(
            model_name='meloxicam',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='methylprednisolone',
            name='prn',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=True, help_text='Do you take this medication only as needed (PRN)?', null=True),
        ),
        migrations.AlterField(
            model_name='methylprednisolone',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='naproxen',
            name='prn',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=True, help_text='Do you take this medication only as needed (PRN)?', null=True),
        ),
        migrations.AlterField(
            model_name='naproxen',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='othertreat',
            name='prn',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=True, help_text='Do you take this medication only as needed (PRN)?', null=True),
        ),
        migrations.AlterField(
            model_name='othertreat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prednisone',
            name='prn',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=True, help_text='Do you take this medication only as needed (PRN)?', null=True),
        ),
        migrations.AlterField(
            model_name='prednisone',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='probenecid',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tinctureoftime',
            name='prn',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=True, help_text='Do you take this medication only as needed (PRN)?', null=True),
        ),
        migrations.AlterField(
            model_name='tinctureoftime',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
