# Generated by Django 3.1.7 on 2021-12-16 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flareaid', '0002_flareaid_flare'),
        ('treatment', '0002_auto_20211215_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='celecoxib',
            name='flareaid',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flareaid.flareaid'),
        ),
        migrations.AddField(
            model_name='colchicine',
            name='flareaid',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flareaid.flareaid'),
        ),
        migrations.AddField(
            model_name='ibuprofen',
            name='flareaid',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flareaid.flareaid'),
        ),
        migrations.AddField(
            model_name='indomethacin',
            name='flareaid',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flareaid.flareaid'),
        ),
        migrations.AddField(
            model_name='meloxicam',
            name='flareaid',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flareaid.flareaid'),
        ),
        migrations.AddField(
            model_name='methylprednisolone',
            name='flareaid',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flareaid.flareaid'),
        ),
        migrations.AddField(
            model_name='naproxen',
            name='flareaid',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flareaid.flareaid'),
        ),
        migrations.AddField(
            model_name='othertreat',
            name='flareaid',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flareaid.flareaid'),
        ),
        migrations.AddField(
            model_name='prednisone',
            name='flareaid',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flareaid.flareaid'),
        ),
        migrations.AddField(
            model_name='tinctureoftime',
            name='flareaid',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flareaid.flareaid'),
        ),
    ]
