# Generated by Django 3.1.7 on 2021-12-18 14:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0003_auto_20211216_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colchicine',
            name='dose',
            field=models.FloatField(blank=True, choices=[(0.6, '0.6 mg'), (Decimal('1.2'), '1.2 mg')], default=1.2, null=True),
        ),
        migrations.AlterField(
            model_name='colchicine',
            name='dose2',
            field=models.FloatField(blank=True, choices=[(0.6, '0.6 mg'), (Decimal('1.2'), '1.2 mg')], default=0.6, null=True),
        ),
        migrations.AlterField(
            model_name='colchicine',
            name='dose3',
            field=models.FloatField(blank=True, choices=[(0.6, '0.6 mg'), (Decimal('1.2'), '1.2 mg')], default=0.6, null=True),
        ),
    ]
