# Generated by Django 3.1.7 on 2022-01-11 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0003_auto_20220108_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='celecoxib',
            name='prophylaxis_finished',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=None, help_text='Are you finished with flare prophylaxis?', null=True, verbose_name='Is prophylaxis finished?'),
        ),
        migrations.AddField(
            model_name='colchicine',
            name='prophylaxis_finished',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=None, help_text='Are you finished with flare prophylaxis?', null=True, verbose_name='Is prophylaxis finished?'),
        ),
        migrations.AddField(
            model_name='ibuprofen',
            name='prophylaxis_finished',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=None, help_text='Are you finished with flare prophylaxis?', null=True, verbose_name='Is prophylaxis finished?'),
        ),
        migrations.AddField(
            model_name='indomethacin',
            name='prophylaxis_finished',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=None, help_text='Are you finished with flare prophylaxis?', null=True, verbose_name='Is prophylaxis finished?'),
        ),
        migrations.AddField(
            model_name='meloxicam',
            name='prophylaxis_finished',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=None, help_text='Are you finished with flare prophylaxis?', null=True, verbose_name='Is prophylaxis finished?'),
        ),
        migrations.AddField(
            model_name='methylprednisolone',
            name='prophylaxis_finished',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=None, help_text='Are you finished with flare prophylaxis?', null=True, verbose_name='Is prophylaxis finished?'),
        ),
        migrations.AddField(
            model_name='naproxen',
            name='prophylaxis_finished',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=None, help_text='Are you finished with flare prophylaxis?', null=True, verbose_name='Is prophylaxis finished?'),
        ),
        migrations.AddField(
            model_name='othertreat',
            name='prophylaxis_finished',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=None, help_text='Are you finished with flare prophylaxis?', null=True, verbose_name='Is prophylaxis finished?'),
        ),
        migrations.AddField(
            model_name='prednisone',
            name='prophylaxis_finished',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=None, help_text='Are you finished with flare prophylaxis?', null=True, verbose_name='Is prophylaxis finished?'),
        ),
        migrations.AddField(
            model_name='tinctureoftime',
            name='prophylaxis_finished',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=None, help_text='Are you finished with flare prophylaxis?', null=True, verbose_name='Is prophylaxis finished?'),
        ),
    ]
