# Generated by Django 3.1.7 on 2021-04-22 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0003_auto_20210422_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celecoxib',
            name='dose',
            field=models.IntegerField(choices=[(200, '200 mg'), (400, '400 mg')]),
        ),
        migrations.AlterField(
            model_name='colchicine',
            name='dose',
            field=models.IntegerField(choices=[(0.6, '0.6 mg')]),
        ),
    ]
