# Generated by Django 3.1.7 on 2021-08-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0003_auto_20210811_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meloxicam',
            name='dose',
            field=models.DecimalField(blank=True, decimal_places=1, default=15.0, max_digits=3, null=True),
        ),
    ]
