# Generated by Django 3.1.7 on 2021-12-19 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ppxaid', '0001_initial'),
        ('ultaid', '0006_ultaid_titrating'),
        ('treatment', '0004_auto_20211218_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='allopurinol',
            name='ultaid',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ultaid.ultaid'),
        ),
        migrations.AddField(
            model_name='celecoxib',
            name='date_ended',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='celecoxib',
            name='date_started',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='celecoxib',
            name='ppxaid',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ppxaid.ppxaid'),
        ),
        migrations.AddField(
            model_name='colchicine',
            name='date_ended',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='colchicine',
            name='date_started',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='colchicine',
            name='ppxaid',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ppxaid.ppxaid'),
        ),
        migrations.AddField(
            model_name='febuxostat',
            name='ultaid',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ultaid.ultaid'),
        ),
        migrations.AddField(
            model_name='ibuprofen',
            name='date_ended',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibuprofen',
            name='date_started',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibuprofen',
            name='ppxaid',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ppxaid.ppxaid'),
        ),
        migrations.AddField(
            model_name='indomethacin',
            name='date_ended',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indomethacin',
            name='date_started',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indomethacin',
            name='ppxaid',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ppxaid.ppxaid'),
        ),
        migrations.AddField(
            model_name='meloxicam',
            name='date_ended',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meloxicam',
            name='date_started',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meloxicam',
            name='ppxaid',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ppxaid.ppxaid'),
        ),
        migrations.AddField(
            model_name='methylprednisolone',
            name='date_ended',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='methylprednisolone',
            name='date_started',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='methylprednisolone',
            name='ppxaid',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ppxaid.ppxaid'),
        ),
        migrations.AddField(
            model_name='naproxen',
            name='date_ended',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='naproxen',
            name='date_started',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='naproxen',
            name='ppxaid',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ppxaid.ppxaid'),
        ),
        migrations.AddField(
            model_name='othertreat',
            name='date_ended',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='othertreat',
            name='date_started',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='othertreat',
            name='ppxaid',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ppxaid.ppxaid'),
        ),
        migrations.AddField(
            model_name='prednisone',
            name='date_ended',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prednisone',
            name='date_started',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prednisone',
            name='ppxaid',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ppxaid.ppxaid'),
        ),
        migrations.AddField(
            model_name='probenecid',
            name='ultaid',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ultaid.ultaid'),
        ),
        migrations.AddField(
            model_name='tinctureoftime',
            name='date_ended',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tinctureoftime',
            name='date_started',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tinctureoftime',
            name='ppxaid',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ppxaid.ppxaid'),
        ),
        migrations.AlterField(
            model_name='allopurinol',
            name='dose',
            field=models.IntegerField(choices=[(50, '50 mg'), (100, '100 mg'), (150, '150 mg'), (200, '200 mg'), (250, '250 mg'), (300, '300 mg'), (350, '350 mg'), (400, '400 mg'), (450, '450 mg'), (500, '500 mg'), (550, '550 mg'), (600, '600 mg'), (650, '650 mg'), (700, '700 mg'), (750, '750 mg'), (800, '800 mg'), (850, '850 mg'), (900, '900 mg')], default=100),
        ),
        migrations.AlterField(
            model_name='allopurinol',
            name='freq',
            field=models.CharField(choices=[('daily', 'Once daily'), ('twice daily', 'Twice daily'), ('three times daily', 'Three times daily'), ('every other week', 'Every 2 weeks'), ('once', 'Once')], default='daily', max_length=50),
        ),
        migrations.AlterField(
            model_name='celecoxib',
            name='freq',
            field=models.CharField(blank=True, choices=[('daily', 'Once daily'), ('twice daily', 'Twice daily'), ('three times daily', 'Three times daily'), ('every other week', 'Every 2 weeks'), ('once', 'Once')], default='daily', max_length=50),
        ),
        migrations.AlterField(
            model_name='colchicine',
            name='freq',
            field=models.CharField(blank=True, choices=[('daily', 'Once daily'), ('twice daily', 'Twice daily'), ('three times daily', 'Three times daily'), ('every other week', 'Every 2 weeks'), ('once', 'Once')], default='once', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='colchicine',
            name='freq2',
            field=models.CharField(blank=True, choices=[('daily', 'Once daily'), ('twice daily', 'Twice daily'), ('three times daily', 'Three times daily'), ('every other week', 'Every 2 weeks'), ('once', 'Once')], default='once', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='colchicine',
            name='freq3',
            field=models.CharField(blank=True, choices=[('daily', 'Once daily'), ('twice daily', 'Twice daily'), ('three times daily', 'Three times daily'), ('every other week', 'Every 2 weeks'), ('once', 'Once')], default='twice daily', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='febuxostat',
            name='dose',
            field=models.IntegerField(choices=[(20, '20 mg'), (40, '40 mg'), (60, '60 mg'), (80, '80 mg'), (100, '100 mg'), (120, '120 mg')], default=40),
        ),
        migrations.AlterField(
            model_name='febuxostat',
            name='freq',
            field=models.CharField(choices=[('daily', 'Once daily'), ('twice daily', 'Twice daily'), ('three times daily', 'Three times daily'), ('every other week', 'Every 2 weeks'), ('once', 'Once')], default='daily', max_length=50),
        ),
        migrations.AlterField(
            model_name='ibuprofen',
            name='dose',
            field=models.IntegerField(blank=True, choices=[(200, '200 mg'), (400, '400 mg'), (600, '600 mg'), (800, '800 mg')], default=800, null=True),
        ),
        migrations.AlterField(
            model_name='ibuprofen',
            name='freq',
            field=models.CharField(blank=True, choices=[('daily', 'Once daily'), ('twice daily', 'Twice daily'), ('three times daily', 'Three times daily'), ('every other week', 'Every 2 weeks'), ('once', 'Once')], default='three times daily', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='indomethacin',
            name='freq',
            field=models.CharField(blank=True, choices=[('daily', 'Once daily'), ('twice daily', 'Twice daily'), ('three times daily', 'Three times daily'), ('every other week', 'Every 2 weeks'), ('once', 'Once')], default='daily', max_length=50),
        ),
        migrations.AlterField(
            model_name='meloxicam',
            name='freq',
            field=models.CharField(blank=True, choices=[('daily', 'Once daily'), ('twice daily', 'Twice daily'), ('three times daily', 'Three times daily'), ('every other week', 'Every 2 weeks'), ('once', 'Once')], default='daily', max_length=50),
        ),
        migrations.AlterField(
            model_name='methylprednisolone',
            name='freq',
            field=models.CharField(blank=True, choices=[('daily', 'Once daily'), ('twice daily', 'Twice daily'), ('three times daily', 'Three times daily'), ('every other week', 'Every 2 weeks'), ('once', 'Once')], default='daily', max_length=50),
        ),
        migrations.AlterField(
            model_name='naproxen',
            name='dose',
            field=models.IntegerField(blank=True, choices=[(220, '220 mg'), (250, '250 mg'), (440, '440 mg'), (500, '500 mg')], default=440, null=True),
        ),
        migrations.AlterField(
            model_name='naproxen',
            name='freq',
            field=models.CharField(blank=True, choices=[('daily', 'Once daily'), ('twice daily', 'Twice daily'), ('three times daily', 'Three times daily'), ('every other week', 'Every 2 weeks'), ('once', 'Once')], default='twice daily', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='othertreat',
            name='freq',
            field=models.CharField(blank=True, choices=[('daily', 'Once daily'), ('twice daily', 'Twice daily'), ('three times daily', 'Three times daily'), ('every other week', 'Every 2 weeks'), ('once', 'Once')], default='daily', help_text='Any optional information on your frequency?', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prednisone',
            name='freq',
            field=models.CharField(blank=True, choices=[('daily', 'Once daily'), ('twice daily', 'Twice daily'), ('three times daily', 'Three times daily'), ('every other week', 'Every 2 weeks'), ('once', 'Once')], default='daily', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prednisone',
            name='freq2',
            field=models.CharField(blank=True, choices=[('daily', 'Once daily'), ('twice daily', 'Twice daily'), ('three times daily', 'Three times daily'), ('every other week', 'Every 2 weeks'), ('once', 'Once')], default='daily', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='probenecid',
            name='freq',
            field=models.CharField(choices=[('daily', 'Once daily'), ('twice daily', 'Twice daily'), ('three times daily', 'Three times daily'), ('every other week', 'Every 2 weeks'), ('once', 'Once')], default='twice daily', max_length=50),
        ),
        migrations.AlterField(
            model_name='tinctureoftime',
            name='freq',
            field=models.CharField(blank=True, choices=[('daily', 'Once daily'), ('twice daily', 'Twice daily'), ('three times daily', 'Three times daily'), ('every other week', 'Every 2 weeks'), ('once', 'Once')], default='daily', help_text='Any optional information on your frequency?', max_length=50, null=True),
        ),
    ]
