# Generated by Django 3.1.7 on 2021-08-11 17:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0004_auto_20210811_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colchicine',
            name='dose',
            field=models.DecimalField(blank=True, choices=[(Decimal('0.6'), '0.6 mg')], decimal_places=1, default=Decimal('0.6'), max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='meloxicam',
            name='dose',
            field=models.DecimalField(blank=True, choices=[(Decimal('7.5'), '7.5 mg'), (Decimal('15'), '15 mg')], decimal_places=1, default=Decimal('15.0'), max_digits=3, null=True),
        ),
    ]
