# Generated by Django 3.1.7 on 2022-01-13 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0004_auto_20220112_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='allopurinol',
            name='intolerant',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Are you intolerant or should / will not take <django.db.models.fields.CharField>?', verbose_name='Intolerance'),
        ),
        migrations.AddField(
            model_name='celecoxib',
            name='intolerant',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Are you intolerant or should / will not take <django.db.models.fields.CharField>?', verbose_name='Intolerance'),
        ),
        migrations.AddField(
            model_name='colchicine',
            name='intolerant',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Are you intolerant or should / will not take <django.db.models.fields.CharField>?', verbose_name='Intolerance'),
        ),
        migrations.AddField(
            model_name='febuxostat',
            name='intolerant',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Are you intolerant or should / will not take <django.db.models.fields.CharField>?', verbose_name='Intolerance'),
        ),
        migrations.AddField(
            model_name='ibuprofen',
            name='intolerant',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Are you intolerant or should / will not take <django.db.models.fields.CharField>?', verbose_name='Intolerance'),
        ),
        migrations.AddField(
            model_name='indomethacin',
            name='intolerant',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Are you intolerant or should / will not take <django.db.models.fields.CharField>?', verbose_name='Intolerance'),
        ),
        migrations.AddField(
            model_name='meloxicam',
            name='intolerant',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Are you intolerant or should / will not take <django.db.models.fields.CharField>?', verbose_name='Intolerance'),
        ),
        migrations.AddField(
            model_name='methylprednisolone',
            name='intolerant',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Are you intolerant or should / will not take <django.db.models.fields.CharField>?', verbose_name='Intolerance'),
        ),
        migrations.AddField(
            model_name='naproxen',
            name='intolerant',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Are you intolerant or should / will not take <django.db.models.fields.CharField>?', verbose_name='Intolerance'),
        ),
        migrations.AddField(
            model_name='othertreat',
            name='intolerant',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Are you intolerant or should / will not take <django.db.models.fields.CharField>?', verbose_name='Intolerance'),
        ),
        migrations.AddField(
            model_name='prednisone',
            name='intolerant',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Are you intolerant or should / will not take <django.db.models.fields.CharField>?', verbose_name='Intolerance'),
        ),
        migrations.AddField(
            model_name='probenecid',
            name='intolerant',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Are you intolerant or should / will not take <django.db.models.fields.CharField>?', verbose_name='Intolerance'),
        ),
        migrations.AddField(
            model_name='tinctureoftime',
            name='intolerant',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Are you intolerant or should / will not take <django.db.models.fields.CharField>?', verbose_name='Intolerance'),
        ),
    ]
