# Generated by Django 3.1.7 on 2021-04-22 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0004_auto_20210422_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colchicine',
            name='dose',
            field=models.DecimalField(choices=[(0.6, '0.6 mg')], decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='ibuprofen',
            name='dose',
            field=models.IntegerField(choices=[(200, '200 mg'), (400, '400 mg'), (600, '600 mg'), (800, '800 mg')]),
        ),
        migrations.AlterField(
            model_name='meloxicam',
            name='dose',
            field=models.IntegerField(choices=[(7.5, '7.5 mg'), (15, '15 mg')]),
        ),
        migrations.AlterField(
            model_name='methylprednisolone',
            name='dose',
            field=models.IntegerField(choices=[(20, '20 mg'), (40, '40 mg'), (80, '80 mg')]),
        ),
        migrations.AlterField(
            model_name='naproxen',
            name='dose',
            field=models.IntegerField(choices=[(220, '220 mg'), (250, '250 mg'), (440, '440 mg'), (500, '500 mg')]),
        ),
    ]
