# Generated by Django 3.1.7 on 2022-01-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0004_auto_20220111_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colchicine',
            name='side_effects',
            field=models.CharField(blank=True, choices=[('GI upset', 'GI upset'), ('Medication interaction', 'Medication interaction'), ('None', 'None')], help_text='Have you had any side effects?', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='naproxen',
            name='side_effects',
            field=models.CharField(blank=True, choices=[('Rash', 'Rash'), ('Kidney failure', 'Kidney failure'), ('Stomach ulcer', 'Stomach ulcer'), ('GI upset', 'GI upset'), ('Medication interaction', 'Medication interaction'), ('None', 'None')], help_text='Have you had any side effects?', max_length=100, null=True),
        ),
    ]
