# Generated by Django 3.1.7 on 2021-12-21 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0005_auto_20211219_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allopurinol',
            name='ultaid',
        ),
        migrations.RemoveField(
            model_name='febuxostat',
            name='ultaid',
        ),
        migrations.RemoveField(
            model_name='probenecid',
            name='ultaid',
        ),
    ]
