# Generated by Django 3.1.7 on 2022-01-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0005_auto_20220111_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celecoxib',
            name='side_effects',
            field=models.CharField(blank=True, choices=[('Rash', 'Rash'), ('Kidney failure', 'Kidney failure'), ('Stomach ulcer', 'Stomach ulcer'), ('GI upset', 'GI upset'), ('Medication interaction', 'Medication interaction'), ('None', 'None')], help_text='Have you had any side effects?', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='indomethacin',
            name='side_effects',
            field=models.CharField(blank=True, choices=[('Rash', 'Rash'), ('Kidney failure', 'Kidney failure'), ('Stomach ulcer', 'Stomach ulcer'), ('GI upset', 'GI upset'), ('Medication interaction', 'Medication interaction'), ('None', 'None')], help_text='Have you had any side effects?', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='meloxicam',
            name='side_effects',
            field=models.CharField(blank=True, choices=[('Rash', 'Rash'), ('Kidney failure', 'Kidney failure'), ('Stomach ulcer', 'Stomach ulcer'), ('GI upset', 'GI upset'), ('Medication interaction', 'Medication interaction'), ('None', 'None')], help_text='Have you had any side effects?', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='methylprednisolone',
            name='side_effects',
            field=models.CharField(blank=True, choices=[('Bleeding', 'Bleeding'), ('Infection', 'Infection'), ('None', 'None')], help_text='Have you had any side effects?', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='othertreat',
            name='side_effects',
            field=models.CharField(blank=True, help_text='Have you had any side effects? Please list', max_length=400, null=True),
        ),
    ]
