# Generated by Django 3.1.7 on 2021-08-17 14:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0005_auto_20210811_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='tinctureoftime',
            name='duration',
            field=models.IntegerField(default=0, help_text='How long did it take to get better?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='celecoxib',
            name='dose',
            field=models.IntegerField(choices=[(200, '200 mg'), (400, '400 mg')], default=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='colchicine',
            name='dose',
            field=models.DecimalField(choices=[(Decimal('0.6'), '0.6 mg')], decimal_places=1, default=0.6, max_digits=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ibuprofen',
            name='dose',
            field=models.IntegerField(choices=[(200, '200 mg'), (400, '400 mg'), (600, '600 mg'), (800, '800 mg')], default=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meloxicam',
            name='dose',
            field=models.DecimalField(choices=[(Decimal('7.5'), '7.5 mg'), (Decimal('15'), '15 mg')], decimal_places=1, default=15, max_digits=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='methylprednisolone',
            name='dose',
            field=models.IntegerField(choices=[(20, '20 mg'), (40, '40 mg'), (80, '80 mg')], default=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='naproxen',
            name='dose',
            field=models.IntegerField(choices=[(220, '220 mg'), (250, '250 mg'), (440, '440 mg'), (500, '500 mg')], default=220),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='othertreat',
            name='name',
            field=models.CharField(default='Opium', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prednisone',
            name='dose',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
