# Generated by Django 3.1.7 on 2021-04-22 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0005_auto_20210422_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colchicine',
            name='dose',
            field=models.DecimalField(decimal_places=1, default=0.6, max_digits=2),
        ),
    ]
