# Generated by Django 3.1.7 on 2021-12-21 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ultplan', '0001_initial'),
        ('ppxaid', '0001_initial'),
        ('treatment', '0006_auto_20211221_2155'),
        ('flareaid', '0003_auto_20211219_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='allopurinol',
            name='ultplan',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ultplan.ultplan'),
        ),
        migrations.AddField(
            model_name='celecoxib',
            name='ultplan',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ultplan.ultplan'),
        ),
        migrations.AddField(
            model_name='colchicine',
            name='ultplan',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ultplan.ultplan'),
        ),
        migrations.AddField(
            model_name='febuxostat',
            name='ultplan',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ultplan.ultplan'),
        ),
        migrations.AddField(
            model_name='ibuprofen',
            name='ultplan',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ultplan.ultplan'),
        ),
        migrations.AddField(
            model_name='indomethacin',
            name='ultplan',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ultplan.ultplan'),
        ),
        migrations.AddField(
            model_name='meloxicam',
            name='ultplan',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ultplan.ultplan'),
        ),
        migrations.AddField(
            model_name='methylprednisolone',
            name='ultplan',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ultplan.ultplan'),
        ),
        migrations.AddField(
            model_name='naproxen',
            name='ultplan',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ultplan.ultplan'),
        ),
        migrations.AddField(
            model_name='othertreat',
            name='ultplan',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ultplan.ultplan'),
        ),
        migrations.AddField(
            model_name='prednisone',
            name='ultplan',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ultplan.ultplan'),
        ),
        migrations.AddField(
            model_name='probenecid',
            name='ultplan',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ultplan.ultplan'),
        ),
        migrations.AddField(
            model_name='tinctureoftime',
            name='ultplan',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ultplan.ultplan'),
        ),
        migrations.AlterField(
            model_name='celecoxib',
            name='flareaid',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='flareaid.flareaid'),
        ),
        migrations.AlterField(
            model_name='celecoxib',
            name='ppxaid',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ppxaid.ppxaid'),
        ),
        migrations.AlterField(
            model_name='colchicine',
            name='flareaid',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='flareaid.flareaid'),
        ),
        migrations.AlterField(
            model_name='colchicine',
            name='ppxaid',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ppxaid.ppxaid'),
        ),
        migrations.AlterField(
            model_name='ibuprofen',
            name='flareaid',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='flareaid.flareaid'),
        ),
        migrations.AlterField(
            model_name='ibuprofen',
            name='ppxaid',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ppxaid.ppxaid'),
        ),
        migrations.AlterField(
            model_name='indomethacin',
            name='flareaid',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='flareaid.flareaid'),
        ),
        migrations.AlterField(
            model_name='indomethacin',
            name='ppxaid',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ppxaid.ppxaid'),
        ),
        migrations.AlterField(
            model_name='meloxicam',
            name='flareaid',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='flareaid.flareaid'),
        ),
        migrations.AlterField(
            model_name='meloxicam',
            name='ppxaid',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ppxaid.ppxaid'),
        ),
        migrations.AlterField(
            model_name='methylprednisolone',
            name='flareaid',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='flareaid.flareaid'),
        ),
        migrations.AlterField(
            model_name='methylprednisolone',
            name='ppxaid',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ppxaid.ppxaid'),
        ),
        migrations.AlterField(
            model_name='naproxen',
            name='flareaid',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='flareaid.flareaid'),
        ),
        migrations.AlterField(
            model_name='naproxen',
            name='ppxaid',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ppxaid.ppxaid'),
        ),
        migrations.AlterField(
            model_name='othertreat',
            name='flareaid',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='flareaid.flareaid'),
        ),
        migrations.AlterField(
            model_name='othertreat',
            name='ppxaid',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ppxaid.ppxaid'),
        ),
        migrations.AlterField(
            model_name='prednisone',
            name='flareaid',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='flareaid.flareaid'),
        ),
        migrations.AlterField(
            model_name='prednisone',
            name='ppxaid',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ppxaid.ppxaid'),
        ),
        migrations.AlterField(
            model_name='tinctureoftime',
            name='flareaid',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='flareaid.flareaid'),
        ),
        migrations.AlterField(
            model_name='tinctureoftime',
            name='ppxaid',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ppxaid.ppxaid'),
        ),
    ]
