# Generated by Django 3.1.7 on 2021-08-28 16:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0006_auto_20210817_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colchicine',
            name='dose',
            field=models.DecimalField(choices=[(Decimal('0.6'), '0.6 mg')], decimal_places=1, default=Decimal('0.6'), max_digits=2),
        ),
        migrations.AlterField(
            model_name='ibuprofen',
            name='dose',
            field=models.IntegerField(blank=True, choices=[(200, '200 mg'), (400, '400 mg'), (600, '600 mg'), (800, '800 mg')], null=True),
        ),
    ]
