# Generated by Django 3.1.7 on 2022-01-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0006_historicalallopurinol_historicalcelecoxib_historicalcolchicine_historicalfebuxostat_historicalibupro'),
    ]

    operations = [
        migrations.AddField(
            model_name='allopurinol',
            name='active',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, help_text='Is this medication active?', verbose_name='Active Status'),
        ),
        migrations.AddField(
            model_name='celecoxib',
            name='active',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, help_text='Is this medication active?', verbose_name='Active Status'),
        ),
        migrations.AddField(
            model_name='colchicine',
            name='active',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, help_text='Is this medication active?', verbose_name='Active Status'),
        ),
        migrations.AddField(
            model_name='febuxostat',
            name='active',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, help_text='Is this medication active?', verbose_name='Active Status'),
        ),
        migrations.AddField(
            model_name='historicalallopurinol',
            name='active',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, help_text='Is this medication active?', verbose_name='Active Status'),
        ),
        migrations.AddField(
            model_name='historicalcelecoxib',
            name='active',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, help_text='Is this medication active?', verbose_name='Active Status'),
        ),
        migrations.AddField(
            model_name='historicalcolchicine',
            name='active',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, help_text='Is this medication active?', verbose_name='Active Status'),
        ),
        migrations.AddField(
            model_name='historicalfebuxostat',
            name='active',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, help_text='Is this medication active?', verbose_name='Active Status'),
        ),
        migrations.AddField(
            model_name='historicalibuprofen',
            name='active',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, help_text='Is this medication active?', verbose_name='Active Status'),
        ),
        migrations.AddField(
            model_name='historicalindomethacin',
            name='active',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, help_text='Is this medication active?', verbose_name='Active Status'),
        ),
        migrations.AddField(
            model_name='historicalmeloxicam',
            name='active',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, help_text='Is this medication active?', verbose_name='Active Status'),
        ),
        migrations.AddField(
            model_name='historicalmethylprednisolone',
            name='active',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, help_text='Is this medication active?', verbose_name='Active Status'),
        ),
        migrations.AddField(
            model_name='historicalnaproxen',
            name='active',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, help_text='Is this medication active?', verbose_name='Active Status'),
        ),
        migrations.AddField(
            model_name='historicalothertreat',
            name='active',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, help_text='Is this medication active?', verbose_name='Active Status'),
        ),
        migrations.AddField(
            model_name='historicalprednisone',
            name='active',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, help_text='Is this medication active?', verbose_name='Active Status'),
        ),
        migrations.AddField(
            model_name='historicalprobenecid',
            name='active',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, help_text='Is this medication active?', verbose_name='Active Status'),
        ),
        migrations.AddField(
            model_name='historicaltinctureoftime',
            name='active',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, help_text='Is this medication active?', verbose_name='Active Status'),
        ),
        migrations.AddField(
            model_name='ibuprofen',
            name='active',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, help_text='Is this medication active?', verbose_name='Active Status'),
        ),
        migrations.AddField(
            model_name='indomethacin',
            name='active',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, help_text='Is this medication active?', verbose_name='Active Status'),
        ),
        migrations.AddField(
            model_name='meloxicam',
            name='active',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, help_text='Is this medication active?', verbose_name='Active Status'),
        ),
        migrations.AddField(
            model_name='methylprednisolone',
            name='active',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, help_text='Is this medication active?', verbose_name='Active Status'),
        ),
        migrations.AddField(
            model_name='naproxen',
            name='active',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, help_text='Is this medication active?', verbose_name='Active Status'),
        ),
        migrations.AddField(
            model_name='othertreat',
            name='active',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, help_text='Is this medication active?', verbose_name='Active Status'),
        ),
        migrations.AddField(
            model_name='prednisone',
            name='active',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, help_text='Is this medication active?', verbose_name='Active Status'),
        ),
        migrations.AddField(
            model_name='probenecid',
            name='active',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, help_text='Is this medication active?', verbose_name='Active Status'),
        ),
        migrations.AddField(
            model_name='tinctureoftime',
            name='active',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, help_text='Is this medication active?', verbose_name='Active Status'),
        ),
    ]
