# Generated by Django 3.1.7 on 2021-04-23 02:07

import autoslug.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('treatment', '0006_auto_20210422_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allopurinol',
            name='generic_name',
            field=models.CharField(choices=[('allopurinol', 'Allopurinol'), ('febuxostat', 'Febuxostat'), ('prednisone', 'Prednisone'), ('colchicine', 'Colchicine'), ('probenecid', 'Probenecid'), ('pegloticase', 'Pegloticase'), ('ibuprofen', 'Ibuprofen'), ('naproxen', 'Naproxen'), ('meloxicam', 'Meloxicam'), ('celecoxib', 'Celecoxib'), ('methylprednisolone', 'Methylprednisolone')], default='allopurinol', max_length=60),
        ),
        migrations.AlterField(
            model_name='celecoxib',
            name='generic_name',
            field=models.CharField(choices=[('allopurinol', 'Allopurinol'), ('febuxostat', 'Febuxostat'), ('prednisone', 'Prednisone'), ('colchicine', 'Colchicine'), ('probenecid', 'Probenecid'), ('pegloticase', 'Pegloticase'), ('ibuprofen', 'Ibuprofen'), ('naproxen', 'Naproxen'), ('meloxicam', 'Meloxicam'), ('celecoxib', 'Celecoxib'), ('methylprednisolone', 'Methylprednisolone')], default='celecoxib', max_length=60),
        ),
        migrations.AlterField(
            model_name='colchicine',
            name='generic_name',
            field=models.CharField(choices=[('allopurinol', 'Allopurinol'), ('febuxostat', 'Febuxostat'), ('prednisone', 'Prednisone'), ('colchicine', 'Colchicine'), ('probenecid', 'Probenecid'), ('pegloticase', 'Pegloticase'), ('ibuprofen', 'Ibuprofen'), ('naproxen', 'Naproxen'), ('meloxicam', 'Meloxicam'), ('celecoxib', 'Celecoxib'), ('methylprednisolone', 'Methylprednisolone')], default='colchicine', max_length=60),
        ),
        migrations.AlterField(
            model_name='febuxostat',
            name='generic_name',
            field=models.CharField(choices=[('allopurinol', 'Allopurinol'), ('febuxostat', 'Febuxostat'), ('prednisone', 'Prednisone'), ('colchicine', 'Colchicine'), ('probenecid', 'Probenecid'), ('pegloticase', 'Pegloticase'), ('ibuprofen', 'Ibuprofen'), ('naproxen', 'Naproxen'), ('meloxicam', 'Meloxicam'), ('celecoxib', 'Celecoxib'), ('methylprednisolone', 'Methylprednisolone')], default='febuxostat', max_length=60),
        ),
        migrations.AlterField(
            model_name='ibuprofen',
            name='generic_name',
            field=models.CharField(choices=[('allopurinol', 'Allopurinol'), ('febuxostat', 'Febuxostat'), ('prednisone', 'Prednisone'), ('colchicine', 'Colchicine'), ('probenecid', 'Probenecid'), ('pegloticase', 'Pegloticase'), ('ibuprofen', 'Ibuprofen'), ('naproxen', 'Naproxen'), ('meloxicam', 'Meloxicam'), ('celecoxib', 'Celecoxib'), ('methylprednisolone', 'Methylprednisolone')], default='ibuprofen', max_length=60),
        ),
        migrations.AlterField(
            model_name='meloxicam',
            name='generic_name',
            field=models.CharField(choices=[('allopurinol', 'Allopurinol'), ('febuxostat', 'Febuxostat'), ('prednisone', 'Prednisone'), ('colchicine', 'Colchicine'), ('probenecid', 'Probenecid'), ('pegloticase', 'Pegloticase'), ('ibuprofen', 'Ibuprofen'), ('naproxen', 'Naproxen'), ('meloxicam', 'Meloxicam'), ('celecoxib', 'Celecoxib'), ('methylprednisolone', 'Methylprednisolone')], default='meloxicam', max_length=60),
        ),
        migrations.AlterField(
            model_name='methylprednisolone',
            name='generic_name',
            field=models.CharField(choices=[('allopurinol', 'Allopurinol'), ('febuxostat', 'Febuxostat'), ('prednisone', 'Prednisone'), ('colchicine', 'Colchicine'), ('probenecid', 'Probenecid'), ('pegloticase', 'Pegloticase'), ('ibuprofen', 'Ibuprofen'), ('naproxen', 'Naproxen'), ('meloxicam', 'Meloxicam'), ('celecoxib', 'Celecoxib'), ('methylprednisolone', 'Methylprednisolone')], default='methylprednisolone', max_length=60),
        ),
        migrations.AlterField(
            model_name='naproxen',
            name='generic_name',
            field=models.CharField(choices=[('allopurinol', 'Allopurinol'), ('febuxostat', 'Febuxostat'), ('prednisone', 'Prednisone'), ('colchicine', 'Colchicine'), ('probenecid', 'Probenecid'), ('pegloticase', 'Pegloticase'), ('ibuprofen', 'Ibuprofen'), ('naproxen', 'Naproxen'), ('meloxicam', 'Meloxicam'), ('celecoxib', 'Celecoxib'), ('methylprednisolone', 'Methylprednisolone')], default='naproxen', max_length=60),
        ),
        migrations.AlterField(
            model_name='prednisone',
            name='generic_name',
            field=models.CharField(choices=[('allopurinol', 'Allopurinol'), ('febuxostat', 'Febuxostat'), ('prednisone', 'Prednisone'), ('colchicine', 'Colchicine'), ('probenecid', 'Probenecid'), ('pegloticase', 'Pegloticase'), ('ibuprofen', 'Ibuprofen'), ('naproxen', 'Naproxen'), ('meloxicam', 'Meloxicam'), ('celecoxib', 'Celecoxib'), ('methylprednisolone', 'Methylprednisolone')], default='prednisone', max_length=60),
        ),
        migrations.CreateModel(
            name='Probenecid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('generic_name', models.CharField(choices=[('allopurinol', 'Allopurinol'), ('febuxostat', 'Febuxostat'), ('prednisone', 'Prednisone'), ('colchicine', 'Colchicine'), ('probenecid', 'Probenecid'), ('pegloticase', 'Pegloticase'), ('ibuprofen', 'Ibuprofen'), ('naproxen', 'Naproxen'), ('meloxicam', 'Meloxicam'), ('celecoxib', 'Celecoxib'), ('methylprednisolone', 'Methylprednisolone')], default='probenecid', max_length=60)),
                ('med_slug', autoslug.fields.AutoSlugField(editable=False, populate_from='generic_name', unique=True, verbose_name='Medication Name')),
                ('dose', models.IntegerField(choices=[(250, '250 mg'), (500, '500 mg'), (750, '750 mg'), (1000, '1000 mg')])),
                ('freq', models.CharField(choices=[('qday', 'Once daily'), ('bid', 'Twice daily'), ('tid', 'Three times daily'), ('qday prn', 'Once daily as needed'), ('bid prn', 'Twice daily as needed'), ('q2weeks', 'Every 2 weeks'), ('once', 'Once')], default='bid', max_length=50)),
                ('date_started', models.DateField(default=datetime.datetime.now)),
                ('date_ended', models.DateField(blank=True, null=True)),
                ('side_effects', models.CharField(blank=True, choices=[('Flushing', 'Flushing'), ('Headache', 'Headache')], help_text='Have you had any side effects?', max_length=100, null=True)),
                ('drug_class', models.CharField(choices=[('urate-lowering therapy', 'Urate-lowering therapy'), ('systemic steroid', 'Systemic steroid'), ('anti-inflammatory', 'Anti-inflammatory'), ('nonsteroidal antiinflammatory drug', 'Nonsteroidal anti-inflammatory drug'), ('urate extreagogue', 'Urate excretagogue'), ('local steroid', 'Local steroid'), ('recombinant uricase', 'Recombinant uricase')], default='urate extreagogue', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
