# Generated by Django 3.1.7 on 2021-12-28 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ultplan', '0001_initial'),
        ('treatment', '0007_auto_20211221_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allopurinol',
            name='ultplan',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ultplan.ultplan'),
        ),
        migrations.AlterField(
            model_name='febuxostat',
            name='ultplan',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ultplan.ultplan'),
        ),
        migrations.AlterField(
            model_name='probenecid',
            name='ultplan',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ultplan.ultplan'),
        ),
    ]
