# Generated by Django 3.1.7 on 2021-04-30 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('treatment', '0008_auto_20210427_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='allopurinol',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='allopurinol',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='febuxostat',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='febuxostat',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
