# Generated by Django 3.1.7 on 2022-01-01 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ultplan', '0003_ultplan_dose_adjustment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('treatment', '0008_auto_20211228_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allopurinol',
            name='date_ended',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='allopurinol',
            name='date_started',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='allopurinol',
            name='ultplan',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ultplan.ultplan'),
        ),
        migrations.AlterField(
            model_name='celecoxib',
            name='date_ended',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='colchicine',
            name='date_ended',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='febuxostat',
            name='date_ended',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='febuxostat',
            name='date_started',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='febuxostat',
            name='ultplan',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ultplan.ultplan'),
        ),
        migrations.AlterField(
            model_name='ibuprofen',
            name='date_ended',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='indomethacin',
            name='date_ended',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='meloxicam',
            name='date_ended',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='methylprednisolone',
            name='date_ended',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='naproxen',
            name='date_ended',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='othertreat',
            name='date_ended',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='prednisone',
            name='date_ended',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='probenecid',
            name='date_ended',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='probenecid',
            name='date_started',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='probenecid',
            name='ultplan',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ultplan.ultplan'),
        ),
        migrations.AlterField(
            model_name='tinctureoftime',
            name='date_ended',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='ProbenecidHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('generic_name', models.CharField(choices=[('allopurinol', 'Allopurinol'), ('febuxostat', 'Febuxostat'), ('indomethacin', 'Indomethacin'), ('prednisone', 'Prednisone'), ('colchicine', 'Colchicine'), ('probenecid', 'Probenecid'), ('pegloticase', 'Pegloticase'), ('ibuprofen', 'Ibuprofen'), ('naproxen', 'Naproxen'), ('meloxicam', 'Meloxicam'), ('celecoxib', 'Celecoxib'), ('methylprednisolone', 'Methylprednisolone'), ('tinctureoftime', 'Tinctureoftime'), ('other', 'Other')], max_length=60)),
                ('dose', models.IntegerField(blank=True, null=True)),
                ('freq', models.CharField(blank=True, choices=[('daily', 'Once daily'), ('twice daily', 'Twice daily'), ('three times daily', 'Three times daily'), ('every other week', 'Every 2 weeks'), ('once', 'Once')], default='daily', max_length=50, null=True)),
                ('side_effects', models.CharField(blank=True, help_text='Have you had any side effects?', max_length=100, null=True)),
                ('drug_class', models.CharField(choices=[('urate-lowering therapy', 'Urate-lowering therapy'), ('systemic steroid', 'Systemic steroid'), ('anti-inflammatory', 'Anti-inflammatory'), ('nonsteroidal anti-inflammatory drug', 'Nonsteroidal anti-inflammatory drug'), ('urate extreagogue', 'Urate excretagogue'), ('local steroid', 'Local steroid'), ('recombinant uricase', 'Recombinant uricase'), ('other', 'Other')], max_length=50)),
                ('date_ended', models.DateField(blank=True, default=None, null=True)),
                ('date_started', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('probenecid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment.probenecid')),
                ('ultplan', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ultplan.ultplan')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='FebuxostatHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('generic_name', models.CharField(choices=[('allopurinol', 'Allopurinol'), ('febuxostat', 'Febuxostat'), ('indomethacin', 'Indomethacin'), ('prednisone', 'Prednisone'), ('colchicine', 'Colchicine'), ('probenecid', 'Probenecid'), ('pegloticase', 'Pegloticase'), ('ibuprofen', 'Ibuprofen'), ('naproxen', 'Naproxen'), ('meloxicam', 'Meloxicam'), ('celecoxib', 'Celecoxib'), ('methylprednisolone', 'Methylprednisolone'), ('tinctureoftime', 'Tinctureoftime'), ('other', 'Other')], max_length=60)),
                ('dose', models.IntegerField(blank=True, null=True)),
                ('freq', models.CharField(blank=True, choices=[('daily', 'Once daily'), ('twice daily', 'Twice daily'), ('three times daily', 'Three times daily'), ('every other week', 'Every 2 weeks'), ('once', 'Once')], default='daily', max_length=50, null=True)),
                ('side_effects', models.CharField(blank=True, help_text='Have you had any side effects?', max_length=100, null=True)),
                ('drug_class', models.CharField(choices=[('urate-lowering therapy', 'Urate-lowering therapy'), ('systemic steroid', 'Systemic steroid'), ('anti-inflammatory', 'Anti-inflammatory'), ('nonsteroidal anti-inflammatory drug', 'Nonsteroidal anti-inflammatory drug'), ('urate extreagogue', 'Urate excretagogue'), ('local steroid', 'Local steroid'), ('recombinant uricase', 'Recombinant uricase'), ('other', 'Other')], max_length=50)),
                ('date_ended', models.DateField(blank=True, default=None, null=True)),
                ('date_started', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('febuxostat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment.febuxostat')),
                ('ultplan', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ultplan.ultplan')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='AllopurinolHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('generic_name', models.CharField(choices=[('allopurinol', 'Allopurinol'), ('febuxostat', 'Febuxostat'), ('indomethacin', 'Indomethacin'), ('prednisone', 'Prednisone'), ('colchicine', 'Colchicine'), ('probenecid', 'Probenecid'), ('pegloticase', 'Pegloticase'), ('ibuprofen', 'Ibuprofen'), ('naproxen', 'Naproxen'), ('meloxicam', 'Meloxicam'), ('celecoxib', 'Celecoxib'), ('methylprednisolone', 'Methylprednisolone'), ('tinctureoftime', 'Tinctureoftime'), ('other', 'Other')], max_length=60)),
                ('dose', models.IntegerField(blank=True, null=True)),
                ('freq', models.CharField(blank=True, choices=[('daily', 'Once daily'), ('twice daily', 'Twice daily'), ('three times daily', 'Three times daily'), ('every other week', 'Every 2 weeks'), ('once', 'Once')], default='daily', max_length=50, null=True)),
                ('side_effects', models.CharField(blank=True, help_text='Have you had any side effects?', max_length=100, null=True)),
                ('drug_class', models.CharField(choices=[('urate-lowering therapy', 'Urate-lowering therapy'), ('systemic steroid', 'Systemic steroid'), ('anti-inflammatory', 'Anti-inflammatory'), ('nonsteroidal anti-inflammatory drug', 'Nonsteroidal anti-inflammatory drug'), ('urate extreagogue', 'Urate excretagogue'), ('local steroid', 'Local steroid'), ('recombinant uricase', 'Recombinant uricase'), ('other', 'Other')], max_length=50)),
                ('date_ended', models.DateField(blank=True, default=None, null=True)),
                ('date_started', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('allopurinol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment.allopurinol')),
                ('ultplan', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ultplan.ultplan')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
