# Generated by Django 3.1.7 on 2021-09-14 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0008_auto_20210828_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allopurinol',
            name='drug_class',
            field=models.CharField(choices=[('urate-lowering therapy', 'Urate-lowering therapy'), ('systemic steroid', 'Systemic steroid'), ('anti-inflammatory', 'Anti-inflammatory'), ('nonsteroidal anti-inflammatory drug', 'Nonsteroidal anti-inflammatory drug'), ('urate extreagogue', 'Urate excretagogue'), ('local steroid', 'Local steroid'), ('recombinant uricase', 'Recombinant uricase'), ('other', 'Other')], default='urate-lowering therapy', max_length=50),
        ),
        migrations.AlterField(
            model_name='celecoxib',
            name='drug_class',
            field=models.CharField(choices=[('urate-lowering therapy', 'Urate-lowering therapy'), ('systemic steroid', 'Systemic steroid'), ('anti-inflammatory', 'Anti-inflammatory'), ('nonsteroidal anti-inflammatory drug', 'Nonsteroidal anti-inflammatory drug'), ('urate extreagogue', 'Urate excretagogue'), ('local steroid', 'Local steroid'), ('recombinant uricase', 'Recombinant uricase'), ('other', 'Other')], default='nonsteroidal anti-inflammatory drug', max_length=50),
        ),
        migrations.AlterField(
            model_name='colchicine',
            name='drug_class',
            field=models.CharField(choices=[('urate-lowering therapy', 'Urate-lowering therapy'), ('systemic steroid', 'Systemic steroid'), ('anti-inflammatory', 'Anti-inflammatory'), ('nonsteroidal anti-inflammatory drug', 'Nonsteroidal anti-inflammatory drug'), ('urate extreagogue', 'Urate excretagogue'), ('local steroid', 'Local steroid'), ('recombinant uricase', 'Recombinant uricase'), ('other', 'Other')], default='anti-inflammatory', max_length=50),
        ),
        migrations.AlterField(
            model_name='febuxostat',
            name='drug_class',
            field=models.CharField(choices=[('urate-lowering therapy', 'Urate-lowering therapy'), ('systemic steroid', 'Systemic steroid'), ('anti-inflammatory', 'Anti-inflammatory'), ('nonsteroidal anti-inflammatory drug', 'Nonsteroidal anti-inflammatory drug'), ('urate extreagogue', 'Urate excretagogue'), ('local steroid', 'Local steroid'), ('recombinant uricase', 'Recombinant uricase'), ('other', 'Other')], default='urate-lowering therapy', max_length=50),
        ),
        migrations.AlterField(
            model_name='ibuprofen',
            name='drug_class',
            field=models.CharField(choices=[('urate-lowering therapy', 'Urate-lowering therapy'), ('systemic steroid', 'Systemic steroid'), ('anti-inflammatory', 'Anti-inflammatory'), ('nonsteroidal anti-inflammatory drug', 'Nonsteroidal anti-inflammatory drug'), ('urate extreagogue', 'Urate excretagogue'), ('local steroid', 'Local steroid'), ('recombinant uricase', 'Recombinant uricase'), ('other', 'Other')], default='nonsteroidal anti-inflammatory drug', max_length=50),
        ),
        migrations.AlterField(
            model_name='meloxicam',
            name='drug_class',
            field=models.CharField(choices=[('urate-lowering therapy', 'Urate-lowering therapy'), ('systemic steroid', 'Systemic steroid'), ('anti-inflammatory', 'Anti-inflammatory'), ('nonsteroidal anti-inflammatory drug', 'Nonsteroidal anti-inflammatory drug'), ('urate extreagogue', 'Urate excretagogue'), ('local steroid', 'Local steroid'), ('recombinant uricase', 'Recombinant uricase'), ('other', 'Other')], default='nonsteroidal anti-inflammatory drug', max_length=50),
        ),
        migrations.AlterField(
            model_name='methylprednisolone',
            name='drug_class',
            field=models.CharField(choices=[('urate-lowering therapy', 'Urate-lowering therapy'), ('systemic steroid', 'Systemic steroid'), ('anti-inflammatory', 'Anti-inflammatory'), ('nonsteroidal anti-inflammatory drug', 'Nonsteroidal anti-inflammatory drug'), ('urate extreagogue', 'Urate excretagogue'), ('local steroid', 'Local steroid'), ('recombinant uricase', 'Recombinant uricase'), ('other', 'Other')], default='local steroid', max_length=50),
        ),
        migrations.AlterField(
            model_name='naproxen',
            name='drug_class',
            field=models.CharField(choices=[('urate-lowering therapy', 'Urate-lowering therapy'), ('systemic steroid', 'Systemic steroid'), ('anti-inflammatory', 'Anti-inflammatory'), ('nonsteroidal anti-inflammatory drug', 'Nonsteroidal anti-inflammatory drug'), ('urate extreagogue', 'Urate excretagogue'), ('local steroid', 'Local steroid'), ('recombinant uricase', 'Recombinant uricase'), ('other', 'Other')], default='nonsteroidal anti-inflammatory drug', max_length=50),
        ),
        migrations.AlterField(
            model_name='othertreat',
            name='drug_class',
            field=models.CharField(choices=[('urate-lowering therapy', 'Urate-lowering therapy'), ('systemic steroid', 'Systemic steroid'), ('anti-inflammatory', 'Anti-inflammatory'), ('nonsteroidal anti-inflammatory drug', 'Nonsteroidal anti-inflammatory drug'), ('urate extreagogue', 'Urate excretagogue'), ('local steroid', 'Local steroid'), ('recombinant uricase', 'Recombinant uricase'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='prednisone',
            name='drug_class',
            field=models.CharField(choices=[('urate-lowering therapy', 'Urate-lowering therapy'), ('systemic steroid', 'Systemic steroid'), ('anti-inflammatory', 'Anti-inflammatory'), ('nonsteroidal anti-inflammatory drug', 'Nonsteroidal anti-inflammatory drug'), ('urate extreagogue', 'Urate excretagogue'), ('local steroid', 'Local steroid'), ('recombinant uricase', 'Recombinant uricase'), ('other', 'Other')], default='systemic steroid', max_length=50),
        ),
        migrations.AlterField(
            model_name='probenecid',
            name='drug_class',
            field=models.CharField(choices=[('urate-lowering therapy', 'Urate-lowering therapy'), ('systemic steroid', 'Systemic steroid'), ('anti-inflammatory', 'Anti-inflammatory'), ('nonsteroidal anti-inflammatory drug', 'Nonsteroidal anti-inflammatory drug'), ('urate extreagogue', 'Urate excretagogue'), ('local steroid', 'Local steroid'), ('recombinant uricase', 'Recombinant uricase'), ('other', 'Other')], default='urate extreagogue', max_length=50),
        ),
        migrations.AlterField(
            model_name='tinctureoftime',
            name='drug_class',
            field=models.CharField(choices=[('urate-lowering therapy', 'Urate-lowering therapy'), ('systemic steroid', 'Systemic steroid'), ('anti-inflammatory', 'Anti-inflammatory'), ('nonsteroidal anti-inflammatory drug', 'Nonsteroidal anti-inflammatory drug'), ('urate extreagogue', 'Urate excretagogue'), ('local steroid', 'Local steroid'), ('recombinant uricase', 'Recombinant uricase'), ('other', 'Other')], default='tinctureoftime', max_length=50),
        ),
    ]
