# Generated by Django 3.1.7 on 2021-04-30 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0009_auto_20210430_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allopurinol',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='allopurinol',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='febuxostat',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='febuxostat',
            name='object_id',
        ),
    ]
