# Generated by Django 3.1.7 on 2022-01-02 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0010_auto_20220102_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='allopurinolhistory',
            name='de_sensitized',
            field=models.BooleanField(blank=True, help_text='Have you been de-sensitized to allopurinol?', null=True),
        ),
    ]
