# Generated by Django 3.1.7 on 2021-05-28 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0011_auto_20210510_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allopurinol',
            name='side_effects',
            field=models.CharField(blank=True, choices=[('Rash', 'Rash'), ('Hypersensitivity syndrome', 'Hypersensitivity syndrome'), ('Elevated LFTs', 'Elevated LFTs'), ('Cytopenias', 'Cytopenias'), ('GI upset', 'GI upset'), ('None', 'None')], help_text='Have you had any side effects?', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='celecoxib',
            name='as_prophylaxis',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Is this for flare prophylaxis while initiating ULT?', verbose_name='Flare prophylaxis?'),
        ),
        migrations.AlterField(
            model_name='celecoxib',
            name='date_started',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='celecoxib',
            name='dose',
            field=models.IntegerField(blank=True, choices=[(200, '200 mg'), (400, '400 mg')], null=True),
        ),
        migrations.AlterField(
            model_name='celecoxib',
            name='freq',
            field=models.CharField(blank=True, choices=[('qday', 'Once daily'), ('bid', 'Twice daily'), ('tid', 'Three times daily'), ('qday prn', 'Once daily as needed'), ('bid prn', 'Twice daily as needed'), ('q2weeks', 'Every 2 weeks'), ('once', 'Once')], default='qday', max_length=50),
        ),
        migrations.AlterField(
            model_name='celecoxib',
            name='side_effects',
            field=models.CharField(blank=True, choices=[('Rash', 'Rash'), ('Kidney failure', 'Kidney failure'), ('Stomach ulcer', 'Stomach ulcer'), ('GI upset', 'GI upset'), ('Medication interaction', 'Medication interaction'), ('None', 'None')], default='None', help_text='Have you had any side effects?', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='colchicine',
            name='as_prophylaxis',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Is this for flare prophylaxis while initiating ULT?', null=True, verbose_name='Flare prophylaxis?'),
        ),
        migrations.AlterField(
            model_name='colchicine',
            name='date_started',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='colchicine',
            name='dose',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.6, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='colchicine',
            name='freq',
            field=models.CharField(blank=True, choices=[('qday', 'Once daily'), ('bid', 'Twice daily'), ('tid', 'Three times daily'), ('qday prn', 'Once daily as needed'), ('bid prn', 'Twice daily as needed'), ('q2weeks', 'Every 2 weeks'), ('once', 'Once')], default='qday', max_length=50),
        ),
        migrations.AlterField(
            model_name='colchicine',
            name='side_effects',
            field=models.CharField(blank=True, choices=[('GI upset', 'GI upset'), ('Medication interaction', 'Medication interaction'), ('None', 'None')], default='None', help_text='Have you had any side effects?', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='febuxostat',
            name='side_effects',
            field=models.CharField(blank=True, choices=[('Rash', 'Rash'), ('Hypersensitivity syndrome', 'Hypersensitivity syndrome'), ('Elevated LFTs', 'Elevated LFTs'), ('Cytopenias', 'Cytopenias'), ('GI upset', 'GI upset'), ('None', 'None')], help_text='Have you had any side effects?', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ibuprofen',
            name='as_prophylaxis',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Is this for flare prophylaxis while initiating ULT?', null=True, verbose_name='Flare prophylaxis?'),
        ),
        migrations.AlterField(
            model_name='ibuprofen',
            name='date_started',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='ibuprofen',
            name='dose',
            field=models.IntegerField(blank=True, choices=[(200, '200 mg'), (400, '400 mg'), (600, '600 mg'), (800, '800 mg')], null=True),
        ),
        migrations.AlterField(
            model_name='ibuprofen',
            name='freq',
            field=models.CharField(blank=True, choices=[('qday', 'Once daily'), ('bid', 'Twice daily'), ('tid', 'Three times daily'), ('qday prn', 'Once daily as needed'), ('bid prn', 'Twice daily as needed'), ('q2weeks', 'Every 2 weeks'), ('once', 'Once')], default='qday', max_length=50),
        ),
        migrations.AlterField(
            model_name='ibuprofen',
            name='side_effects',
            field=models.CharField(blank=True, choices=[('Rash', 'Rash'), ('Kidney failure', 'Kidney failure'), ('Stomach ulcer', 'Stomach ulcer'), ('GI upset', 'GI upset'), ('Medication interaction', 'Medication interaction'), ('None', 'None')], help_text='Have you had any side effects?', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='meloxicam',
            name='as_prophylaxis',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Is this for flare prophylaxis while initiating ULT?', verbose_name='Flare prophylaxis?'),
        ),
        migrations.AlterField(
            model_name='meloxicam',
            name='date_started',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='meloxicam',
            name='dose',
            field=models.IntegerField(blank=True, choices=[(7.5, '7.5 mg'), (15, '15 mg')], null=True),
        ),
        migrations.AlterField(
            model_name='meloxicam',
            name='freq',
            field=models.CharField(blank=True, choices=[('qday', 'Once daily'), ('bid', 'Twice daily'), ('tid', 'Three times daily'), ('qday prn', 'Once daily as needed'), ('bid prn', 'Twice daily as needed'), ('q2weeks', 'Every 2 weeks'), ('once', 'Once')], default='qday', max_length=50),
        ),
        migrations.AlterField(
            model_name='meloxicam',
            name='side_effects',
            field=models.CharField(blank=True, choices=[('Rash', 'Rash'), ('Kidney failure', 'Kidney failure'), ('Stomach ulcer', 'Stomach ulcer'), ('GI upset', 'GI upset'), ('Medication interaction', 'Medication interaction'), ('None', 'None')], default='None', help_text='Have you had any side effects?', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='methylprednisolone',
            name='as_injection',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Was this given by an injection into your joint?', null=True, verbose_name='Given by joint injection?'),
        ),
        migrations.AlterField(
            model_name='methylprednisolone',
            name='date_started',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='methylprednisolone',
            name='dose',
            field=models.IntegerField(blank=True, choices=[(20, '20 mg'), (40, '40 mg'), (80, '80 mg')], null=True),
        ),
        migrations.AlterField(
            model_name='methylprednisolone',
            name='freq',
            field=models.CharField(blank=True, choices=[('qday', 'Once daily'), ('bid', 'Twice daily'), ('tid', 'Three times daily'), ('qday prn', 'Once daily as needed'), ('bid prn', 'Twice daily as needed'), ('q2weeks', 'Every 2 weeks'), ('once', 'Once')], default='qday', max_length=50),
        ),
        migrations.AlterField(
            model_name='methylprednisolone',
            name='side_effects',
            field=models.CharField(blank=True, choices=[('Bleeding', 'Bleeding'), ('Infection', 'Infection'), ('None', 'None')], default='None', help_text='Have you had any side effects?', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='naproxen',
            name='as_prophylaxis',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Is this for flare prophylaxis while initiating ULT?', null=True, verbose_name='Flare prophylaxis?'),
        ),
        migrations.AlterField(
            model_name='naproxen',
            name='date_started',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='naproxen',
            name='dose',
            field=models.IntegerField(blank=True, choices=[(220, '220 mg'), (250, '250 mg'), (440, '440 mg'), (500, '500 mg')], null=True),
        ),
        migrations.AlterField(
            model_name='naproxen',
            name='freq',
            field=models.CharField(blank=True, choices=[('qday', 'Once daily'), ('bid', 'Twice daily'), ('tid', 'Three times daily'), ('qday prn', 'Once daily as needed'), ('bid prn', 'Twice daily as needed'), ('q2weeks', 'Every 2 weeks'), ('once', 'Once')], default='qday', max_length=50),
        ),
        migrations.AlterField(
            model_name='naproxen',
            name='side_effects',
            field=models.CharField(blank=True, choices=[('Rash', 'Rash'), ('Kidney failure', 'Kidney failure'), ('Stomach ulcer', 'Stomach ulcer'), ('GI upset', 'GI upset'), ('Medication interaction', 'Medication interaction'), ('None', 'None')], default='None', help_text='Have you had any side effects?', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prednisone',
            name='as_prophylaxis',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Is this for flare prophylaxis while initiating ULT?', null=True, verbose_name='Flare prophylaxis?'),
        ),
        migrations.AlterField(
            model_name='prednisone',
            name='date_started',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='prednisone',
            name='dose',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prednisone',
            name='freq',
            field=models.CharField(blank=True, choices=[('qday', 'Once daily'), ('bid', 'Twice daily'), ('tid', 'Three times daily'), ('qday prn', 'Once daily as needed'), ('bid prn', 'Twice daily as needed'), ('q2weeks', 'Every 2 weeks'), ('once', 'Once')], default='qday', max_length=50),
        ),
        migrations.AlterField(
            model_name='prednisone',
            name='side_effects',
            field=models.CharField(blank=True, choices=[('Insomnia', 'Insomnia'), ('Weight gain', 'Weight gain'), ('Anxiety', 'Anxiety'), ('Hyperglycemia', 'Hyperglycemia'), ('Weakness', 'Weakness'), ('Easy bruising', 'Easy bruising'), ('Osteoporosis', 'Osteoporosis'), ('Cataract', 'Cataract'), ('Infection', 'Infection'), ('None', 'None')], help_text='Have you had any side effects?', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='probenecid',
            name='side_effects',
            field=models.CharField(blank=True, choices=[('Flushing', 'Flushing'), ('Headache', 'Headache'), ('None', 'None')], help_text='Have you had any side effects?', max_length=100, null=True),
        ),
    ]
