# Generated by Django 3.0.3 on 2020-04-27 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gout', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['last_name', 'first_name'], 'permissions': (('can_create_new_patient', 'Creates new patient'),)},
        ),
    ]
