# Generated by Django 3.0.3 on 2020-05-01 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gout', '0002_auto_20200427_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Urate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uric_acid', models.DecimalField(decimal_places=1, help_text='uric acid?', max_digits=3)),
                ('date', models.DateField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gout.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Creatinine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creatinine', models.DecimalField(decimal_places=2, help_text='creatinine', max_digits=4)),
                ('date', models.DateField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gout.Patient')),
            ],
        ),
    ]
