# Generated by Django 3.1.7 on 2021-04-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ult', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ult',
            name='freq_flares',
            field=models.CharField(choices=[('Under two', 'Under two'), ('Two or more', 'Two or more')], help_text='Approximately how many flares do you have per year?', max_length=30),
        ),
        migrations.AlterField(
            model_name='ult',
            name='num_flares',
            field=models.CharField(choices=[('one', 'One'), ('1-3', '1-3'), ('4-6', '4-6'), ('7 or more', '7 or more')], help_text='Approximately how many gout flares have you had?', max_length=30),
        ),
    ]
