# Generated by Django 3.1.7 on 2021-11-08 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_auto_20211108_1349'),
        ('ult', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ult',
            name='ckd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.ckd'),
        ),
        migrations.AlterField(
            model_name='ult',
            name='erosions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.erosions'),
        ),
        migrations.AlterField(
            model_name='ult',
            name='stones',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.uratekidneystones'),
        ),
        migrations.AlterField(
            model_name='ult',
            name='tophi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.tophi'),
        ),
    ]
