# Generated by Django 3.1.7 on 2022-02-19 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ult', '0001_initial'),
        ('history', '0002_auto_20220219_1527'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ult',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ult_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ult',
            name='erosions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.erosions'),
        ),
        migrations.AddField(
            model_name='ult',
            name='hyperuricemia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.hyperuricemia'),
        ),
        migrations.AddField(
            model_name='ult',
            name='stones',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.uratekidneystones'),
        ),
        migrations.AddField(
            model_name='ult',
            name='tophi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.tophi'),
        ),
        migrations.AddField(
            model_name='ult',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
