# Generated by Django 3.1.7 on 2021-11-08 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_auto_20211108_1349'),
        ('ult', '0002_auto_20211108_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ult',
            name='uric_acid',
        ),
        migrations.AddField(
            model_name='ult',
            name='hyperuricemia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.hyperuricemia'),
        ),
    ]
