# Generated by Django 3.1.7 on 2021-04-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ult', '0002_auto_20210412_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ult',
            name='first_flare',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], help_text='Is this your first flare?', verbose_name='Is this your first flare?'),
        ),
    ]
