# Generated by Django 3.1.7 on 2021-10-04 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ult', '0002_ult_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ult',
            name='ckd',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, help_text="If you don't know, that's OK!", null=True, verbose_name='Do you have chronic kidney disease (CKD) stage III or greater?'),
        ),
        migrations.AlterField(
            model_name='ult',
            name='erosions',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, help_text="If you don't know, that's OK!", null=True, verbose_name='Do you have erosions on your x-rays?'),
        ),
        migrations.AlterField(
            model_name='ult',
            name='stones',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, help_text="If you don't know, that's OK!", null=True, verbose_name='Have you ever had kidney stones made of uric acid?'),
        ),
        migrations.AlterField(
            model_name='ult',
            name='tophi',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, help_text="If you don't know, that's OK!", null=True, verbose_name='Do you have tophi?'),
        ),
        migrations.AlterField(
            model_name='ult',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
