# Generated by Django 3.1.7 on 2022-02-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ult', '0002_ult_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ult',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
