# Generated by Django 3.1.7 on 2021-10-04 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_auto_20211004_1817'),
        ('ult', '0003_auto_20211004_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ult',
            name='ckd',
            field=models.OneToOneField(blank=True, help_text='Stage?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.ckd', verbose_name='Do you have CKD?'),
        ),
    ]
