# Generated by Django 3.1.7 on 2021-04-12 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ult', '0003_auto_20210412_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ult',
            name='ckd',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], help_text="If you don't know, that's OK!", verbose_name='Do you have chronic kidney disease (CKD)?'),
        ),
        migrations.AlterField(
            model_name='ult',
            name='erosions',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], help_text="If you don't know, that's OK!", verbose_name='Do you have erosions on your x-rays?'),
        ),
        migrations.AlterField(
            model_name='ult',
            name='first_flare',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], help_text='If so, disregard the rest of the questions.', verbose_name='Is this your first flare?'),
        ),
        migrations.AlterField(
            model_name='ult',
            name='freq_flares',
            field=models.CharField(choices=[('Under two', 'Under two'), ('Two or more', 'Two or more')], help_text='An estimate is fine!', max_length=30, verbose_name='Approximately how many flares do you have per year?'),
        ),
        migrations.AlterField(
            model_name='ult',
            name='num_flares',
            field=models.CharField(choices=[('one', 'One'), ('1-3', '1-3'), ('4-6', '4-6'), ('7 or more', '7 or more')], help_text='An estimate is fine!', max_length=30, verbose_name='Approximately how many gout flares have you had?'),
        ),
        migrations.AlterField(
            model_name='ult',
            name='stones',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], help_text="If you don't know, that's OK!", verbose_name='Have you ever had kidney stones made of uric acid?'),
        ),
        migrations.AlterField(
            model_name='ult',
            name='tophi',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], help_text="If you don't know, that's OK!", verbose_name='Do you have tophi?'),
        ),
        migrations.AlterField(
            model_name='ult',
            name='uric_acid',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], help_text="If you don't know, that's OK!", verbose_name='Is your uric acid over 9.0?'),
        ),
    ]
