# Generated by Django 3.1.7 on 2021-10-04 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_auto_20211004_1817'),
        ('ult', '0004_auto_20211004_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ult',
            name='ckd',
            field=models.OneToOneField(blank=True, default=False, help_text="If you don't know, that's OK!", null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.ckd', verbose_name='Do you have chronic kidney disease (CKD) stage III or greater?'),
        ),
        migrations.AlterField(
            model_name='ult',
            name='erosions',
            field=models.OneToOneField(blank=True, default=False, help_text="If you don't know, that's OK!", null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.erosions', verbose_name='Do you have erosions on your x-rays?'),
        ),
        migrations.AlterField(
            model_name='ult',
            name='stones',
            field=models.OneToOneField(blank=True, default=False, help_text="If you don't know, that's OK!", null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.uratekidneystones', verbose_name='Have you ever had kidney stones made of uric acid?'),
        ),
        migrations.AlterField(
            model_name='ult',
            name='tophi',
            field=models.OneToOneField(blank=True, default=False, help_text="If you don't know, that's OK!", null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.tophi', verbose_name='Do you have tophi?'),
        ),
    ]
