# Generated by Django 3.1.7 on 2021-04-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ult', '0005_auto_20210413_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ult',
            name='first_flare',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='If so, disregard the rest of the questions.', verbose_name='Is this your first flare?'),
        ),
    ]
