# Generated by Django 3.1.7 on 2021-08-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ult', '0009_auto_20210811_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ult',
            name='first_flare',
        ),
        migrations.AlterField(
            model_name='ult',
            name='ckd',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, help_text="If you don't know, that's OK!", null=True, verbose_name='Do you have chronic kidney disease (CKD) stage III or greater?'),
        ),
        migrations.AlterField(
            model_name='ult',
            name='erosions',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, help_text="If you don't know, that's OK!", null=True, verbose_name='Do you have erosions on your x-rays?'),
        ),
        migrations.AlterField(
            model_name='ult',
            name='freq_flares',
            field=models.CharField(blank=True, choices=[('one', 'One'), ('two or more', 'Two or more')], default='one', help_text='An estimate is fine!', max_length=30, null=True, verbose_name='Approximately how many flares do you have per year?'),
        ),
        migrations.AlterField(
            model_name='ult',
            name='num_flares',
            field=models.CharField(blank=True, choices=[('zero', 'Zero'), ('one', 'One'), ('1-3', '2-3'), ('4-6', '4-6'), ('7 or more', '7 or more')], default='one', help_text='If more than one, an estimate is fine!', max_length=30, null=True, verbose_name='How many gout flares have you had?'),
        ),
        migrations.AlterField(
            model_name='ult',
            name='stones',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, help_text="If you don't know, that's OK!", null=True, verbose_name='Have you ever had kidney stones made of uric acid?'),
        ),
        migrations.AlterField(
            model_name='ult',
            name='tophi',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, help_text="If you don't know, that's OK!", null=True, verbose_name='Do you have tophi?'),
        ),
        migrations.AlterField(
            model_name='ult',
            name='uric_acid',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, help_text="If you don't know, that's OK!", null=True, verbose_name='Is your uric acid over 9.0?'),
        ),
    ]
