# Generated by Django 3.1.7 on 2021-08-01 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vitals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('picture', models.ImageField(blank=True, default='default_image.jpg', help_text='Upload a picture for your profile', null=True, upload_to='')),
                ('bio', models.CharField(blank=True, help_text='500 character bio', max_length=500, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female'), ('non-binary', 'non-binary')], default='male', help_text='Enter gender', max_length=20, null=True)),
                ('race', models.CharField(blank=True, choices=[('white', 'white'), ('black', 'black'), ('asian', 'asian'), ('native american', 'native american'), ('hispanic', 'hispanic')], default='white', help_text='Enter race', max_length=40, null=True)),
                ('drinks_per_week', models.IntegerField(blank=True, null=True)),
                ('height', models.OneToOneField(blank=True, help_text='How tall are you in feet/inches?', null=True, on_delete=django.db.models.deletion.CASCADE, to='vitals.height')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('weight', models.OneToOneField(blank=True, help_text='How much do you weight in pounds?', null=True, on_delete=django.db.models.deletion.CASCADE, to='vitals.weight')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
