# Generated by Django 3.1.7 on 2021-11-11 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vitals', '0001_initial'),
        ('history', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('alcohol', models.OneToOneField(blank=True, help_text='How many drinks do you have per week?', null=True, on_delete=django.db.models.deletion.CASCADE, to='history.alcohol')),
                ('fructose', models.OneToOneField(blank=True, help_text='Do you eat a lot of fructose such as the sugar found in soda/pop, processed candies, or juices?', null=True, on_delete=django.db.models.deletion.CASCADE, to='history.fructose')),
                ('shellfish', models.OneToOneField(blank=True, help_text='Do you eat a lot of shellfish?', null=True, on_delete=django.db.models.deletion.CASCADE, to='history.shellfish')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('picture', models.ImageField(blank=True, default='default_thumbnail.png', help_text='Upload a picture for your profile', null=True, upload_to='')),
                ('bio', models.CharField(blank=True, help_text='500 character bio', max_length=500, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female'), ('non-binary', 'non-binary')], default='male', help_text='Enter gender', max_length=20, null=True)),
                ('race', models.CharField(blank=True, choices=[('white', 'white'), ('black', 'black'), ('asian', 'asian'), ('native american', 'native american'), ('hispanic', 'hispanic')], default='white', help_text='Enter race', max_length=40, null=True)),
                ('height', models.OneToOneField(blank=True, help_text='How tall are you in feet/inches?', null=True, on_delete=django.db.models.deletion.CASCADE, to='vitals.height')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('weight', models.OneToOneField(blank=True, help_text='How much do you weight in pounds?', null=True, on_delete=django.db.models.deletion.CASCADE, to='vitals.weight')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('CHF', models.OneToOneField(blank=True, help_text='Do you have congestive heart failure (CHF)?', null=True, on_delete=django.db.models.deletion.CASCADE, to='history.chf')),
                ('CKD', models.OneToOneField(blank=True, help_text='Do you have chronic kidney disease (CKD)?', null=True, on_delete=django.db.models.deletion.CASCADE, to='history.ckd', verbose_name='CKD')),
                ('IBD', models.OneToOneField(blank=True, help_text="Do you have IBD (inflammatory bowel disease=Crohn's disease or ulcerative colitis)?", null=True, on_delete=django.db.models.deletion.CASCADE, to='history.ibd')),
                ('XOI_interactions', models.OneToOneField(blank=True, help_text='Are you on 6-mercaptopurine or azathioprine?', null=True, on_delete=django.db.models.deletion.CASCADE, to='history.xoiinteractions')),
                ('allopurinol_hypersensitivity', models.OneToOneField(blank=True, help_text='Have you ever had an adverse reaction to allopurinol?', null=True, on_delete=django.db.models.deletion.CASCADE, to='history.allopurinolhypersensitivity', verbose_name='Allopurinol Hypersensitivity')),
                ('anticoagulation', models.OneToOneField(blank=True, help_text='Are you on anticoagulation?', null=True, on_delete=django.db.models.deletion.CASCADE, to='history.anticoagulation')),
                ('bleed', models.OneToOneField(blank=True, help_text='Have you had a major bleeding event?', null=True, on_delete=django.db.models.deletion.CASCADE, to='history.bleed')),
                ('colchicine_interactions', models.OneToOneField(blank=True, help_text='Are you on a medication that interacts with colchicine, such as simvastatin, clarithromycin, or diltiazem?', null=True, on_delete=django.db.models.deletion.CASCADE, to='history.colchicineinteractions')),
                ('diabetes', models.OneToOneField(blank=True, help_text='Do you have diabetes?', null=True, on_delete=django.db.models.deletion.CASCADE, to='history.diabetes')),
                ('erosions', models.OneToOneField(blank=True, help_text='Do you have gouty erosions?', null=True, on_delete=django.db.models.deletion.CASCADE, to='history.erosions')),
                ('febuxostat_hypersensitivity', models.OneToOneField(blank=True, help_text='Have you ever had an adverse reaction to febuxostat?', null=True, on_delete=django.db.models.deletion.CASCADE, to='history.febuxostathypersensitivity', verbose_name='Febuxostat Hypersensitivity')),
                ('heartattack', models.OneToOneField(blank=True, help_text='Have you had a heart attack?', null=True, on_delete=django.db.models.deletion.CASCADE, to='history.heartattack')),
                ('hypertension', models.OneToOneField(blank=True, help_text='Do you have high blood pressure (hypertension)?', null=True, on_delete=django.db.models.deletion.CASCADE, to='history.hypertension')),
                ('hyperuricemia', models.OneToOneField(blank=True, help_text='Do you have blood uric acid levels greater than 9.0 mg/dL?', null=True, on_delete=django.db.models.deletion.CASCADE, to='history.hyperuricemia')),
                ('organ_transplant', models.OneToOneField(blank=True, help_text='Have you had an organ transplant?', null=True, on_delete=django.db.models.deletion.CASCADE, to='history.organtransplant')),
                ('osteoporosis', models.OneToOneField(blank=True, help_text='Do you have osteoporosis?', null=True, on_delete=django.db.models.deletion.CASCADE, to='history.osteoporosis')),
                ('stroke', models.OneToOneField(blank=True, help_text='Have you had a stroke?', null=True, on_delete=django.db.models.deletion.CASCADE, to='history.stroke')),
                ('tophi', models.OneToOneField(blank=True, help_text='Do you have gouty tophi?', null=True, on_delete=django.db.models.deletion.CASCADE, to='history.tophi')),
                ('urate_kidney_stones', models.OneToOneField(blank=True, help_text='Have you had urate kidney stones?', null=True, on_delete=django.db.models.deletion.CASCADE, to='history.uratekidneystones')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FamilyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('gout', models.OneToOneField(blank=True, help_text='Do you have a family history of gout?', null=True, on_delete=django.db.models.deletion.CASCADE, to='history.gout')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
