# Generated by Django 3.1.7 on 2021-12-02 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0006_auto_20211202_1017'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalprofile',
            name='PVD',
            field=models.OneToOneField(blank=True, help_text="Do you have <a href='https://en.wikipedia.org/wiki/Peripheral_artery_disease' target='_blank'>peripheral vascular disease</a>?", null=True, on_delete=django.db.models.deletion.CASCADE, to='history.pvd'),
        ),
    ]
