# Generated by Django 3.1.7 on 2021-04-19 16:44

from django.db import migrations, models
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientprofile',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='age',
            field=models.IntegerField(default=35, help_text='Enter age', verbose_name=range(0, -149)),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='drinks_per_week',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('non-binary', 'non-binary')], default='male', help_text='Enter gender', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='height',
            field=models.IntegerField(default='70', help_text='How tall are you in feet/inches?', verbose_name=range(0, -100)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='race',
            field=models.CharField(choices=[('white', 'white'), ('black', 'black'), ('asian', 'asian'), ('native american', 'native american'), ('hispanic', 'hispanic')], default='white', help_text='Enter race', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='weight',
            field=models.IntegerField(default='170', help_text='How much do you weight in pounds?', verbose_name=range(0, -950)),
            preserve_default=False,
        ),
    ]
