# Generated by Django 3.1.7 on 2021-08-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='picture',
            field=models.ImageField(blank=True, default='default_thumbnail.png', help_text='Upload a picture for your profile', null=True, upload_to=''),
        ),
    ]
