# Generated by Django 3.1.7 on 2021-10-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contraindicationsprofile',
            name='contraindication',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], help_text='Have you ever had a stroke, heart attack, or major bleeding event?', null=True),
        ),
    ]
