# Generated by Django 3.1.7 on 2021-11-05 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalprofile',
            old_name='colchicine_interaction',
            new_name='colchicine_interactions',
        ),
    ]
