# Generated by Django 3.1.7 on 2022-01-12 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vitals', '0001_initial'),
        ('history', '0002_auto_20220112_1549'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='height',
            field=models.OneToOneField(blank=True, help_text='How tall are you in feet/inches?', null=True, on_delete=django.db.models.deletion.CASCADE, to='vitals.height'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='weight',
            field=models.OneToOneField(blank=True, help_text='How much do you weight in pounds?', null=True, on_delete=django.db.models.deletion.CASCADE, to='vitals.weight'),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='CHF',
            field=models.OneToOneField(blank=True, help_text='Do you have congestive heart failure (CHF)?', null=True, on_delete=django.db.models.deletion.CASCADE, to='history.chf'),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='CKD',
            field=models.OneToOneField(blank=True, help_text='Do you have chronic kidney disease (CKD)?', null=True, on_delete=django.db.models.deletion.CASCADE, to='history.ckd', verbose_name='CKD'),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='IBD',
            field=models.OneToOneField(blank=True, help_text="Do you have IBD (inflammatory bowel disease=Crohn's disease or ulcerative colitis)?", null=True, on_delete=django.db.models.deletion.CASCADE, to='history.ibd'),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='PVD',
            field=models.OneToOneField(blank=True, help_text="Do you have <a href='https://en.wikipedia.org/wiki/Peripheral_artery_disease' target='_blank'>peripheral vascular disease</a>?", null=True, on_delete=django.db.models.deletion.CASCADE, to='history.pvd'),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='XOI_interactions',
            field=models.OneToOneField(blank=True, help_text='Are you on 6-mercaptopurine or azathioprine?', null=True, on_delete=django.db.models.deletion.CASCADE, to='history.xoiinteractions'),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='allopurinol_hypersensitivity',
            field=models.OneToOneField(blank=True, help_text='Have you ever had an adverse reaction to allopurinol?', null=True, on_delete=django.db.models.deletion.CASCADE, to='history.allopurinolhypersensitivity', verbose_name='Allopurinol Hypersensitivity'),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='angina',
            field=models.OneToOneField(blank=True, help_text="Do you get <a href='https://www.heart.org/en/health-topics/heart-attack/angina-chest-pain' target='_blank'>angina</a>?", null=True, on_delete=django.db.models.deletion.CASCADE, to='history.angina', verbose_name='Angina (Cardiac Chest Pain)'),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='anticoagulation',
            field=models.OneToOneField(blank=True, help_text='Are you on anticoagulation?', null=True, on_delete=django.db.models.deletion.CASCADE, to='history.anticoagulation'),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='bleed',
            field=models.OneToOneField(blank=True, help_text='Have you had a major bleeding event?', null=True, on_delete=django.db.models.deletion.CASCADE, to='history.bleed'),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='colchicine_interactions',
            field=models.OneToOneField(blank=True, help_text='Are you on a medication that interacts with colchicine, such as simvastatin, clarithromycin, or diltiazem?', null=True, on_delete=django.db.models.deletion.CASCADE, to='history.colchicineinteractions'),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='diabetes',
            field=models.OneToOneField(blank=True, help_text='Do you have diabetes?', null=True, on_delete=django.db.models.deletion.CASCADE, to='history.diabetes'),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='erosions',
            field=models.OneToOneField(blank=True, help_text='Do you have gouty erosions?', null=True, on_delete=django.db.models.deletion.CASCADE, to='history.erosions'),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='febuxostat_hypersensitivity',
            field=models.OneToOneField(blank=True, help_text='Have you ever had an adverse reaction to febuxostat?', null=True, on_delete=django.db.models.deletion.CASCADE, to='history.febuxostathypersensitivity', verbose_name='Febuxostat Hypersensitivity'),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='heartattack',
            field=models.OneToOneField(blank=True, help_text='Have you had a heart attack?', null=True, on_delete=django.db.models.deletion.CASCADE, to='history.heartattack'),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='hypertension',
            field=models.OneToOneField(blank=True, help_text='Do you have high blood pressure (hypertension)?', null=True, on_delete=django.db.models.deletion.CASCADE, to='history.hypertension'),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='hyperuricemia',
            field=models.OneToOneField(blank=True, help_text='Do you have blood uric acid levels greater than 9.0 mg/dL?', null=True, on_delete=django.db.models.deletion.CASCADE, to='history.hyperuricemia'),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='organ_transplant',
            field=models.OneToOneField(blank=True, help_text='Have you had an organ transplant?', null=True, on_delete=django.db.models.deletion.CASCADE, to='history.organtransplant'),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='osteoporosis',
            field=models.OneToOneField(blank=True, help_text='Do you have osteoporosis?', null=True, on_delete=django.db.models.deletion.CASCADE, to='history.osteoporosis'),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='stroke',
            field=models.OneToOneField(blank=True, help_text='Have you had a stroke?', null=True, on_delete=django.db.models.deletion.CASCADE, to='history.stroke'),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='tophi',
            field=models.OneToOneField(blank=True, help_text='Do you have gouty tophi?', null=True, on_delete=django.db.models.deletion.CASCADE, to='history.tophi'),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='urate_kidney_stones',
            field=models.OneToOneField(blank=True, help_text='Have you had urate kidney stones?', null=True, on_delete=django.db.models.deletion.CASCADE, to='history.uratekidneystones'),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='familyprofile',
            name='gout',
            field=models.OneToOneField(blank=True, help_text='Do you have a family history of gout?', null=True, on_delete=django.db.models.deletion.CASCADE, to='history.gout'),
        ),
        migrations.AddField(
            model_name='familyprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
