# Generated by Django 3.1.7 on 2022-03-26 14:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20220313_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpatientprofile',
            name='creatinine_emergency',
            field=models.DecimalField(decimal_places=2, default=Decimal('5'), help_text='Percentage for trivial creatinine abnormality calculation', max_digits=3),
        ),
        migrations.AddField(
            model_name='historicalpatientprofile',
            name='creatinine_nonurgent',
            field=models.DecimalField(decimal_places=2, default=Decimal('2'), help_text='Percentage for trivial creatinine abnormality calculation', max_digits=3),
        ),
        migrations.AddField(
            model_name='historicalpatientprofile',
            name='creatinine_trivial',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Percentage for trivial creatinine abnormality calculation', max_digits=3),
        ),
        migrations.AddField(
            model_name='historicalpatientprofile',
            name='creatinine_urgent',
            field=models.DecimalField(decimal_places=2, default=Decimal('3'), help_text='Percentage for trivial creatinine abnormality calculation', max_digits=3),
        ),
        migrations.AddField(
            model_name='historicalpatientprofile',
            name='hemoglobin_high_emergency',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Percentage for trivial high hemoglobin abnormality calculation', max_digits=3),
        ),
        migrations.AddField(
            model_name='historicalpatientprofile',
            name='hemoglobin_high_nonurgent',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Percentage for trivial high hemoglobin abnormality calculation', max_digits=3),
        ),
        migrations.AddField(
            model_name='historicalpatientprofile',
            name='hemoglobin_high_trivial',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Percentage for trivial high hemoglobin abnormality calculation', max_digits=3),
        ),
        migrations.AddField(
            model_name='historicalpatientprofile',
            name='hemoglobin_high_urgent',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Percentage for trivial high hemoglobin abnormality calculation', max_digits=3),
        ),
        migrations.AddField(
            model_name='historicalpatientprofile',
            name='hemoglobin_low_emergency',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Percentage for trivial low hemoglobin abnormality calculation', max_digits=3),
        ),
        migrations.AddField(
            model_name='historicalpatientprofile',
            name='hemoglobin_low_nonurgent',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Percentage for trivial low hemoglobin abnormality calculation', max_digits=3),
        ),
        migrations.AddField(
            model_name='historicalpatientprofile',
            name='hemoglobin_low_trivial',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Percentage for trivial low hemoglobin abnormality calculation', max_digits=3),
        ),
        migrations.AddField(
            model_name='historicalpatientprofile',
            name='hemoglobin_low_urgent',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Percentage for trivial low hemoglobin abnormality calculation', max_digits=3),
        ),
        migrations.AddField(
            model_name='historicalpatientprofile',
            name='lft_emergency',
            field=models.DecimalField(decimal_places=2, default=Decimal('5'), help_text='Percentage for emergency LFT abnormality calculation', max_digits=3),
        ),
        migrations.AddField(
            model_name='historicalpatientprofile',
            name='lft_nonurgent',
            field=models.DecimalField(decimal_places=2, default=Decimal('2'), help_text='Percentage for nonurgent LFT abnormality calculation', max_digits=3),
        ),
        migrations.AddField(
            model_name='historicalpatientprofile',
            name='lft_trivial',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Percentage for trivial LFT abnormality calculation', max_digits=3),
        ),
        migrations.AddField(
            model_name='historicalpatientprofile',
            name='lft_urgent',
            field=models.DecimalField(decimal_places=2, default=Decimal('3'), help_text='Percentage for urgent LFT abnormality calculation', max_digits=3),
        ),
        migrations.AddField(
            model_name='historicalpatientprofile',
            name='platelet_high_emergency',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Percentage for trivial high platelet abnormality calculation', max_digits=3),
        ),
        migrations.AddField(
            model_name='historicalpatientprofile',
            name='platelet_high_nonurgent',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Percentage for trivial high platelet abnormality calculation', max_digits=3),
        ),
        migrations.AddField(
            model_name='historicalpatientprofile',
            name='platelet_high_trivial',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Percentage for trivial high platelet abnormality calculation', max_digits=3),
        ),
        migrations.AddField(
            model_name='historicalpatientprofile',
            name='platelet_high_urgent',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Percentage for trivial high platelet abnormality calculation', max_digits=3),
        ),
        migrations.AddField(
            model_name='historicalpatientprofile',
            name='platelet_low_emergency',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Percentage for trivial low platelet abnormality calculation', max_digits=3),
        ),
        migrations.AddField(
            model_name='historicalpatientprofile',
            name='platelet_low_nonurgent',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Percentage for trivial low platelet abnormality calculation', max_digits=3),
        ),
        migrations.AddField(
            model_name='historicalpatientprofile',
            name='platelet_low_trivial',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Percentage for trivial low platelet abnormality calculation', max_digits=3),
        ),
        migrations.AddField(
            model_name='historicalpatientprofile',
            name='platelet_low_urgent',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Percentage for trivial low platelet abnormality calculation', max_digits=3),
        ),
        migrations.AddField(
            model_name='historicalpatientprofile',
            name='wbc_high_emergency',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Percentage for trivial high WBC abnormality calculation', max_digits=3),
        ),
        migrations.AddField(
            model_name='historicalpatientprofile',
            name='wbc_high_nonurgent',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Percentage for trivial high WBC abnormality calculation', max_digits=3),
        ),
        migrations.AddField(
            model_name='historicalpatientprofile',
            name='wbc_high_trivial',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Percentage for trivial high WBC abnormality calculation', max_digits=3),
        ),
        migrations.AddField(
            model_name='historicalpatientprofile',
            name='wbc_high_urgent',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Percentage for trivial high WBC abnormality calculation', max_digits=3),
        ),
        migrations.AddField(
            model_name='historicalpatientprofile',
            name='wbc_low_emergency',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Percentage for trivial low WBC abnormality calculation', max_digits=3),
        ),
        migrations.AddField(
            model_name='historicalpatientprofile',
            name='wbc_low_nonurgent',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Percentage for trivial low WBC abnormality calculation', max_digits=3),
        ),
        migrations.AddField(
            model_name='historicalpatientprofile',
            name='wbc_low_trivial',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Percentage for trivial low WBC abnormality calculation', max_digits=3),
        ),
        migrations.AddField(
            model_name='historicalpatientprofile',
            name='wbc_low_urgent',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Percentage for trivial low WBC abnormality calculation', max_digits=3),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='creatinine_emergency',
            field=models.DecimalField(decimal_places=2, default=Decimal('5'), help_text='Percentage for trivial creatinine abnormality calculation', max_digits=3),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='creatinine_nonurgent',
            field=models.DecimalField(decimal_places=2, default=Decimal('2'), help_text='Percentage for trivial creatinine abnormality calculation', max_digits=3),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='creatinine_trivial',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Percentage for trivial creatinine abnormality calculation', max_digits=3),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='creatinine_urgent',
            field=models.DecimalField(decimal_places=2, default=Decimal('3'), help_text='Percentage for trivial creatinine abnormality calculation', max_digits=3),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='hemoglobin_high_emergency',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Percentage for trivial high hemoglobin abnormality calculation', max_digits=3),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='hemoglobin_high_nonurgent',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Percentage for trivial high hemoglobin abnormality calculation', max_digits=3),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='hemoglobin_high_trivial',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Percentage for trivial high hemoglobin abnormality calculation', max_digits=3),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='hemoglobin_high_urgent',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Percentage for trivial high hemoglobin abnormality calculation', max_digits=3),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='hemoglobin_low_emergency',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Percentage for trivial low hemoglobin abnormality calculation', max_digits=3),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='hemoglobin_low_nonurgent',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Percentage for trivial low hemoglobin abnormality calculation', max_digits=3),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='hemoglobin_low_trivial',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Percentage for trivial low hemoglobin abnormality calculation', max_digits=3),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='hemoglobin_low_urgent',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Percentage for trivial low hemoglobin abnormality calculation', max_digits=3),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='lft_emergency',
            field=models.DecimalField(decimal_places=2, default=Decimal('5'), help_text='Percentage for emergency LFT abnormality calculation', max_digits=3),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='lft_nonurgent',
            field=models.DecimalField(decimal_places=2, default=Decimal('2'), help_text='Percentage for nonurgent LFT abnormality calculation', max_digits=3),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='lft_trivial',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Percentage for trivial LFT abnormality calculation', max_digits=3),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='lft_urgent',
            field=models.DecimalField(decimal_places=2, default=Decimal('3'), help_text='Percentage for urgent LFT abnormality calculation', max_digits=3),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='platelet_high_emergency',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Percentage for trivial high platelet abnormality calculation', max_digits=3),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='platelet_high_nonurgent',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Percentage for trivial high platelet abnormality calculation', max_digits=3),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='platelet_high_trivial',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Percentage for trivial high platelet abnormality calculation', max_digits=3),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='platelet_high_urgent',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Percentage for trivial high platelet abnormality calculation', max_digits=3),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='platelet_low_emergency',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Percentage for trivial low platelet abnormality calculation', max_digits=3),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='platelet_low_nonurgent',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Percentage for trivial low platelet abnormality calculation', max_digits=3),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='platelet_low_trivial',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Percentage for trivial low platelet abnormality calculation', max_digits=3),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='platelet_low_urgent',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Percentage for trivial low platelet abnormality calculation', max_digits=3),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='wbc_high_emergency',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Percentage for trivial high WBC abnormality calculation', max_digits=3),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='wbc_high_nonurgent',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Percentage for trivial high WBC abnormality calculation', max_digits=3),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='wbc_high_trivial',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Percentage for trivial high WBC abnormality calculation', max_digits=3),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='wbc_high_urgent',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Percentage for trivial high WBC abnormality calculation', max_digits=3),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='wbc_low_emergency',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Percentage for trivial low WBC abnormality calculation', max_digits=3),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='wbc_low_nonurgent',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Percentage for trivial low WBC abnormality calculation', max_digits=3),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='wbc_low_trivial',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Percentage for trivial low WBC abnormality calculation', max_digits=3),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='wbc_low_urgent',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Percentage for trivial low WBC abnormality calculation', max_digits=3),
        ),
    ]
