# Generated by Django 3.1.7 on 2021-12-10 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0007_angina'),
        ('profiles', '0002_medicalprofile_pvd'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalprofile',
            name='angina',
            field=models.OneToOneField(blank=True, help_text="Do you get <a href='https://www.heart.org/en/health-topics/heart-attack/angina-chest-pain' target='_blank'>angina</a>?", null=True, on_delete=django.db.models.deletion.CASCADE, to='history.angina', verbose_name='Angina (Cardiac Chest Pain)'),
        ),
    ]
