# Generated by Django 3.1.7 on 2021-10-25 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0006_hyperuricemia'),
        ('profiles', '0002_auto_20211024_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalprofile',
            name='erosions',
            field=models.OneToOneField(blank=True, help_text='Do you have gouty erosions?', null=True, on_delete=django.db.models.deletion.CASCADE, to='history.erosions'),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='hyperuricemia',
            field=models.OneToOneField(blank=True, help_text='Do you have blood uric acid levels greater than 9.0 mg/dL?', null=True, on_delete=django.db.models.deletion.CASCADE, to='history.hyperuricemia'),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='tophi',
            field=models.OneToOneField(blank=True, help_text='Do you have gouty tophi?', null=True, on_delete=django.db.models.deletion.CASCADE, to='history.tophi'),
        ),
    ]
