# Generated by Django 3.1.7 on 2021-09-15 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('history', '0002_colchicineinteractions_organtransplant_xoiinteractions'),
        ('profiles', '0002_auto_20210806_1609'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientprofile',
            options={},
        ),
        migrations.CreateModel(
            name='MedicalProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('CHF', models.OneToOneField(blank=True, help_text='Do you have congestive heart failure (CHF)?', null=True, on_delete=django.db.models.deletion.CASCADE, to='history.chf')),
                ('CKD', models.OneToOneField(blank=True, help_text='Do you have chronic kidney disease (CKD)?', null=True, on_delete=django.db.models.deletion.CASCADE, to='history.ckd')),
                ('diabetes', models.OneToOneField(blank=True, help_text='Do you have diabetes?', null=True, on_delete=django.db.models.deletion.CASCADE, to='history.diabetes')),
                ('hypertension', models.OneToOneField(blank=True, help_text='Do you have high blood pressure (hypertension)?', null=True, on_delete=django.db.models.deletion.CASCADE, to='history.hypertension')),
                ('organ_transplant', models.OneToOneField(blank=True, help_text='Have you had an organ transplant?', null=True, on_delete=django.db.models.deletion.CASCADE, to='history.organtransplant')),
                ('urate_kidney_stones', models.OneToOneField(blank=True, help_text='Have you had urate kidney stones?', null=True, on_delete=django.db.models.deletion.CASCADE, to='history.uratekidneystones')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
