# Generated by Django 3.1.7 on 2022-01-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20220129_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpatientprofile',
            name='patient_id',
            field=models.IntegerField(blank=True, help_text='Does the Patient have an ID for you to reference?', null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='patient_id',
            field=models.IntegerField(blank=True, help_text='Does the Patient have an ID for you to reference?', null=True),
        ),
    ]
