# Generated by Django 3.1.7 on 2021-09-15 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_auto_20210915_2125'),
        ('profiles', '0003_auto_20210915_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalprofile',
            name='CKD',
            field=models.OneToOneField(blank=True, help_text='Do you have chronic kidney disease (CKD)?', null=True, on_delete=django.db.models.deletion.CASCADE, to='history.ckd', verbose_name='CKD'),
        ),
    ]
