# Generated by Django 3.1.7 on 2022-02-01 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20220130_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproviderprofile',
            name='delinquent_lab_interval',
            field=models.DurationField(default=datetime.timedelta(days=21), help_text='How frequently do you recheck urgent labs?', verbose_name='Urgent Lab Check Interval'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='delinquent_lab_interval',
            field=models.DurationField(default=datetime.timedelta(days=21), help_text='How frequently do you recheck urgent labs?', verbose_name='Urgent Lab Check Interval'),
        ),
    ]
