# Generated by Django 3.1.7 on 2022-03-30 16:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20220326_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpatientprofile',
            name='platelet_high_emergency',
            field=models.DecimalField(decimal_places=2, default=Decimal('2'), help_text='Percentage for trivial high platelet abnormality calculation', max_digits=3),
        ),
        migrations.AlterField(
            model_name='historicalpatientprofile',
            name='platelet_high_nonurgent',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.5'), help_text='Percentage for trivial high platelet abnormality calculation', max_digits=3),
        ),
        migrations.AlterField(
            model_name='historicalpatientprofile',
            name='platelet_high_urgent',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.75'), help_text='Percentage for trivial high platelet abnormality calculation', max_digits=3),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='platelet_high_emergency',
            field=models.DecimalField(decimal_places=2, default=Decimal('2'), help_text='Percentage for trivial high platelet abnormality calculation', max_digits=3),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='platelet_high_nonurgent',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.5'), help_text='Percentage for trivial high platelet abnormality calculation', max_digits=3),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='platelet_high_urgent',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.75'), help_text='Percentage for trivial high platelet abnormality calculation', max_digits=3),
        ),
    ]
