# Generated by Django 3.1.7 on 2022-03-30 19:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20220330_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpatientprofile',
            name='platelet_low_emergency',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.25'), help_text='Percentage for trivial low platelet abnormality calculation', max_digits=3),
        ),
        migrations.AlterField(
            model_name='historicalpatientprofile',
            name='platelet_low_nonurgent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.75'), help_text='Percentage for trivial low platelet abnormality calculation', max_digits=3),
        ),
        migrations.AlterField(
            model_name='historicalpatientprofile',
            name='platelet_low_urgent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.5'), help_text='Percentage for trivial low platelet abnormality calculation', max_digits=3),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='platelet_low_emergency',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.25'), help_text='Percentage for trivial low platelet abnormality calculation', max_digits=3),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='platelet_low_nonurgent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.75'), help_text='Percentage for trivial low platelet abnormality calculation', max_digits=3),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='platelet_low_urgent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.5'), help_text='Percentage for trivial low platelet abnormality calculation', max_digits=3),
        ),
    ]
