# Generated by Django 3.1.7 on 2022-02-02 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20220201_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpatientprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='bio',
        ),
    ]
