# Generated by Django 3.1.7 on 2021-04-19 19:37

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20210419_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default='spiew', editable=False, populate_from='user', unique=True, verbose_name='User Profile'),
            preserve_default=False,
        ),
    ]
