# Generated by Django 3.1.7 on 2021-09-16 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20210915_2125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalprofile',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='patientprofile',
            options={'get_latest_by': 'modified'},
        ),
    ]
