# Generated by Django 3.1.7 on 2021-09-19 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0005_auto_20210919_1951'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0005_auto_20210916_0133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='drinks_per_week',
        ),
        migrations.CreateModel(
            name='SocialProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('alcohol', models.OneToOneField(blank=True, help_text='How many drinks do you have per week?', null=True, on_delete=django.db.models.deletion.CASCADE, to='history.alcohol')),
                ('fructose', models.OneToOneField(blank=True, help_text='Do you eat a lot of fructose such as the sugar found in soda/pop, processed candies, or juices?', null=True, on_delete=django.db.models.deletion.CASCADE, to='history.fructose')),
                ('shellfish', models.OneToOneField(blank=True, help_text='Do you eat a lot of shellfish?', null=True, on_delete=django.db.models.deletion.CASCADE, to='history.shellfish')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContraindicationsProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('value', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], help_text='Have you ever had a heart stroke, heart attack, or major bleeding event?', null=True)),
                ('bleed', models.OneToOneField(blank=True, help_text='Have you had a major bleeding event?', null=True, on_delete=django.db.models.deletion.CASCADE, to='history.bleed')),
                ('heartattack', models.OneToOneField(blank=True, help_text='Have you had a heart attack?', null=True, on_delete=django.db.models.deletion.CASCADE, to='history.heartattack')),
                ('stroke', models.OneToOneField(blank=True, help_text='Have you had a stroke?', null=True, on_delete=django.db.models.deletion.CASCADE, to='history.stroke')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
