# Generated by Django 3.1.7 on 2021-04-20 18:13

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20210420_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='user__username', unique=True, verbose_name='User Profile'),
        ),
    ]
