# Generated by Django 3.1.7 on 2021-09-19 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20210919_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contraindicationsprofile',
            old_name='value',
            new_name='contraindication',
        ),
    ]
