# Generated by Django 3.1.7 on 2021-04-21 15:40

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20210420_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='get_id_num', unique_with=('user',), verbose_name='User Profile'),
        ),
    ]
