# Generated by Django 3.1.7 on 2021-04-27 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20210421_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female'), ('non-binary', 'non-binary')], default='male', help_text='Enter gender', max_length=20),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='race',
            field=models.CharField(blank=True, choices=[('white', 'white'), ('black', 'black'), ('asian', 'asian'), ('native american', 'native american'), ('hispanic', 'hispanic')], default='white', help_text='Enter race', max_length=40),
        ),
    ]
