# Generated by Django 3.1.7 on 2021-06-07 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20210427_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='age',
        ),
    ]
