# Generated by Django 3.1.7 on 2021-07-23 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_remove_patientprofile_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='slug',
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='picture',
            field=models.ImageField(blank=True, default='default_image.jpg', help_text='Upload a picture for your profile', null=True, upload_to=''),
        ),
    ]
