# Generated by Django 3.1.7 on 2021-07-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20210723_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='bio',
            field=models.CharField(blank=True, help_text='500 character bio', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female'), ('non-binary', 'non-binary')], default='male', help_text='Enter gender', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='race',
            field=models.CharField(blank=True, choices=[('white', 'white'), ('black', 'black'), ('asian', 'asian'), ('native american', 'native american'), ('hispanic', 'hispanic')], default='white', help_text='Enter race', max_length=40, null=True),
        ),
    ]
