# Generated by Django 3.1.7 on 2021-10-04 12:49

from django.db import migrations, models
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ALT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('date_drawn', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='What day was this lab drawn?', null=True)),
                ('value', models.IntegerField(help_text='ALT / SGPT')),
                ('units', models.CharField(blank=True, choices=[('mg/dL (milligrams per deciliter)', 'mg/dL (milligrams per deciliter)'), ('g/dL (grams per decliter)', 'g/dL (grams per decliter)'), ('cells/mm^3 (cells per cubmic millimeter)', 'cells/mm^3 (cells per cubmic millimeter)'), ('PLTS/μL (platelets per microliter)', 'PLTS/μL (platelets per microliter)'), ('U/L (units per liter)', 'U/L (units per liter)')], default='U/L (units per liter)', max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('date_drawn', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='What day was this lab drawn?', null=True)),
                ('value', models.IntegerField(help_text='AST / SGOT')),
                ('units', models.CharField(blank=True, choices=[('mg/dL (milligrams per deciliter)', 'mg/dL (milligrams per deciliter)'), ('g/dL (grams per decliter)', 'g/dL (grams per decliter)'), ('cells/mm^3 (cells per cubmic millimeter)', 'cells/mm^3 (cells per cubmic millimeter)'), ('PLTS/μL (platelets per microliter)', 'PLTS/μL (platelets per microliter)'), ('U/L (units per liter)', 'U/L (units per liter)')], default='U/L (units per liter)', max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Creatinine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('date_drawn', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='What day was this lab drawn?', null=True)),
                ('value', models.DecimalField(decimal_places=2, help_text='creatinine', max_digits=4)),
                ('units', models.CharField(blank=True, choices=[('mg/dL (milligrams per deciliter)', 'mg/dL (milligrams per deciliter)'), ('g/dL (grams per decliter)', 'g/dL (grams per decliter)'), ('cells/mm^3 (cells per cubmic millimeter)', 'cells/mm^3 (cells per cubmic millimeter)'), ('PLTS/μL (platelets per microliter)', 'PLTS/μL (platelets per microliter)'), ('U/L (units per liter)', 'U/L (units per liter)')], default='mg/dL (milligrams per deciliter)', max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hemoglobin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('date_drawn', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='What day was this lab drawn?', null=True)),
                ('value', models.DecimalField(decimal_places=1, help_text='HGB', max_digits=3)),
                ('units', models.CharField(blank=True, choices=[('mg/dL (milligrams per deciliter)', 'mg/dL (milligrams per deciliter)'), ('g/dL (grams per decliter)', 'g/dL (grams per decliter)'), ('cells/mm^3 (cells per cubmic millimeter)', 'cells/mm^3 (cells per cubmic millimeter)'), ('PLTS/μL (platelets per microliter)', 'PLTS/μL (platelets per microliter)'), ('U/L (units per liter)', 'U/L (units per liter)')], default='g/dL (grams per decliter)', max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Platelet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('date_drawn', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='What day was this lab drawn?', null=True)),
                ('value', models.IntegerField(help_text='PLT / platelets')),
                ('units', models.CharField(blank=True, choices=[('mg/dL (milligrams per deciliter)', 'mg/dL (milligrams per deciliter)'), ('g/dL (grams per decliter)', 'g/dL (grams per decliter)'), ('cells/mm^3 (cells per cubmic millimeter)', 'cells/mm^3 (cells per cubmic millimeter)'), ('PLTS/μL (platelets per microliter)', 'PLTS/μL (platelets per microliter)'), ('U/L (units per liter)', 'U/L (units per liter)')], default='PLTS/μL (platelets per microliter)', max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Urate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('date_drawn', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='What day was this lab drawn?', null=True)),
                ('value', models.DecimalField(decimal_places=1, help_text='Enter the uric acid', max_digits=3)),
                ('units', models.CharField(blank=True, choices=[('mg/dL (milligrams per deciliter)', 'mg/dL (milligrams per deciliter)'), ('g/dL (grams per decliter)', 'g/dL (grams per decliter)'), ('cells/mm^3 (cells per cubmic millimeter)', 'cells/mm^3 (cells per cubmic millimeter)'), ('PLTS/μL (platelets per microliter)', 'PLTS/μL (platelets per microliter)'), ('U/L (units per liter)', 'U/L (units per liter)')], default='mg/dL (milligrams per deciliter)', max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WBC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('date_drawn', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='What day was this lab drawn?', null=True)),
                ('value', models.DecimalField(decimal_places=1, help_text='WBC', max_digits=3)),
                ('units', models.CharField(blank=True, choices=[('mg/dL (milligrams per deciliter)', 'mg/dL (milligrams per deciliter)'), ('g/dL (grams per decliter)', 'g/dL (grams per decliter)'), ('cells/mm^3 (cells per cubmic millimeter)', 'cells/mm^3 (cells per cubmic millimeter)'), ('PLTS/μL (platelets per microliter)', 'PLTS/μL (platelets per microliter)'), ('U/L (units per liter)', 'U/L (units per liter)')], default='cells/mm^3 (cells per cubmic millimeter)', max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
