# Generated by Django 3.1.7 on 2022-01-12 15:49

import datetime
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ALT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('date_drawn', models.DateField(blank=True, default=None, help_text='What day was this lab drawn?', null=True)),
                ('value', models.IntegerField(help_text='ALT (SGPT) is typically reported in units per liter (U/L)')),
                ('units', models.CharField(blank=True, choices=[('mg/dL (milligrams per deciliter)', 'mg/dL (milligrams per deciliter)'), ('g/dL (grams per decliter)', 'g/dL (grams per decliter)'), ('cells/mm^3 (cells per cubmic millimeter)', 'cells/mm^3 (cells per cubmic millimeter)'), ('PLTS/μL (platelets per microliter)', 'PLTS/μL (platelets per microliter)'), ('U/L (units per liter)', 'U/L (units per liter)')], default='U/L (units per liter)', max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('date_drawn', models.DateField(blank=True, default=None, help_text='What day was this lab drawn?', null=True)),
                ('value', models.IntegerField(help_text='AST (SGOT) is typically reported in units per liter (U/L)')),
                ('units', models.CharField(blank=True, choices=[('mg/dL (milligrams per deciliter)', 'mg/dL (milligrams per deciliter)'), ('g/dL (grams per decliter)', 'g/dL (grams per decliter)'), ('cells/mm^3 (cells per cubmic millimeter)', 'cells/mm^3 (cells per cubmic millimeter)'), ('PLTS/μL (platelets per microliter)', 'PLTS/μL (platelets per microliter)'), ('U/L (units per liter)', 'U/L (units per liter)')], default='U/L (units per liter)', max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Creatinine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('date_drawn', models.DateField(blank=True, default=None, help_text='What day was this lab drawn?', null=True)),
                ('value', models.DecimalField(decimal_places=2, help_text='Creatinine is typically reported as milligrams per deciliter (mg/dL)', max_digits=4)),
                ('units', models.CharField(blank=True, choices=[('mg/dL (milligrams per deciliter)', 'mg/dL (milligrams per deciliter)'), ('g/dL (grams per decliter)', 'g/dL (grams per decliter)'), ('cells/mm^3 (cells per cubmic millimeter)', 'cells/mm^3 (cells per cubmic millimeter)'), ('PLTS/μL (platelets per microliter)', 'PLTS/μL (platelets per microliter)'), ('U/L (units per liter)', 'U/L (units per liter)')], default='mg/dL (milligrams per deciliter)', max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hemoglobin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('date_drawn', models.DateField(blank=True, default=None, help_text='What day was this lab drawn?', null=True)),
                ('value', models.DecimalField(decimal_places=1, help_text='HGB (hemoglobin) is typically reporeted in grams per deciliter (g/dL)', max_digits=3)),
                ('units', models.CharField(blank=True, choices=[('mg/dL (milligrams per deciliter)', 'mg/dL (milligrams per deciliter)'), ('g/dL (grams per decliter)', 'g/dL (grams per decliter)'), ('cells/mm^3 (cells per cubmic millimeter)', 'cells/mm^3 (cells per cubmic millimeter)'), ('PLTS/μL (platelets per microliter)', 'PLTS/μL (platelets per microliter)'), ('U/L (units per liter)', 'U/L (units per liter)')], default='g/dL (grams per decliter)', max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LabCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('due', models.DateField(default=datetime.date(2022, 2, 23), help_text='When is this lab check due?')),
                ('completed', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Is this lab check completed?')),
                ('completed_date', models.DateField(blank=True, default=None, help_text='When was this lab check completed?', null=True)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Platelet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('date_drawn', models.DateField(blank=True, default=None, help_text='What day was this lab drawn?', null=True)),
                ('value', models.IntegerField(help_text='PLT (platelets) is typically reported in platelets per microliter (PLT/microL)')),
                ('units', models.CharField(blank=True, choices=[('mg/dL (milligrams per deciliter)', 'mg/dL (milligrams per deciliter)'), ('g/dL (grams per decliter)', 'g/dL (grams per decliter)'), ('cells/mm^3 (cells per cubmic millimeter)', 'cells/mm^3 (cells per cubmic millimeter)'), ('PLTS/μL (platelets per microliter)', 'PLTS/μL (platelets per microliter)'), ('U/L (units per liter)', 'U/L (units per liter)')], default='PLTS/μL (platelets per microliter)', max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Urate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('date_drawn', models.DateField(blank=True, default=None, help_text='What day was this lab drawn?', null=True)),
                ('value', models.DecimalField(decimal_places=1, help_text='Uric acid is typically reported in micrograms per deciliter (mg/dL)', max_digits=3)),
                ('units', models.CharField(blank=True, choices=[('mg/dL (milligrams per deciliter)', 'mg/dL (milligrams per deciliter)'), ('g/dL (grams per decliter)', 'g/dL (grams per decliter)'), ('cells/mm^3 (cells per cubmic millimeter)', 'cells/mm^3 (cells per cubmic millimeter)'), ('PLTS/μL (platelets per microliter)', 'PLTS/μL (platelets per microliter)'), ('U/L (units per liter)', 'U/L (units per liter)')], default='mg/dL (milligrams per deciliter)', max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WBC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('date_drawn', models.DateField(blank=True, default=None, help_text='What day was this lab drawn?', null=True)),
                ('value', models.DecimalField(decimal_places=1, help_text='WBC (white blood cells) is typically reported as cells per cubic millimeter (cells/mm^3)', max_digits=3)),
                ('units', models.CharField(blank=True, choices=[('mg/dL (milligrams per deciliter)', 'mg/dL (milligrams per deciliter)'), ('g/dL (grams per decliter)', 'g/dL (grams per decliter)'), ('cells/mm^3 (cells per cubmic millimeter)', 'cells/mm^3 (cells per cubmic millimeter)'), ('PLTS/μL (platelets per microliter)', 'PLTS/μL (platelets per microliter)'), ('U/L (units per liter)', 'U/L (units per liter)')], default='cells/mm^3 (cells per cubmic millimeter)', max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
