# Generated by Django 3.1.7 on 2022-03-25 00:47

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_auto_20220313_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='alt',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AddField(
            model_name='ast',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AddField(
            model_name='baselinealt',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AddField(
            model_name='baselineast',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AddField(
            model_name='baselinecreatinine',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AddField(
            model_name='baselinehemoglobin',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AddField(
            model_name='baselineplatelet',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AddField(
            model_name='baselinewbc',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AddField(
            model_name='creatinine',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AddField(
            model_name='hemoglobin',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AddField(
            model_name='historicalalt',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AddField(
            model_name='historicalast',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AddField(
            model_name='historicalbaselinealt',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AddField(
            model_name='historicalbaselineast',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AddField(
            model_name='historicalbaselinecreatinine',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AddField(
            model_name='historicalbaselinehemoglobin',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AddField(
            model_name='historicalbaselineplatelet',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AddField(
            model_name='historicalbaselinewbc',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AddField(
            model_name='historicalcreatinine',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AddField(
            model_name='historicalhemoglobin',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AddField(
            model_name='historicalplatelet',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AddField(
            model_name='historicalurate',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AddField(
            model_name='historicalwbc',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AddField(
            model_name='platelet',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AddField(
            model_name='urate',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AddField(
            model_name='wbc',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='historicallabcheck',
            name='due',
            field=models.DateField(default=datetime.date(2022, 5, 6), help_text='When is this lab check due?'),
        ),
        migrations.AlterField(
            model_name='labcheck',
            name='due',
            field=models.DateField(default=datetime.date(2022, 5, 6), help_text='When is this lab check due?'),
        ),
    ]
