# Generated by Django 3.1.7 on 2022-03-06 00:17

import datetime
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lab', '0002_auto_20220302_0209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alt',
            name='abnormal_flag',
        ),
        migrations.RemoveField(
            model_name='alt',
            name='baseline',
        ),
        migrations.RemoveField(
            model_name='alt',
            name='ultplan',
        ),
        migrations.RemoveField(
            model_name='ast',
            name='abnormal_flag',
        ),
        migrations.RemoveField(
            model_name='ast',
            name='baseline',
        ),
        migrations.RemoveField(
            model_name='ast',
            name='ultplan',
        ),
        migrations.RemoveField(
            model_name='creatinine',
            name='abnormal_flag',
        ),
        migrations.RemoveField(
            model_name='creatinine',
            name='baseline',
        ),
        migrations.RemoveField(
            model_name='creatinine',
            name='ultplan',
        ),
        migrations.RemoveField(
            model_name='hemoglobin',
            name='abnormal_flag',
        ),
        migrations.RemoveField(
            model_name='hemoglobin',
            name='baseline',
        ),
        migrations.RemoveField(
            model_name='hemoglobin',
            name='ultplan',
        ),
        migrations.RemoveField(
            model_name='historicalalt',
            name='abnormal_flag',
        ),
        migrations.RemoveField(
            model_name='historicalalt',
            name='baseline',
        ),
        migrations.RemoveField(
            model_name='historicalalt',
            name='ultplan',
        ),
        migrations.RemoveField(
            model_name='historicalast',
            name='abnormal_flag',
        ),
        migrations.RemoveField(
            model_name='historicalast',
            name='baseline',
        ),
        migrations.RemoveField(
            model_name='historicalast',
            name='ultplan',
        ),
        migrations.RemoveField(
            model_name='historicalcreatinine',
            name='abnormal_flag',
        ),
        migrations.RemoveField(
            model_name='historicalcreatinine',
            name='baseline',
        ),
        migrations.RemoveField(
            model_name='historicalcreatinine',
            name='ultplan',
        ),
        migrations.RemoveField(
            model_name='historicalhemoglobin',
            name='abnormal_flag',
        ),
        migrations.RemoveField(
            model_name='historicalhemoglobin',
            name='baseline',
        ),
        migrations.RemoveField(
            model_name='historicalhemoglobin',
            name='ultplan',
        ),
        migrations.RemoveField(
            model_name='historicallabcheck',
            name='abnormal_labcheck',
        ),
        migrations.RemoveField(
            model_name='historicalplatelet',
            name='abnormal_flag',
        ),
        migrations.RemoveField(
            model_name='historicalplatelet',
            name='baseline',
        ),
        migrations.RemoveField(
            model_name='historicalplatelet',
            name='ultplan',
        ),
        migrations.RemoveField(
            model_name='historicalurate',
            name='abnormal_flag',
        ),
        migrations.RemoveField(
            model_name='historicalurate',
            name='baseline',
        ),
        migrations.RemoveField(
            model_name='historicalurate',
            name='ultplan',
        ),
        migrations.RemoveField(
            model_name='historicalwbc',
            name='abnormal_flag',
        ),
        migrations.RemoveField(
            model_name='historicalwbc',
            name='baseline',
        ),
        migrations.RemoveField(
            model_name='historicalwbc',
            name='ultplan',
        ),
        migrations.RemoveField(
            model_name='labcheck',
            name='abnormal_labcheck',
        ),
        migrations.RemoveField(
            model_name='platelet',
            name='abnormal_flag',
        ),
        migrations.RemoveField(
            model_name='platelet',
            name='baseline',
        ),
        migrations.RemoveField(
            model_name='platelet',
            name='ultplan',
        ),
        migrations.RemoveField(
            model_name='urate',
            name='abnormal_flag',
        ),
        migrations.RemoveField(
            model_name='urate',
            name='baseline',
        ),
        migrations.RemoveField(
            model_name='urate',
            name='ultplan',
        ),
        migrations.RemoveField(
            model_name='wbc',
            name='abnormal_flag',
        ),
        migrations.RemoveField(
            model_name='wbc',
            name='baseline',
        ),
        migrations.RemoveField(
            model_name='wbc',
            name='ultplan',
        ),
        migrations.AlterField(
            model_name='historicallabcheck',
            name='due',
            field=models.DateField(default=datetime.date(2022, 4, 17), help_text='When is this lab check due?'),
        ),
        migrations.AlterField(
            model_name='labcheck',
            name='due',
            field=models.DateField(default=datetime.date(2022, 4, 17), help_text='When is this lab check due?'),
        ),
        migrations.CreateModel(
            name='HistoricalBaselineWBC',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('units', models.CharField(blank=True, choices=[('mg/dL (milligrams per deciliter)', 'mg/dL (milligrams per deciliter)'), ('g/dL (grams per deciliter)', 'g/dL (grams per deciliter)'), ('cells/mm^3 (cells per cubic millimeter)', 'cells/mm^3 (cells per cubmic millimeter)'), ('PLTS/μL (platelets per microliter)', 'PLTS/μL (platelets per microliter)'), ('U/L (units per liter)', 'U/L (units per liter)')], default='cells/mm^3 (cells per cubic millimeter)', max_length=100, null=True)),
                ('reference_lower', models.DecimalField(decimal_places=1, default=Decimal('4.5'), help_text='Lower limit of normal values for WBC', max_digits=3)),
                ('reference_upper', models.DecimalField(decimal_places=1, default=Decimal('11'), help_text='Upper limit of normal values for WBC', max_digits=3)),
                ('value', models.DecimalField(blank=True, decimal_places=1, help_text='WBC (white blood cells) is typically reported as cells per cubic millimeter (cells/mm^3)', max_digits=3, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('creator', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical baseline wbc',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalBaselinePlatelet',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('units', models.CharField(blank=True, choices=[('mg/dL (milligrams per deciliter)', 'mg/dL (milligrams per deciliter)'), ('g/dL (grams per deciliter)', 'g/dL (grams per deciliter)'), ('cells/mm^3 (cells per cubic millimeter)', 'cells/mm^3 (cells per cubmic millimeter)'), ('PLTS/μL (platelets per microliter)', 'PLTS/μL (platelets per microliter)'), ('U/L (units per liter)', 'U/L (units per liter)')], default='PLTS/μL (platelets per microliter)', max_length=100, null=True)),
                ('reference_lower', models.IntegerField(default=150, help_text='Lower limit of normal values for platelets')),
                ('reference_upper', models.IntegerField(default=450, help_text='Upper limit of normal values for platelets')),
                ('value', models.IntegerField(blank=True, help_text='PLT (platelets) is typically reported in platelets per microliter (PLT/microL)', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('creator', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical baseline platelet',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalBaselineHemoglobin',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('units', models.CharField(blank=True, choices=[('mg/dL (milligrams per deciliter)', 'mg/dL (milligrams per deciliter)'), ('g/dL (grams per deciliter)', 'g/dL (grams per deciliter)'), ('cells/mm^3 (cells per cubic millimeter)', 'cells/mm^3 (cells per cubmic millimeter)'), ('PLTS/μL (platelets per microliter)', 'PLTS/μL (platelets per microliter)'), ('U/L (units per liter)', 'U/L (units per liter)')], default='g/dL (grams per deciliter)', max_length=100, null=True)),
                ('reference_lower', models.DecimalField(decimal_places=1, default=Decimal('13.5'), help_text='Lower limit of normal values for hemoglobin', max_digits=3)),
                ('reference_upper', models.DecimalField(decimal_places=1, default=Decimal('17.5'), help_text='Upper limit of normal values for hemoglobin', max_digits=3)),
                ('value', models.DecimalField(blank=True, decimal_places=1, help_text='HGB (hemoglobin) is typically reporeted in grams per deciliter (g/dL)', max_digits=3, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('creator', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical baseline hemoglobin',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalBaselineCreatinine',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('units', models.CharField(blank=True, choices=[('mg/dL (milligrams per deciliter)', 'mg/dL (milligrams per deciliter)'), ('g/dL (grams per deciliter)', 'g/dL (grams per deciliter)'), ('cells/mm^3 (cells per cubic millimeter)', 'cells/mm^3 (cells per cubmic millimeter)'), ('PLTS/μL (platelets per microliter)', 'PLTS/μL (platelets per microliter)'), ('U/L (units per liter)', 'U/L (units per liter)')], default='mg/dL (milligrams per deciliter)', max_length=100, null=True)),
                ('reference_lower', models.DecimalField(decimal_places=2, default=Decimal('0.7399999999999999911182158029987476766109466552734375'), help_text='Lower limit of normal values for creatinine', max_digits=4)),
                ('reference_upper', models.DecimalField(decimal_places=2, default=Decimal('1.350000000000000088817841970012523233890533447265625'), help_text='Upper limit of normal values for creatinine', max_digits=4)),
                ('value', models.DecimalField(blank=True, decimal_places=2, help_text='Creatinine is typically reported as milligrams per deciliter (mg/dL)', max_digits=4, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('creator', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical baseline creatinine',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalBaselineAST',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('units', models.CharField(blank=True, choices=[('mg/dL (milligrams per deciliter)', 'mg/dL (milligrams per deciliter)'), ('g/dL (grams per deciliter)', 'g/dL (grams per deciliter)'), ('cells/mm^3 (cells per cubic millimeter)', 'cells/mm^3 (cells per cubmic millimeter)'), ('PLTS/μL (platelets per microliter)', 'PLTS/μL (platelets per microliter)'), ('U/L (units per liter)', 'U/L (units per liter)')], default='U/L (units per liter)', max_length=100, null=True)),
                ('reference_lower', models.IntegerField(default=10, help_text='Lower limit of normal values for AST')),
                ('reference_upper', models.IntegerField(default=40, help_text='Upper limit of normal values for AST')),
                ('value', models.IntegerField(blank=True, help_text='AST (SGOT) is typically reported in units per liter (U/L)', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('creator', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical baseline ast',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalBaselineALT',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('units', models.CharField(blank=True, choices=[('mg/dL (milligrams per deciliter)', 'mg/dL (milligrams per deciliter)'), ('g/dL (grams per deciliter)', 'g/dL (grams per deciliter)'), ('cells/mm^3 (cells per cubic millimeter)', 'cells/mm^3 (cells per cubmic millimeter)'), ('PLTS/μL (platelets per microliter)', 'PLTS/μL (platelets per microliter)'), ('U/L (units per liter)', 'U/L (units per liter)')], default='U/L (units per liter)', max_length=100, null=True)),
                ('reference_lower', models.IntegerField(default=7, help_text='Lower limit of normal values for ALT')),
                ('reference_upper', models.IntegerField(default=55, help_text='Upper limit of normal values for ALT')),
                ('value', models.IntegerField(blank=True, help_text='ALT (SGPT) is typically reported in units per liter (U/L)', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('creator', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical baseline alt',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='BaselineWBC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('units', models.CharField(blank=True, choices=[('mg/dL (milligrams per deciliter)', 'mg/dL (milligrams per deciliter)'), ('g/dL (grams per deciliter)', 'g/dL (grams per deciliter)'), ('cells/mm^3 (cells per cubic millimeter)', 'cells/mm^3 (cells per cubmic millimeter)'), ('PLTS/μL (platelets per microliter)', 'PLTS/μL (platelets per microliter)'), ('U/L (units per liter)', 'U/L (units per liter)')], default='cells/mm^3 (cells per cubic millimeter)', max_length=100, null=True)),
                ('reference_lower', models.DecimalField(decimal_places=1, default=Decimal('4.5'), help_text='Lower limit of normal values for WBC', max_digits=3)),
                ('reference_upper', models.DecimalField(decimal_places=1, default=Decimal('11'), help_text='Upper limit of normal values for WBC', max_digits=3)),
                ('value', models.DecimalField(blank=True, decimal_places=1, help_text='WBC (white blood cells) is typically reported as cells per cubic millimeter (cells/mm^3)', max_digits=3, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baselinewbc_creator', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BaselinePlatelet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('units', models.CharField(blank=True, choices=[('mg/dL (milligrams per deciliter)', 'mg/dL (milligrams per deciliter)'), ('g/dL (grams per deciliter)', 'g/dL (grams per deciliter)'), ('cells/mm^3 (cells per cubic millimeter)', 'cells/mm^3 (cells per cubmic millimeter)'), ('PLTS/μL (platelets per microliter)', 'PLTS/μL (platelets per microliter)'), ('U/L (units per liter)', 'U/L (units per liter)')], default='PLTS/μL (platelets per microliter)', max_length=100, null=True)),
                ('reference_lower', models.IntegerField(default=150, help_text='Lower limit of normal values for platelets')),
                ('reference_upper', models.IntegerField(default=450, help_text='Upper limit of normal values for platelets')),
                ('value', models.IntegerField(blank=True, help_text='PLT (platelets) is typically reported in platelets per microliter (PLT/microL)', null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baselineplatelet_creator', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BaselineHemoglobin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('units', models.CharField(blank=True, choices=[('mg/dL (milligrams per deciliter)', 'mg/dL (milligrams per deciliter)'), ('g/dL (grams per deciliter)', 'g/dL (grams per deciliter)'), ('cells/mm^3 (cells per cubic millimeter)', 'cells/mm^3 (cells per cubmic millimeter)'), ('PLTS/μL (platelets per microliter)', 'PLTS/μL (platelets per microliter)'), ('U/L (units per liter)', 'U/L (units per liter)')], default='g/dL (grams per deciliter)', max_length=100, null=True)),
                ('reference_lower', models.DecimalField(decimal_places=1, default=Decimal('13.5'), help_text='Lower limit of normal values for hemoglobin', max_digits=3)),
                ('reference_upper', models.DecimalField(decimal_places=1, default=Decimal('17.5'), help_text='Upper limit of normal values for hemoglobin', max_digits=3)),
                ('value', models.DecimalField(blank=True, decimal_places=1, help_text='HGB (hemoglobin) is typically reporeted in grams per deciliter (g/dL)', max_digits=3, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baselinehemoglobin_creator', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BaselineCreatinine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('units', models.CharField(blank=True, choices=[('mg/dL (milligrams per deciliter)', 'mg/dL (milligrams per deciliter)'), ('g/dL (grams per deciliter)', 'g/dL (grams per deciliter)'), ('cells/mm^3 (cells per cubic millimeter)', 'cells/mm^3 (cells per cubmic millimeter)'), ('PLTS/μL (platelets per microliter)', 'PLTS/μL (platelets per microliter)'), ('U/L (units per liter)', 'U/L (units per liter)')], default='mg/dL (milligrams per deciliter)', max_length=100, null=True)),
                ('reference_lower', models.DecimalField(decimal_places=2, default=Decimal('0.7399999999999999911182158029987476766109466552734375'), help_text='Lower limit of normal values for creatinine', max_digits=4)),
                ('reference_upper', models.DecimalField(decimal_places=2, default=Decimal('1.350000000000000088817841970012523233890533447265625'), help_text='Upper limit of normal values for creatinine', max_digits=4)),
                ('value', models.DecimalField(blank=True, decimal_places=2, help_text='Creatinine is typically reported as milligrams per deciliter (mg/dL)', max_digits=4, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baselinecreatinine_creator', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BaselineAST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('units', models.CharField(blank=True, choices=[('mg/dL (milligrams per deciliter)', 'mg/dL (milligrams per deciliter)'), ('g/dL (grams per deciliter)', 'g/dL (grams per deciliter)'), ('cells/mm^3 (cells per cubic millimeter)', 'cells/mm^3 (cells per cubmic millimeter)'), ('PLTS/μL (platelets per microliter)', 'PLTS/μL (platelets per microliter)'), ('U/L (units per liter)', 'U/L (units per liter)')], default='U/L (units per liter)', max_length=100, null=True)),
                ('reference_lower', models.IntegerField(default=10, help_text='Lower limit of normal values for AST')),
                ('reference_upper', models.IntegerField(default=40, help_text='Upper limit of normal values for AST')),
                ('value', models.IntegerField(blank=True, help_text='AST (SGOT) is typically reported in units per liter (U/L)', null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baselineast_creator', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BaselineALT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('units', models.CharField(blank=True, choices=[('mg/dL (milligrams per deciliter)', 'mg/dL (milligrams per deciliter)'), ('g/dL (grams per deciliter)', 'g/dL (grams per deciliter)'), ('cells/mm^3 (cells per cubic millimeter)', 'cells/mm^3 (cells per cubmic millimeter)'), ('PLTS/μL (platelets per microliter)', 'PLTS/μL (platelets per microliter)'), ('U/L (units per liter)', 'U/L (units per liter)')], default='U/L (units per liter)', max_length=100, null=True)),
                ('reference_lower', models.IntegerField(default=7, help_text='Lower limit of normal values for ALT')),
                ('reference_upper', models.IntegerField(default=55, help_text='Upper limit of normal values for ALT')),
                ('value', models.IntegerField(blank=True, help_text='ALT (SGPT) is typically reported in units per liter (U/L)', null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baselinealt_creator', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
