# Generated by Django 3.1.7 on 2021-04-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_alt_ast_creatinine_hemoglobin_platelet_wbc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ast',
            name='ast_sgot',
            field=models.IntegerField(help_text='AST / SGOT'),
        ),
    ]
