# Generated by Django 3.1.7 on 2022-03-26 00:49

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_auto_20220325_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallabcheck',
            name='abnormal_followup',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lab.labcheck'),
        ),
        migrations.AddField(
            model_name='labcheck',
            name='abnormal_followup',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='lab.labcheck'),
        ),
        migrations.AlterField(
            model_name='alt',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency'), (5, 'Error'), (6, 'Improving')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='ast',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency'), (5, 'Error'), (6, 'Improving')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='baselinealt',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency'), (5, 'Error'), (6, 'Improving')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='baselineast',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency'), (5, 'Error'), (6, 'Improving')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='baselinecreatinine',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency'), (5, 'Error'), (6, 'Improving')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='baselinehemoglobin',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency'), (5, 'Error'), (6, 'Improving')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='baselineplatelet',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency'), (5, 'Error'), (6, 'Improving')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='baselinewbc',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency'), (5, 'Error'), (6, 'Improving')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='creatinine',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency'), (5, 'Error'), (6, 'Improving')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='hemoglobin',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency'), (5, 'Error'), (6, 'Improving')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='historicalalt',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency'), (5, 'Error'), (6, 'Improving')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='historicalast',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency'), (5, 'Error'), (6, 'Improving')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='historicalbaselinealt',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency'), (5, 'Error'), (6, 'Improving')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='historicalbaselineast',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency'), (5, 'Error'), (6, 'Improving')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='historicalbaselinecreatinine',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency'), (5, 'Error'), (6, 'Improving')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='historicalbaselinehemoglobin',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency'), (5, 'Error'), (6, 'Improving')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='historicalbaselineplatelet',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency'), (5, 'Error'), (6, 'Improving')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='historicalbaselinewbc',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency'), (5, 'Error'), (6, 'Improving')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='historicalcreatinine',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency'), (5, 'Error'), (6, 'Improving')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='historicalhemoglobin',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency'), (5, 'Error'), (6, 'Improving')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='historicallabcheck',
            name='completed_date',
            field=models.DateTimeField(blank=True, default=None, help_text='When was this lab check completed?', null=True),
        ),
        migrations.AlterField(
            model_name='historicallabcheck',
            name='due',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 7, 0, 48, 49, 197490, tzinfo=utc), help_text='When is this lab check due?'),
        ),
        migrations.AlterField(
            model_name='historicalplatelet',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency'), (5, 'Error'), (6, 'Improving')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='historicalurate',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency'), (5, 'Error'), (6, 'Improving')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='historicalwbc',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency'), (5, 'Error'), (6, 'Improving')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='labcheck',
            name='completed_date',
            field=models.DateTimeField(blank=True, default=None, help_text='When was this lab check completed?', null=True),
        ),
        migrations.AlterField(
            model_name='labcheck',
            name='due',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 7, 0, 48, 49, 197490, tzinfo=utc), help_text='When is this lab check due?'),
        ),
        migrations.AlterField(
            model_name='platelet',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency'), (5, 'Error'), (6, 'Improving')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='urate',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency'), (5, 'Error'), (6, 'Improving')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='wbc',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency'), (5, 'Error'), (6, 'Improving')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
    ]
