# Generated by Django 3.1.7 on 2022-03-08 00:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_auto_20220306_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baselinecreatinine',
            name='value',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Creatinine is typically reported as milligrams per deciliter (mg/dL)', max_digits=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalbaselinecreatinine',
            name='value',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Creatinine is typically reported as milligrams per deciliter (mg/dL)', max_digits=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicallabcheck',
            name='due',
            field=models.DateField(default=datetime.date(2022, 4, 19), help_text='When is this lab check due?'),
        ),
        migrations.AlterField(
            model_name='labcheck',
            name='due',
            field=models.DateField(default=datetime.date(2022, 4, 19), help_text='When is this lab check due?'),
        ),
    ]
