# Generated by Django 3.1.7 on 2021-12-07 17:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_auto_20211202_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urate',
            name='value',
            field=models.DecimalField(decimal_places=1, help_text='Typically reported in mg/dL', max_digits=3, validators=[django.core.validators.MinLengthValidator(0)]),
        ),
    ]
