# Generated by Django 3.1.7 on 2022-01-28 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_auto_20220121_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='alt',
            name='baseline',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Is this the baseline for this User?', verbose_name='Baseline'),
        ),
        migrations.AddField(
            model_name='ast',
            name='baseline',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Is this the baseline for this User?', verbose_name='Baseline'),
        ),
        migrations.AddField(
            model_name='creatinine',
            name='baseline',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Is this the baseline for this User?', verbose_name='Baseline'),
        ),
        migrations.AddField(
            model_name='hemoglobin',
            name='baseline',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Is this the baseline for this User?', verbose_name='Baseline'),
        ),
        migrations.AddField(
            model_name='platelet',
            name='baseline',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Is this the baseline for this User?', verbose_name='Baseline'),
        ),
        migrations.AddField(
            model_name='urate',
            name='baseline',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Is this the baseline for this User?', verbose_name='Baseline'),
        ),
        migrations.AddField(
            model_name='wbc',
            name='baseline',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Is this the baseline for this User?', verbose_name='Baseline'),
        ),
        migrations.AlterField(
            model_name='labcheck',
            name='due',
            field=models.DateField(default=datetime.date(2022, 3, 11), help_text='When is this lab check due?'),
        ),
    ]
