# Generated by Django 3.1.7 on 2022-01-12 21:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_auto_20220112_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='alt',
            name='reference_lower',
            field=models.IntegerField(default=7, help_text='Lower limit of normal values for ALT'),
        ),
        migrations.AddField(
            model_name='alt',
            name='reference_upper',
            field=models.IntegerField(default=55, help_text='Upper limit of normal values for ALT'),
        ),
        migrations.AddField(
            model_name='ast',
            name='reference_lower',
            field=models.IntegerField(default=10, help_text='Lower limit of normal values for AST'),
        ),
        migrations.AddField(
            model_name='ast',
            name='reference_upper',
            field=models.IntegerField(default=40, help_text='Upper limit of normal values for AST'),
        ),
        migrations.AddField(
            model_name='creatinine',
            name='reference_lower',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.7399999999999999911182158029987476766109466552734375'), help_text='Lower limit of normal values for creatinine', max_digits=4),
        ),
        migrations.AddField(
            model_name='creatinine',
            name='reference_upper',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.350000000000000088817841970012523233890533447265625'), help_text='Upper limit of normal values for creatinine', max_digits=4),
        ),
        migrations.AddField(
            model_name='hemoglobin',
            name='reference_lower',
            field=models.DecimalField(decimal_places=1, default=Decimal('13.5'), help_text='Lower limit of normal values for hemoglobin', max_digits=3),
        ),
        migrations.AddField(
            model_name='hemoglobin',
            name='reference_upper',
            field=models.DecimalField(decimal_places=1, default=Decimal('17.5'), help_text='Upper limit of normal values for hemoglobin', max_digits=3),
        ),
        migrations.AddField(
            model_name='platelet',
            name='reference_lower',
            field=models.IntegerField(default=150, help_text='Lower limit of normal values for platelets'),
        ),
        migrations.AddField(
            model_name='platelet',
            name='reference_upper',
            field=models.IntegerField(default=450, help_text='Upper limit of normal values for platelets'),
        ),
        migrations.AddField(
            model_name='urate',
            name='reference_lower',
            field=models.DecimalField(decimal_places=1, default=3.5, help_text='Lower limit of normal values for urate', max_digits=3),
        ),
        migrations.AddField(
            model_name='urate',
            name='reference_upper',
            field=models.DecimalField(decimal_places=1, default=7.2, help_text='Upper limit of normal values for urate', max_digits=3),
        ),
        migrations.AddField(
            model_name='wbc',
            name='reference_lower',
            field=models.DecimalField(decimal_places=1, default=Decimal('4.5'), help_text='Lower limit of normal values for WBC', max_digits=3),
        ),
        migrations.AddField(
            model_name='wbc',
            name='reference_upper',
            field=models.DecimalField(decimal_places=1, default=Decimal('11'), help_text='Upper limit of normal values for WBC', max_digits=3),
        ),
    ]
