# Generated by Django 3.1.7 on 2022-01-11 20:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_auto_20220108_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labcheck',
            name='due',
            field=models.DateField(default=datetime.date(2022, 2, 22), help_text='When is this lab check due?'),
        ),
    ]
