# Generated by Django 3.1.7 on 2022-02-01 03:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_auto_20220130_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallabcheck',
            name='due',
            field=models.DateField(default=datetime.date(2022, 3, 15), help_text='When is this lab check due?'),
        ),
        migrations.AlterField(
            model_name='labcheck',
            name='due',
            field=models.DateField(default=datetime.date(2022, 3, 15), help_text='When is this lab check due?'),
        ),
    ]
