# Generated by Django 3.1.7 on 2022-01-13 00:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_auto_20220112_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labcheck',
            name='due',
            field=models.DateField(default=datetime.date(2022, 2, 24), help_text='When is this lab check due?'),
        ),
    ]
