# Generated by Django 3.1.7 on 2021-12-19 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ultaid', '0006_ultaid_titrating'),
        ('lab', '0005_auto_20211208_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='alt',
            name='ULTAid',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ultaid.ultaid'),
        ),
        migrations.AddField(
            model_name='ast',
            name='ULTAid',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ultaid.ultaid'),
        ),
        migrations.AddField(
            model_name='creatinine',
            name='ULTAid',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ultaid.ultaid'),
        ),
        migrations.AddField(
            model_name='hemoglobin',
            name='ULTAid',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ultaid.ultaid'),
        ),
        migrations.AddField(
            model_name='platelet',
            name='ULTAid',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ultaid.ultaid'),
        ),
        migrations.AddField(
            model_name='urate',
            name='ULTAid',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ultaid.ultaid'),
        ),
        migrations.AddField(
            model_name='wbc',
            name='ULTAid',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ultaid.ultaid'),
        ),
    ]
