# Generated by Django 3.1.7 on 2022-03-30 16:22

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_auto_20220326_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alt',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency'), (5, 'Resolved'), (6, 'Improving Restart'), (7, 'Improving Recheck')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AlterField(
            model_name='ast',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency'), (5, 'Resolved'), (6, 'Improving Restart'), (7, 'Improving Recheck')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AlterField(
            model_name='baselinealt',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency'), (5, 'Resolved'), (6, 'Improving Restart'), (7, 'Improving Recheck')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AlterField(
            model_name='baselineast',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency'), (5, 'Resolved'), (6, 'Improving Restart'), (7, 'Improving Recheck')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AlterField(
            model_name='baselinecreatinine',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency'), (5, 'Resolved'), (6, 'Improving Restart'), (7, 'Improving Recheck')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AlterField(
            model_name='baselinehemoglobin',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency'), (5, 'Resolved'), (6, 'Improving Restart'), (7, 'Improving Recheck')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AlterField(
            model_name='baselineplatelet',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency'), (5, 'Resolved'), (6, 'Improving Restart'), (7, 'Improving Recheck')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AlterField(
            model_name='baselinewbc',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency'), (5, 'Resolved'), (6, 'Improving Restart'), (7, 'Improving Recheck')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AlterField(
            model_name='creatinine',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency'), (5, 'Resolved'), (6, 'Improving Restart'), (7, 'Improving Recheck')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AlterField(
            model_name='hemoglobin',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency'), (5, 'Resolved'), (6, 'Improving Restart'), (7, 'Improving Recheck')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AlterField(
            model_name='historicalalt',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency'), (5, 'Resolved'), (6, 'Improving Restart'), (7, 'Improving Recheck')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AlterField(
            model_name='historicalast',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency'), (5, 'Resolved'), (6, 'Improving Restart'), (7, 'Improving Recheck')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AlterField(
            model_name='historicalbaselinealt',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency'), (5, 'Resolved'), (6, 'Improving Restart'), (7, 'Improving Recheck')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AlterField(
            model_name='historicalbaselineast',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency'), (5, 'Resolved'), (6, 'Improving Restart'), (7, 'Improving Recheck')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AlterField(
            model_name='historicalbaselinecreatinine',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency'), (5, 'Resolved'), (6, 'Improving Restart'), (7, 'Improving Recheck')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AlterField(
            model_name='historicalbaselinehemoglobin',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency'), (5, 'Resolved'), (6, 'Improving Restart'), (7, 'Improving Recheck')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AlterField(
            model_name='historicalbaselineplatelet',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency'), (5, 'Resolved'), (6, 'Improving Restart'), (7, 'Improving Recheck')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AlterField(
            model_name='historicalbaselinewbc',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency'), (5, 'Resolved'), (6, 'Improving Restart'), (7, 'Improving Recheck')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AlterField(
            model_name='historicalcreatinine',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency'), (5, 'Resolved'), (6, 'Improving Restart'), (7, 'Improving Recheck')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AlterField(
            model_name='historicalhemoglobin',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency'), (5, 'Resolved'), (6, 'Improving Restart'), (7, 'Improving Recheck')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AlterField(
            model_name='historicallabcheck',
            name='due',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 11, 16, 22, 16, 190800, tzinfo=utc), help_text='When is this lab check due?'),
        ),
        migrations.AlterField(
            model_name='historicalplatelet',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency'), (5, 'Resolved'), (6, 'Improving Restart'), (7, 'Improving Recheck')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AlterField(
            model_name='historicalurate',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency'), (5, 'Resolved'), (6, 'Improving Restart'), (7, 'Improving Recheck')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AlterField(
            model_name='historicalwbc',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency'), (5, 'Resolved'), (6, 'Improving Restart'), (7, 'Improving Recheck')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AlterField(
            model_name='labcheck',
            name='due',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 11, 16, 22, 16, 190800, tzinfo=utc), help_text='When is this lab check due?'),
        ),
        migrations.AlterField(
            model_name='platelet',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency'), (5, 'Resolved'), (6, 'Improving Restart'), (7, 'Improving Recheck')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AlterField(
            model_name='urate',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency'), (5, 'Resolved'), (6, 'Improving Restart'), (7, 'Improving Recheck')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AlterField(
            model_name='wbc',
            name='flag',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Trivial'), (2, 'Nonurgent'), (3, 'Urgent'), (4, 'Emergency'), (5, 'Resolved'), (6, 'Improving Restart'), (7, 'Improving Recheck')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)]),
        ),
    ]
