# Generated by Django 3.1.7 on 2022-01-13 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_auto_20220113_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='alt',
            name='abnormal_flag',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Is this lab abnormal?', verbose_name='Abnormal Flag'),
        ),
        migrations.AddField(
            model_name='ast',
            name='abnormal_flag',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Is this lab abnormal?', verbose_name='Abnormal Flag'),
        ),
        migrations.AddField(
            model_name='creatinine',
            name='abnormal_flag',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Is this lab abnormal?', verbose_name='Abnormal Flag'),
        ),
        migrations.AddField(
            model_name='hemoglobin',
            name='abnormal_flag',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Is this lab abnormal?', verbose_name='Abnormal Flag'),
        ),
        migrations.AddField(
            model_name='platelet',
            name='abnormal_flag',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Is this lab abnormal?', verbose_name='Abnormal Flag'),
        ),
        migrations.AddField(
            model_name='urate',
            name='abnormal_flag',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Is this lab abnormal?', verbose_name='Abnormal Flag'),
        ),
        migrations.AddField(
            model_name='wbc',
            name='abnormal_flag',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Is this lab abnormal?', verbose_name='Abnormal Flag'),
        ),
    ]
