# Generated by Django 3.1.7 on 2022-01-16 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0006_auto_20220113_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labcheck',
            name='due',
            field=models.DateField(default=datetime.date(2022, 2, 27), help_text='When is this lab check due?'),
        ),
    ]
