# Generated by Django 3.1.7 on 2021-06-24 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0006_auto_20210624_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='alt',
            name='units',
            field=models.CharField(blank=True, choices=[('milligrams per deciliter', 'milligrams per deciliter'), ('grams per decliter', 'grams per deciliter'), ('cells per cubmic millimeter', 'cells per cubic millimeter'), ('platelets per microliter', 'platelets per microliter'), ('units per liter', 'units per liter')], default='units per liter', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ast',
            name='units',
            field=models.CharField(blank=True, choices=[('milligrams per deciliter', 'milligrams per deciliter'), ('grams per decliter', 'grams per deciliter'), ('cells per cubmic millimeter', 'cells per cubic millimeter'), ('platelets per microliter', 'platelets per microliter'), ('units per liter', 'units per liter')], default='units per liter', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='creatinine',
            name='units',
            field=models.CharField(blank=True, choices=[('milligrams per deciliter', 'milligrams per deciliter'), ('grams per decliter', 'grams per deciliter'), ('cells per cubmic millimeter', 'cells per cubic millimeter'), ('platelets per microliter', 'platelets per microliter'), ('units per liter', 'units per liter')], default='milligrams per deciliter', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hemoglobin',
            name='units',
            field=models.CharField(blank=True, choices=[('milligrams per deciliter', 'milligrams per deciliter'), ('grams per decliter', 'grams per deciliter'), ('cells per cubmic millimeter', 'cells per cubic millimeter'), ('platelets per microliter', 'platelets per microliter'), ('units per liter', 'units per liter')], default='grams per decliter', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='platelet',
            name='units',
            field=models.CharField(blank=True, choices=[('milligrams per deciliter', 'milligrams per deciliter'), ('grams per decliter', 'grams per deciliter'), ('cells per cubmic millimeter', 'cells per cubic millimeter'), ('platelets per microliter', 'platelets per microliter'), ('units per liter', 'units per liter')], default='platelets per microliter', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='urate',
            name='units',
            field=models.CharField(blank=True, choices=[('milligrams per deciliter', 'milligrams per deciliter'), ('grams per decliter', 'grams per deciliter'), ('cells per cubmic millimeter', 'cells per cubic millimeter'), ('platelets per microliter', 'platelets per microliter'), ('units per liter', 'units per liter')], default='milligrams per deciliter', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wbc',
            name='units',
            field=models.CharField(blank=True, choices=[('milligrams per deciliter', 'milligrams per deciliter'), ('grams per decliter', 'grams per deciliter'), ('cells per cubmic millimeter', 'cells per cubic millimeter'), ('platelets per microliter', 'platelets per microliter'), ('units per liter', 'units per liter')], default='cells per cubmic millimeter', max_length=100, null=True),
        ),
    ]
