# Generated by Django 3.1.7 on 2021-12-21 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ultplan', '0001_initial'),
        ('lab', '0006_auto_20211219_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='alt',
            name='ultplan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ultplan.ultplan'),
        ),
        migrations.AddField(
            model_name='ast',
            name='ultplan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ultplan.ultplan'),
        ),
        migrations.AddField(
            model_name='creatinine',
            name='ultplan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ultplan.ultplan'),
        ),
        migrations.AddField(
            model_name='hemoglobin',
            name='ultplan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ultplan.ultplan'),
        ),
        migrations.AddField(
            model_name='platelet',
            name='ultplan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ultplan.ultplan'),
        ),
        migrations.AddField(
            model_name='urate',
            name='ultplan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ultplan.ultplan'),
        ),
        migrations.AddField(
            model_name='wbc',
            name='ultplan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ultplan.ultplan'),
        ),
    ]
