# Generated by Django 3.1.7 on 2022-03-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0006_auto_20220308_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alt',
            name='date_drawn',
            field=models.DateTimeField(blank=True, default=None, help_text='What day was this lab drawn?', null=True),
        ),
        migrations.AlterField(
            model_name='ast',
            name='date_drawn',
            field=models.DateTimeField(blank=True, default=None, help_text='What day was this lab drawn?', null=True),
        ),
        migrations.AlterField(
            model_name='creatinine',
            name='date_drawn',
            field=models.DateTimeField(blank=True, default=None, help_text='What day was this lab drawn?', null=True),
        ),
        migrations.AlterField(
            model_name='hemoglobin',
            name='date_drawn',
            field=models.DateTimeField(blank=True, default=None, help_text='What day was this lab drawn?', null=True),
        ),
        migrations.AlterField(
            model_name='historicalalt',
            name='date_drawn',
            field=models.DateTimeField(blank=True, default=None, help_text='What day was this lab drawn?', null=True),
        ),
        migrations.AlterField(
            model_name='historicalast',
            name='date_drawn',
            field=models.DateTimeField(blank=True, default=None, help_text='What day was this lab drawn?', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcreatinine',
            name='date_drawn',
            field=models.DateTimeField(blank=True, default=None, help_text='What day was this lab drawn?', null=True),
        ),
        migrations.AlterField(
            model_name='historicalhemoglobin',
            name='date_drawn',
            field=models.DateTimeField(blank=True, default=None, help_text='What day was this lab drawn?', null=True),
        ),
        migrations.AlterField(
            model_name='historicalplatelet',
            name='date_drawn',
            field=models.DateTimeField(blank=True, default=None, help_text='What day was this lab drawn?', null=True),
        ),
        migrations.AlterField(
            model_name='historicalurate',
            name='date_drawn',
            field=models.DateTimeField(blank=True, default=None, help_text='What day was this lab drawn?', null=True),
        ),
        migrations.AlterField(
            model_name='historicalwbc',
            name='date_drawn',
            field=models.DateTimeField(blank=True, default=None, help_text='What day was this lab drawn?', null=True),
        ),
        migrations.AlterField(
            model_name='platelet',
            name='date_drawn',
            field=models.DateTimeField(blank=True, default=None, help_text='What day was this lab drawn?', null=True),
        ),
        migrations.AlterField(
            model_name='urate',
            name='date_drawn',
            field=models.DateTimeField(blank=True, default=None, help_text='What day was this lab drawn?', null=True),
        ),
        migrations.AlterField(
            model_name='wbc',
            name='date_drawn',
            field=models.DateTimeField(blank=True, default=None, help_text='What day was this lab drawn?', null=True),
        ),
    ]
