# Generated by Django 3.1.7 on 2022-03-10 03:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0007_auto_20220308_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='ast',
            name='alt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.alt'),
        ),
        migrations.AddField(
            model_name='historicalast',
            name='alt',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lab.alt'),
        ),
        migrations.AlterField(
            model_name='historicallabcheck',
            name='due',
            field=models.DateField(default=datetime.date(2022, 4, 21), help_text='When is this lab check due?'),
        ),
        migrations.AlterField(
            model_name='labcheck',
            name='due',
            field=models.DateField(default=datetime.date(2022, 4, 21), help_text='When is this lab check due?'),
        ),
    ]
