# Generated by Django 3.1.7 on 2022-01-18 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0007_auto_20220116_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labcheck',
            name='due',
            field=models.DateField(default=datetime.date(2022, 3, 1), help_text='When is this lab check due?'),
        ),
    ]
