# Generated by Django 3.1.7 on 2021-12-25 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ultplan', '0001_initial'),
        ('lab', '0007_auto_20211221_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alt',
            old_name='ULTAid',
            new_name='ultaid',
        ),
        migrations.RenameField(
            model_name='ast',
            old_name='ULTAid',
            new_name='ultaid',
        ),
        migrations.RenameField(
            model_name='creatinine',
            old_name='ULTAid',
            new_name='ultaid',
        ),
        migrations.RenameField(
            model_name='hemoglobin',
            old_name='ULTAid',
            new_name='ultaid',
        ),
        migrations.RenameField(
            model_name='platelet',
            old_name='ULTAid',
            new_name='ultaid',
        ),
        migrations.RenameField(
            model_name='urate',
            old_name='ULTAid',
            new_name='ultaid',
        ),
        migrations.RenameField(
            model_name='wbc',
            old_name='ULTAid',
            new_name='ultaid',
        ),
        migrations.AlterField(
            model_name='alt',
            name='ultplan',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ultplan.ultplan'),
        ),
        migrations.AlterField(
            model_name='alt',
            name='value',
            field=models.IntegerField(help_text='ALT (SGPT) is typically reported in units per liter (U/L)'),
        ),
        migrations.AlterField(
            model_name='ast',
            name='ultplan',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ultplan.ultplan'),
        ),
        migrations.AlterField(
            model_name='ast',
            name='value',
            field=models.IntegerField(help_text='AST (SGOT) is typically reported in units per liter (U/L)'),
        ),
        migrations.AlterField(
            model_name='creatinine',
            name='ultplan',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ultplan.ultplan'),
        ),
        migrations.AlterField(
            model_name='creatinine',
            name='value',
            field=models.DecimalField(decimal_places=2, help_text='Creatinine is typically reported as milligrams per deciliter (mg/dL)', max_digits=4),
        ),
        migrations.AlterField(
            model_name='hemoglobin',
            name='ultplan',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ultplan.ultplan'),
        ),
        migrations.AlterField(
            model_name='hemoglobin',
            name='value',
            field=models.DecimalField(decimal_places=1, help_text='HGB (hemoglobin) is typically reporeted in grams per deciliter (g/dL)', max_digits=3),
        ),
        migrations.AlterField(
            model_name='platelet',
            name='ultplan',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ultplan.ultplan'),
        ),
        migrations.AlterField(
            model_name='platelet',
            name='value',
            field=models.IntegerField(help_text='PLT (platelets) is typically reported in platelets per microliter (PLT/microL)'),
        ),
        migrations.AlterField(
            model_name='urate',
            name='ultplan',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ultplan.ultplan'),
        ),
        migrations.AlterField(
            model_name='urate',
            name='value',
            field=models.DecimalField(decimal_places=1, help_text='Uric acid is typically reported in micrograms per deciliter (mg/dL)', max_digits=3),
        ),
        migrations.AlterField(
            model_name='wbc',
            name='ultplan',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ultplan.ultplan'),
        ),
        migrations.AlterField(
            model_name='wbc',
            name='value',
            field=models.DecimalField(decimal_places=1, help_text='WBC (white blood cells) is typically reported as cells per cubic millimeter (cells/mm^3)', max_digits=3),
        ),
    ]
