# Generated by Django 3.1.7 on 2021-06-24 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0007_auto_20210624_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alt',
            name='units',
            field=models.CharField(blank=True, choices=[('mg/dL (milligrams per deciliter)', 'mg/dL (milligrams per deciliter)'), ('g/dL (grams per decliter)', 'g/dL (grams per decliter)'), ('cells/mm^3 (cells per cubmic millimeter)', 'cells/mm^3 (cells per cubmic millimeter)'), ('PLTS/μL (platelets per microliter)', 'PLTS/μL (platelets per microliter)'), ('U/L (units per liter)', 'U/L (units per liter)')], default='U/L (units per liter)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ast',
            name='units',
            field=models.CharField(blank=True, choices=[('mg/dL (milligrams per deciliter)', 'mg/dL (milligrams per deciliter)'), ('g/dL (grams per decliter)', 'g/dL (grams per decliter)'), ('cells/mm^3 (cells per cubmic millimeter)', 'cells/mm^3 (cells per cubmic millimeter)'), ('PLTS/μL (platelets per microliter)', 'PLTS/μL (platelets per microliter)'), ('U/L (units per liter)', 'U/L (units per liter)')], default='U/L (units per liter)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='creatinine',
            name='units',
            field=models.CharField(blank=True, choices=[('mg/dL (milligrams per deciliter)', 'mg/dL (milligrams per deciliter)'), ('g/dL (grams per decliter)', 'g/dL (grams per decliter)'), ('cells/mm^3 (cells per cubmic millimeter)', 'cells/mm^3 (cells per cubmic millimeter)'), ('PLTS/μL (platelets per microliter)', 'PLTS/μL (platelets per microliter)'), ('U/L (units per liter)', 'U/L (units per liter)')], default='mg/dL (milligrams per deciliter)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hemoglobin',
            name='units',
            field=models.CharField(blank=True, choices=[('mg/dL (milligrams per deciliter)', 'mg/dL (milligrams per deciliter)'), ('g/dL (grams per decliter)', 'g/dL (grams per decliter)'), ('cells/mm^3 (cells per cubmic millimeter)', 'cells/mm^3 (cells per cubmic millimeter)'), ('PLTS/μL (platelets per microliter)', 'PLTS/μL (platelets per microliter)'), ('U/L (units per liter)', 'U/L (units per liter)')], default='g/dL (grams per decliter)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='platelet',
            name='units',
            field=models.CharField(blank=True, choices=[('mg/dL (milligrams per deciliter)', 'mg/dL (milligrams per deciliter)'), ('g/dL (grams per decliter)', 'g/dL (grams per decliter)'), ('cells/mm^3 (cells per cubmic millimeter)', 'cells/mm^3 (cells per cubmic millimeter)'), ('PLTS/μL (platelets per microliter)', 'PLTS/μL (platelets per microliter)'), ('U/L (units per liter)', 'U/L (units per liter)')], default='PLTS/μL (platelets per microliter)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='urate',
            name='units',
            field=models.CharField(blank=True, choices=[('mg/dL (milligrams per deciliter)', 'mg/dL (milligrams per deciliter)'), ('g/dL (grams per decliter)', 'g/dL (grams per decliter)'), ('cells/mm^3 (cells per cubmic millimeter)', 'cells/mm^3 (cells per cubmic millimeter)'), ('PLTS/μL (platelets per microliter)', 'PLTS/μL (platelets per microliter)'), ('U/L (units per liter)', 'U/L (units per liter)')], default='mg/dL (milligrams per deciliter)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wbc',
            name='units',
            field=models.CharField(blank=True, choices=[('mg/dL (milligrams per deciliter)', 'mg/dL (milligrams per deciliter)'), ('g/dL (grams per decliter)', 'g/dL (grams per decliter)'), ('cells/mm^3 (cells per cubmic millimeter)', 'cells/mm^3 (cells per cubmic millimeter)'), ('PLTS/μL (platelets per microliter)', 'PLTS/μL (platelets per microliter)'), ('U/L (units per liter)', 'U/L (units per liter)')], default='cells/mm^3 (cells per cubmic millimeter)', max_length=100, null=True),
        ),
    ]
