# Generated by Django 3.1.7 on 2022-04-04 02:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0008_auto_20220330_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallabcheck',
            name='due',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 16, 2, 24, 59, 531476, tzinfo=utc), help_text='When is this lab check due?'),
        ),
        migrations.AlterField(
            model_name='labcheck',
            name='due',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 16, 2, 24, 59, 531476, tzinfo=utc), help_text='When is this lab check due?'),
        ),
    ]
