# Generated by Django 3.1.7 on 2021-08-18 06:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0008_auto_20210624_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alt',
            name='date_drawn',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='What day was this lab drawn?', null=True),
        ),
        migrations.AlterField(
            model_name='ast',
            name='date_drawn',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='What day was this lab drawn?', null=True),
        ),
        migrations.AlterField(
            model_name='creatinine',
            name='date_drawn',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='What day was this lab drawn?', null=True),
        ),
        migrations.AlterField(
            model_name='hemoglobin',
            name='date_drawn',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='What day was this lab drawn?', null=True),
        ),
        migrations.AlterField(
            model_name='platelet',
            name='date_drawn',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='What day was this lab drawn?', null=True),
        ),
        migrations.AlterField(
            model_name='urate',
            name='date_drawn',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='What day was this lab drawn?', null=True),
        ),
        migrations.AlterField(
            model_name='urate',
            name='value',
            field=models.DecimalField(decimal_places=1, default=6.7, help_text='Enter the uric acid', max_digits=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wbc',
            name='date_drawn',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='What day was this lab drawn?', null=True),
        ),
    ]
