# Generated by Django 3.1.7 on 2022-01-18 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0008_auto_20220118_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='labcheck',
            name='abnormal_labcheck',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='lab.labcheck'),
        ),
    ]
