# Generated by Django 3.1.7 on 2022-01-01 20:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ultplan', '0003_ultplan_dose_adjustment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lab', '0009_auto_20211227_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alt',
            name='ultaid',
        ),
        migrations.RemoveField(
            model_name='ast',
            name='ultaid',
        ),
        migrations.RemoveField(
            model_name='creatinine',
            name='ultaid',
        ),
        migrations.RemoveField(
            model_name='hemoglobin',
            name='ultaid',
        ),
        migrations.RemoveField(
            model_name='platelet',
            name='ultaid',
        ),
        migrations.RemoveField(
            model_name='urate',
            name='ultaid',
        ),
        migrations.RemoveField(
            model_name='wbc',
            name='ultaid',
        ),
        migrations.CreateModel(
            name='LabCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('due', models.DateField(default=datetime.datetime(2022, 2, 12, 20, 21, 38, 862914, tzinfo=utc), help_text='When is this lab check due?')),
                ('completed', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Is this lab check completed?')),
                ('alt', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='lab.alt')),
                ('ast', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='lab.ast')),
                ('creatinine', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='lab.creatinine')),
                ('hemoglobin', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='lab.hemoglobin')),
                ('platelet', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='lab.platelet')),
                ('ultplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ultplan.ultplan')),
                ('urate', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='lab.urate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wbc', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='lab.wbc')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
