# Generated by Django 3.1.7 on 2022-01-02 04:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0010_auto_20220101_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labcheck',
            name='due',
            field=models.DateField(default=datetime.datetime(2022, 2, 13, 4, 18, 5, 55996, tzinfo=utc), help_text='When is this lab check due?'),
        ),
    ]
