# Generated by Django 3.1.7 on 2022-01-02 16:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0011_auto_20220102_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labcheck',
            old_name='completed_data',
            new_name='completed_date',
        ),
        migrations.AlterField(
            model_name='labcheck',
            name='due',
            field=models.DateField(default=datetime.datetime(2022, 2, 13, 16, 3, 52, 717680, tzinfo=utc), help_text='When is this lab check due?'),
        ),
    ]
