# Generated by Django 3.1.7 on 2022-01-02 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0012_auto_20220102_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labcheck',
            name='due',
            field=models.DateField(default=datetime.datetime(2022, 2, 13, 16, 58, 12, 725477), help_text='When is this lab check due?'),
        ),
    ]
