# Generated by Django 3.1.7 on 2022-01-02 20:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0013_auto_20220102_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labcheck',
            name='due',
            field=models.DateField(default=datetime.date(2022, 2, 13), help_text='When is this lab check due?'),
        ),
    ]
