# Generated by Django 3.1.7 on 2022-01-03 00:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0014_auto_20220102_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labcheck',
            name='due',
            field=models.DateField(default=datetime.date(2022, 2, 14), help_text='When is this lab check due?'),
        ),
    ]
