# Generated by Django 3.1.7 on 2022-01-03 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0015_auto_20220103_0011'),
        ('lab', '0011_auto_20220102_0418'),
    ]

    operations = [
    ]
