# Generated by Django 3.1.7 on 2022-01-04 00:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0016_merge_20220103_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labcheck',
            name='due',
            field=models.DateField(default=datetime.date(2022, 2, 15), help_text='When is this lab check due?'),
        ),
    ]
