# Generated by Django 3.1.7 on 2021-10-24 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ULTAid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('ckd', models.BooleanField(blank=True, choices=[('', '-----'), (True, 'Yes'), (False, 'No')], default='', help_text='Do you have CKD?', null=True, verbose_name='Do you have CKD?')),
                ('stage', models.IntegerField(blank=True, choices=[(1, 'I'), (2, 'Ii'), (3, 'Iii'), (4, 'Iv'), (5, 'V')], help_text="What <a href='https://www.kidney.org/sites/default/files/01-10-7278_HBG_CKD_Stages_Flyer_GFR.gif' target='_blank'>stage</a> is your CKD?? If you don't know, you probably aren't.", null=True, verbose_name='CKD stage')),
                ('dialysis', models.BooleanField(blank=True, choices=[('', '-----'), (True, 'Yes'), (False, 'No')], help_text="Are you on <a href='https://en.wikipedia.org/wiki/Hemodialysis' target='_blank'>dialysis</a>? If you don't know, you probably aren't.", null=True)),
                ('XOI_interactions', models.BooleanField(blank=True, choices=[('', '-----'), (True, 'Yes'), (False, 'No')], default='', help_text='Are you on azathioprine or 6-mercaptopurine?', null=True, verbose_name='Are you on azathioprine or 6-mercaptopurine?')),
                ('organ_transplant', models.BooleanField(blank=True, choices=[('', '-----'), (True, 'Yes'), (False, 'No')], default='', help_text='Have you had an organ transplant?', null=True, verbose_name='Have you had an organ transplant?')),
                ('allopurinol_hypersensitivity', models.BooleanField(blank=True, choices=[('', '-----'), (True, 'Yes'), (False, 'No')], help_text="Have you ever had a <a href='https://www.nhs.uk/medicines/allopurinol/#:~:text=to%20avoid%20dehydration.-,Serious%20side%20effects,-Skin%20rashes' target='_blank'>drug-reaction to allopurinol</a>?", null=True)),
                ('febuxostat_hypersensitivity', models.BooleanField(blank=True, choices=[('', '-----'), (True, 'Yes'), (False, 'No')], help_text="Have you ever had a <a href='https://www.rheumatology.org/I-Am-A/Patient-Caregiver/Treatments/Febuxostat-Uloric#:~:text=Side%20Effects,not%20be%20stopped.' target='_blank'>drug-reaction to febuxostat</a>?", null=True)),
                ('MACE', models.BooleanField(blank=True, choices=[('', '-----'), (True, 'Yes'), (False, 'No')], help_text="Have you ever had <a href='https://en.wikipedia.org/wiki/Myocardial_infarction' target='_blank'>heart attack</a> or <a href='https://en.wikipedia.org/wiki/Stroke' target='_blank'>stroke</a>?", null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
