# Generated by Django 3.1.7 on 2022-02-03 21:42

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ult', '0001_initial'),
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ULTAid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('need', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], help_text="Do you need <a href='/ult/create/' target='_blank'>ULT</a>?", null=True, verbose_name='Need ULT?')),
                ('want', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], help_text='Will you take daily medication to get rid of your gout?', null=True, verbose_name='Want ULT?')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('XOI_interactions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.xoiinteractions')),
                ('allopurinol_hypersensitivity', models.ForeignKey(blank=True, help_text="Have you ever had a <a href='https://www.nhs.uk/medicines/allopurinol/#:~:text=to%20avoid%20dehydration.-,Serious%20side%20effects,-Skin%20rashes' target='_blank'>drug-reaction to allopurinol</a>?", null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.allopurinolhypersensitivity')),
                ('ckd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.ckd')),
                ('erosions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.erosions')),
                ('febuxostat_hypersensitivity', models.ForeignKey(blank=True, help_text="Have you ever had a <a href='https://www.rheumatology.org/I-Am-A/Patient-Caregiver/Treatments/Febuxostat-Uloric#:~:text=Side%20Effects,not%20be%20stopped.' target='_blank'>drug-reaction to febuxostat</a>?", null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.febuxostathypersensitivity')),
                ('heartattack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.heartattack')),
                ('organ_transplant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.organtransplant')),
                ('stroke', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.stroke')),
                ('tophi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.tophi')),
                ('ult', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ult.ult')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
