# Generated by Django 3.1.7 on 2022-02-19 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ult', '0002_auto_20220219_1527'),
        ('history', '0002_auto_20220219_1527'),
        ('ultplan', '0001_initial'),
        ('ultaid', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ultaid',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ultaid_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ultaid',
            name='erosions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.erosions'),
        ),
        migrations.AddField(
            model_name='ultaid',
            name='febuxostat_hypersensitivity',
            field=models.ForeignKey(blank=True, help_text="Have you ever had a <a href='https://www.rheumatology.org/I-Am-A/Patient-Caregiver/Treatments/Febuxostat-Uloric#:~:text=Side%20Effects,not%20be%20stopped.' target='_blank'>drug-reaction to febuxostat</a>?", null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.febuxostathypersensitivity'),
        ),
        migrations.AddField(
            model_name='ultaid',
            name='heartattack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.heartattack'),
        ),
        migrations.AddField(
            model_name='ultaid',
            name='organ_transplant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.organtransplant'),
        ),
        migrations.AddField(
            model_name='ultaid',
            name='stroke',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.stroke'),
        ),
        migrations.AddField(
            model_name='ultaid',
            name='tophi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.tophi'),
        ),
        migrations.AddField(
            model_name='ultaid',
            name='ult',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ult.ult'),
        ),
        migrations.AddField(
            model_name='ultaid',
            name='ultplan',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ultplan.ultplan'),
        ),
        migrations.AddField(
            model_name='ultaid',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
