# Generated by Django 3.1.7 on 2021-11-20 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultaid', '0002_auto_20211120_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ultaid',
            name='need',
            field=models.BooleanField(blank=True, choices=[('', '-----'), (True, 'Yes'), (False, 'No')], default='', help_text="Do you need <a href='/ult/create/' target='_blank'>ULT</a>?", null=True, verbose_name='Need ULT?'),
        ),
    ]
