# Generated by Django 3.1.7 on 2021-12-19 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultaid', '0005_auto_20211211_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='ultaid',
            name='titrating',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], help_text='Is this ULTAid plan in the process of medication titration?', null=True, verbose_name='Titrating?'),
        ),
    ]
