# Generated by Django 3.1.7 on 2021-12-28 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ultplan', '0002_auto_20211228_0259'),
        ('ultaid', '0007_remove_ultaid_titrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='ultaid',
            name='ultplan',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ultplan.ultplan'),
        ),
    ]
