# Generated by Django 3.1.7 on 2021-12-28 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0007_angina'),
        ('ult', '0001_initial'),
        ('ultaid', '0008_ultaid_ultplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='ultaid',
            name='erosions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.erosions'),
        ),
        migrations.AddField(
            model_name='ultaid',
            name='tophi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.tophi'),
        ),
        migrations.AddField(
            model_name='ultaid',
            name='ult',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ult.ult'),
        ),
    ]
