# Generated by Django 3.1.7 on 2021-12-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultaid', '0009_auto_20211228_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ultaid',
            name='need',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], help_text="Do you need <a href='/ult/create/' target='_blank'>ULT</a>?", null=True, verbose_name='Need ULT?'),
        ),
        migrations.AlterField(
            model_name='ultaid',
            name='want',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], help_text='Will you take daily medication to get rid of your gout?', null=True, verbose_name='Want ULT?'),
        ),
    ]
