# Generated by Django 3.1.7 on 2022-02-01 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provider',
            options={'permissions': [('can_make_patient', 'Can make patient')]},
        ),
    ]
