# Generated by Django 3.1.7 on 2022-02-01 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220201_0310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provider',
            options={'permissions': [('can_add_patient', 'Can Add Patient')]},
        ),
    ]
