# Generated by Django 3.1.7 on 2021-04-26 14:37

import django.contrib.auth.models
from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210323_1705'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('treatments', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
