# Generated by Django 3.1.7 on 2022-02-01 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220201_0315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'permissions': [('can_add_patient', 'Can Add Patient')]},
        ),
        migrations.AlterModelOptions(
            name='provider',
            options={},
        ),
    ]
