# Generated by Django 3.1.7 on 2022-02-01 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220201_1550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provider',
            options={'permissions': [('can_add_patient', 'Can Add Patient'), ('can_edit_patient', 'Can Edit Patient'), ('can_delete_patient', 'Can Delete Patient'), ('can_view_patient', 'Can View Patient')]},
        ),
    ]
