# Generated by Django 3.1.7 on 2021-12-21 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ultaid', '0007_remove_ultaid_titrating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ppxaid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ULTPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('goal_urate', models.FloatField(default=6.0, help_text='What is the goal uric acid?', verbose_name='Goal Uric Acid')),
                ('lab_interval', models.IntegerField(default=42, help_text='How frequently are labs required to be checked?', verbose_name='Lab Check Interval')),
                ('titrating', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, help_text='Is this ULTPlan still in the titration phase?')),
                ('last_titration', models.DateField(blank=True, help_text='When was the ULT dose last titrated?', null=True)),
                ('ppxaid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ppxaid.ppxaid')),
                ('ultaid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ultaid.ultaid')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
