# Generated by Django 3.1.7 on 2021-12-28 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ultplan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ultplan',
            name='ppxaid',
        ),
        migrations.RemoveField(
            model_name='ultplan',
            name='ultaid',
        ),
    ]
