# Generated by Django 3.1.7 on 2022-01-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultplan', '0002_auto_20211228_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='ultplan',
            name='dose_adjustment',
            field=models.IntegerField(default=100, help_text='What is the dose adjustment for each titration for the chosen medication?', verbose_name='Dose Adjustment'),
        ),
    ]
