# Generated by Django 3.1.7 on 2022-02-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultplan', '0002_auto_20220214_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalultplan',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ultplan',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
    ]
