# Generated by Django 3.1.7 on 2022-02-01 03:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultplan', '0002_auto_20220129_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalultplan',
            name='delinquent_lab_interval',
            field=models.DurationField(default=datetime.timedelta(days=21), help_text='How long will you wait before declaring a LabCheck delinquent and pausing the ULTPlan?', verbose_name='Delinquent Lab Check Interval'),
        ),
        migrations.AddField(
            model_name='ultplan',
            name='delinquent_lab_interval',
            field=models.DurationField(default=datetime.timedelta(days=21), help_text='How long will you wait before declaring a LabCheck delinquent and pausing the ULTPlan?', verbose_name='Delinquent Lab Check Interval'),
        ),
    ]
