# Generated by Django 3.1.7 on 2021-09-14 02:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='XOIInteractions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('date', models.DateField(blank=True, help_text='When did you start this medication?', null=True)),
                ('value', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], help_text='Are you on any medications that could interact with allopurinol or febuxostat? (6-mercaptopurine, azathioprine)?', null=True)),
                ('six_mp', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], help_text='Are you on 6-mercaptopurine / 6-MP?', null=True)),
                ('azathioprine', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], help_text='Are you on azathioprine / Imuran?', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganTransplant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('value', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], help_text='Do you have history?', null=True)),
                ('organ', multiselectfield.db.fields.MultiSelectField(choices=[('Heart', 'Heart'), ('Kidney', 'Kidney'), ('Liver', 'Liver'), ('Lung', 'Lung'), ('Pancreas', 'Pancreas'), ('Face', 'Face')], default=True, help_text='Which organ did you have transplanted?', max_length=37, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ColchicineInteractions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('date', models.DateField(blank=True, help_text='When did you start this medication?', null=True)),
                ('value', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], help_text='Are you on any medications that could interact with colchicine? (clarithromycin, simvastatin, diltiazem)', null=True)),
                ('clarithromycin', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], help_text='Are you on clarithromycin', null=True)),
                ('simvastatin', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], help_text='Are you on simvastatin?', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
