# Generated by Django 3.1.7 on 2021-10-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_auto_20211022_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diabetes',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, 'One'), (2, 'Two')], help_text='Do you have type I or type II diabetes?', null=True, verbose_name='Type 1 or type 2 diabetes?'),
        ),
    ]
