# Generated by Django 3.1.7 on 2021-11-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_auto_20211105_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anticoagulation',
            name='value',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], help_text="Are you on <a href='https://en.wikipedia.org/wiki/Anticoagulant' target='_blank'>anticoagulation</a> (blood thinners)</a>)?", null=True, verbose_name='Anticoagulation'),
        ),
        migrations.AlterField(
            model_name='bleed',
            name='value',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], help_text="Have you ever had a major bleed (<a href='https://en.wikipedia.org/wiki/Gastrointestinal_bleeding' target='_blank'>gastrointestinal bleeding</a> (GI), <a href='https://en.wikipedia.org/wiki/Peptic_ulcer_disease' target='_blank'>peptic ulcer disease</a>, brain (CNS))", null=True, verbose_name='major bleed'),
        ),
        migrations.AlterField(
            model_name='colchicineinteractions',
            name='value',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], help_text="Are you on any medications that could <a href='https://www.rxlist.com/colchicine-drug.htm#interactions' target='_blank'>interact</a> with colchicine? (common ones are simvastatin, atorvastatin, oral <a href='https://en.wikipedia.org/wiki/Antifungal' target='_blank'>antifungals</a>)?", null=True, verbose_name='Colchicine Medication Interactions'),
        ),
    ]
