# Generated by Django 3.1.7 on 2022-03-06 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_auto_20220306_0017'),
        ('history', '0002_auto_20220302_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anemia',
            name='baseline',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.baselinehemoglobin'),
        ),
        migrations.AlterField(
            model_name='historicalanemia',
            name='baseline',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lab.baselinehemoglobin'),
        ),
        migrations.AlterField(
            model_name='historicalleukocytosis',
            name='baseline',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lab.baselinewbc'),
        ),
        migrations.AlterField(
            model_name='historicalleukopenia',
            name='baseline',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lab.baselinewbc'),
        ),
        migrations.AlterField(
            model_name='historicalpolycythemia',
            name='baseline',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lab.baselinehemoglobin'),
        ),
        migrations.AlterField(
            model_name='historicalthrombocytopenia',
            name='baseline',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lab.baselineplatelet'),
        ),
        migrations.AlterField(
            model_name='historicalthrombocytosis',
            name='baseline',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lab.baselineplatelet'),
        ),
        migrations.AlterField(
            model_name='historicaltransaminitis',
            name='baseline_alt',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lab.baselinealt'),
        ),
        migrations.AlterField(
            model_name='historicaltransaminitis',
            name='baseline_ast',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lab.baselineast'),
        ),
        migrations.AlterField(
            model_name='leukocytosis',
            name='baseline',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.baselinewbc'),
        ),
        migrations.AlterField(
            model_name='leukopenia',
            name='baseline',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.baselinewbc'),
        ),
        migrations.AlterField(
            model_name='polycythemia',
            name='baseline',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.baselinehemoglobin'),
        ),
        migrations.AlterField(
            model_name='thrombocytopenia',
            name='baseline',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.baselineplatelet'),
        ),
        migrations.AlterField(
            model_name='thrombocytosis',
            name='baseline',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.baselineplatelet'),
        ),
        migrations.AlterField(
            model_name='transaminitis',
            name='baseline_alt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.baselinealt'),
        ),
        migrations.AlterField(
            model_name='transaminitis',
            name='baseline_ast',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.baselineast'),
        ),
    ]
