# Generated by Django 3.1.7 on 2021-11-15 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_auto_20211110_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ckd',
            name='stage',
            field=models.IntegerField(choices=[(1, 'I'), (2, 'II'), (3, 'III'), (4, 'IV'), (5, 'V')], default=None, help_text="What <a href='https://www.kidney.org/sites/default/files/01-10-7278_HBG_CKD_Stages_Flyer_GFR.gif' target='_blank'>stage</a> is your CKD??", null=True, verbose_name='CKD stage'),
        ),
    ]
