# Generated by Django 3.1.7 on 2021-09-15 21:36

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_auto_20210915_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chf',
            name='systolic',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], help_text="Do you have systolic (reduced ejection fraction) heart faliure? If you don't know, skip this or leave it blank.", null=True, verbose_name='Systolic or diastolic heart failure'),
        ),
        migrations.AlterField(
            model_name='chf',
            name='value',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], help_text='Do you have CHF?', null=True, verbose_name='Congestive heart failure (CHF)'),
        ),
        migrations.AlterField(
            model_name='ckd',
            name='stage',
            field=models.IntegerField(blank=True, choices=[(1, 'I'), (2, 'Ii'), (3, 'Iii'), (4, 'Iv'), (5, 'V')], help_text="What stage is your CKD? If you don't know, skip this or leave it blank.", null=True, verbose_name='CKD stage'),
        ),
        migrations.AlterField(
            model_name='diabetes',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, 'I'), (2, 'Ii')], help_text='Do you have type I or type II diabetes?', null=True, verbose_name='Type 1 or type 2 diabetes?'),
        ),
        migrations.AlterField(
            model_name='diabetes',
            name='value',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], help_text='Do you have diabetes?', null=True, verbose_name='Diabetes'),
        ),
        migrations.AlterField(
            model_name='hypertension',
            name='medication',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], help_text='Are you on medications for high blood pressure?', null=True, verbose_name='Blood pressure medications'),
        ),
        migrations.AlterField(
            model_name='hypertension',
            name='value',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], help_text='Do you have hypertension?', null=True, verbose_name='Hypertension (high blood pressure)'),
        ),
        migrations.AlterField(
            model_name='organtransplant',
            name='organ',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Heart', 'Heart'), ('Kidney', 'Kidney'), ('Liver', 'Liver'), ('Lung', 'Lung'), ('Pancreas', 'Pancreas'), ('Face', 'Face')], default=True, help_text='Which organ did you have transplanted?', max_length=37, null=True, verbose_name='Organ(s) transplanted'),
        ),
        migrations.AlterField(
            model_name='organtransplant',
            name='value',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], help_text='Do you have organ transplant?', null=True, verbose_name='Organ transplant'),
        ),
        migrations.AlterField(
            model_name='uratekidneystones',
            name='value',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], help_text='Do you have a history of urate kidney stones?', null=True, verbose_name='Urate Kidney Stones'),
        ),
    ]
