# Generated by Django 3.1.7 on 2021-10-27 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_auto_20211022_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chf',
            name='systolic',
            field=models.BooleanField(blank=True, choices=[(True, 'Systolic'), (False, 'Diastolic')], help_text="Do you have systolic (reduced <a href='https://en.wikipedia.org/wiki/Ejection_fraction' target='_blank'>ejection fraction</a>) heart failure? If you don't know, skip this or leave it blank.", null=True, verbose_name='Systolic or diastolic heart failure'),
        ),
        migrations.AlterField(
            model_name='chf',
            name='value',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], help_text="Do you have CHF (<a href='https://en.wikipedia.org/wiki/Heart_failure' target='_blank'>congestive heart failure</a>)? If you don't know, skip this or leave it blank.", null=True, verbose_name='Congestive Heart Failure (CHF)'),
        ),
        migrations.AlterField(
            model_name='ckd',
            name='dialysis',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], help_text="Are you on <a href='https://en.wikipedia.org/wiki/Hemodialysis' target='_blank'>dialysis</a>? If you don't know, you probably aren't.", null=True),
        ),
        migrations.AlterField(
            model_name='ckd',
            name='stage',
            field=models.IntegerField(blank=True, choices=[(1, 'I'), (2, 'Ii'), (3, 'Iii'), (4, 'Iv'), (5, 'V')], help_text="What <a href='https://www.kidney.org/sites/default/files/01-10-7278_HBG_CKD_Stages_Flyer_GFR.gif' target='_blank'>stage</a> is your CKD?? If you don't know, you probably aren't.", null=True, verbose_name='CKD stage'),
        ),
        migrations.AlterField(
            model_name='ckd',
            name='value',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], help_text="Do you have CKD (<a href='https://en.wikipedia.org/wiki/Chronic_kidney_disease' target='_blank'>chronic kidney disease</a>)? If you don't know, skip this or leave it blank.", null=True, verbose_name='Chronic Kidney Disease (CKD)'),
        ),
        migrations.AlterField(
            model_name='diabetes',
            name='insulin',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], help_text="Are you on <a href='https://en.wikipedia.org/wiki/Insulin' target='_blank'>kidney stones</a>? If you don't know, skip this or leave it blank.", null=True),
        ),
        migrations.AlterField(
            model_name='diabetes',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, 'One'), (2, 'Two')], help_text="Do you have <a href='https://en.wikipedia.org/wiki/Type_1_diabetes' target='_blank'>type I</a> or <a href='https://en.wikipedia.org/wiki/Type_2_diabetes' target='_blank'>type II</a> diabetes? If you don't know, skip this or leave it blank.", null=True, verbose_name='Type 1 or type 2 diabetes?'),
        ),
        migrations.AlterField(
            model_name='diabetes',
            name='value',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], help_text="Do you have <a href='https://en.wikipedia.org/wiki/Diabetes' target='_blank'>diabetes</a>? If you don't know, skip this or leave it blank.", null=True, verbose_name='Diabetes'),
        ),
        migrations.AlterField(
            model_name='hypertension',
            name='medication',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], help_text="Are you on <a href='https://www.heart.org/en/health-topics/high-blood-pressure/changes-you-can-make-to-manage-high-blood-pressure/types-of-blood-pressure-medications' target='_blank'>medications</a> for high blood pressure? If you don't know, skip this or leave it blank.", null=True, verbose_name='Blood pressure medications'),
        ),
        migrations.AlterField(
            model_name='hypertension',
            name='value',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], help_text="Do you have <a href='https://en.wikipedia.org/wiki/Hypertension' target='_blank'>hypertension</a>?", null=True, verbose_name='Hypertension (high blood pressure)'),
        ),
        migrations.AlterField(
            model_name='organtransplant',
            name='value',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], help_text='Have you had an organ transplant?', null=True, verbose_name='Organ transplant'),
        ),
        migrations.AlterField(
            model_name='uratekidneystones',
            name='value',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], help_text="Have you had urate <a href='https://en.wikipedia.org/wiki/Kidney_stone_disease' target='_blank'>kidney stones</a>? If you don't know, skip this or leave it blank.", null=True, verbose_name='Urate Kidney Stones'),
        ),
    ]
