# Generated by Django 3.1.7 on 2022-03-06 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_auto_20220306_0017'),
        ('history', '0003_auto_20220306_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ckd',
            name='baseline',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.baselinecreatinine'),
        ),
        migrations.AlterField(
            model_name='historicalckd',
            name='baseline',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lab.baselinecreatinine'),
        ),
    ]
