# Generated by Django 3.1.7 on 2021-09-19 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('history', '0004_auto_20210915_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bleed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('value', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], help_text='Do you have history?', null=True)),
                ('number', models.IntegerField(blank=True, default=1, help_text='How many have you had?', null=True)),
                ('date', models.DateField(blank=True, help_text='When was it? The most recent if multiple.', null=True)),
                ('GIB', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], help_text='Have you had a gastrointestinal bleed?', null=True)),
                ('GIB_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='When was the last time you has a gastrointestinal bleed?', null=True)),
                ('CNS', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], help_text='Have you had an intracranial bleed?', null=True)),
                ('CNS_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='When was the last time you had an intracranial bleed?', null=True)),
                ('transfusion', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], help_text='Did you require a transfusion?', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fructose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('value', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], help_text='Do you eat a lot of fructose such as the sugar found in soda/pop, processed candies, or juices?', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shellfish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('value', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], help_text='Do you eat a lot of shellfish?', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='anticoagulation',
            name='dabigatran',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], help_text='Are you on dabigatran / Pradaxa?', null=True),
        ),
        migrations.AddField(
            model_name='anticoagulation',
            name='enoxaparin',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], help_text='Are you on enoxaparin / Lovenox?', null=True),
        ),
        migrations.AddField(
            model_name='heartattack',
            name='cabg_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='When did you have a bypass?', null=True),
        ),
        migrations.AddField(
            model_name='heartattack',
            name='stent_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='When was the last time you has a stent?', null=True),
        ),
        migrations.DeleteModel(
            name='BleedingEvent',
        ),
    ]
