# Generated by Django 3.1.7 on 2021-10-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_auto_20211027_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bleed',
            name='GIB',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], help_text="Have you ever had <a href='https://en.wikipedia.org/wiki/Gastrointestinal_bleeding' target='_blank'>gastrointestinal bleeding</a>? If you don't know, skip this or leave it blank.", null=True),
        ),
        migrations.AlterField(
            model_name='bleed',
            name='value',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], help_text='Have you ever had a major bleed?', null=True, verbose_name='major bleed'),
        ),
        migrations.AlterField(
            model_name='heartattack',
            name='cabg',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], help_text="Have you had <a href='https://en.wikipedia.org/wiki/Coronary_artery_bypass_surgery' target='_blank'>bypass</a>? If you don't know, skip this or leave it blank.", null=True, verbose_name='cabg'),
        ),
        migrations.AlterField(
            model_name='heartattack',
            name='stent',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], help_text="Have you had one or more <a href='https://en.wikipedia.org/wiki/Stent' target='_blank'>stent</a> placed? If you don't know, skip this or leave it blank.", null=True, verbose_name='stent'),
        ),
        migrations.AlterField(
            model_name='heartattack',
            name='value',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], help_text="Have you ever had <a href='https://en.wikipedia.org/wiki/Myocardial_infarction' target='_blank'>heart attack</a>? If you don't know, skip this or leave it blank.", null=True, verbose_name='heart attack'),
        ),
        migrations.AlterField(
            model_name='stroke',
            name='value',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], help_text="Have you ever had <a href='https://en.wikipedia.org/wiki/Stroke' target='_blank'>stroke</a>? If you don't know, skip this or leave it blank.", null=True, verbose_name='stroke'),
        ),
    ]
