# Generated by Django 3.1.7 on 2022-03-10 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_auto_20220306_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alcohol',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('Behind the scenes', 'Behind the scenes'), ('FlareAid', 'FlareAid'), ('Flare', 'Flare'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='allopurinolhypersensitivity',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('Behind the scenes', 'Behind the scenes'), ('FlareAid', 'FlareAid'), ('Flare', 'Flare'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='anemia',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('Behind the scenes', 'Behind the scenes'), ('FlareAid', 'FlareAid'), ('Flare', 'Flare'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='angina',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('Behind the scenes', 'Behind the scenes'), ('FlareAid', 'FlareAid'), ('Flare', 'Flare'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='anticoagulation',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('Behind the scenes', 'Behind the scenes'), ('FlareAid', 'FlareAid'), ('Flare', 'Flare'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='bleed',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('Behind the scenes', 'Behind the scenes'), ('FlareAid', 'FlareAid'), ('Flare', 'Flare'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='chf',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('Behind the scenes', 'Behind the scenes'), ('FlareAid', 'FlareAid'), ('Flare', 'Flare'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='ckd',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('Behind the scenes', 'Behind the scenes'), ('FlareAid', 'FlareAid'), ('Flare', 'Flare'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='colchicineinteractions',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('Behind the scenes', 'Behind the scenes'), ('FlareAid', 'FlareAid'), ('Flare', 'Flare'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='cyclosporine',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('Behind the scenes', 'Behind the scenes'), ('FlareAid', 'FlareAid'), ('Flare', 'Flare'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='diabetes',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('Behind the scenes', 'Behind the scenes'), ('FlareAid', 'FlareAid'), ('Flare', 'Flare'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='diuretics',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('Behind the scenes', 'Behind the scenes'), ('FlareAid', 'FlareAid'), ('Flare', 'Flare'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='erosions',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('Behind the scenes', 'Behind the scenes'), ('FlareAid', 'FlareAid'), ('Flare', 'Flare'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='febuxostathypersensitivity',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('Behind the scenes', 'Behind the scenes'), ('FlareAid', 'FlareAid'), ('Flare', 'Flare'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='fructose',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('Behind the scenes', 'Behind the scenes'), ('FlareAid', 'FlareAid'), ('Flare', 'Flare'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='gout',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('Behind the scenes', 'Behind the scenes'), ('FlareAid', 'FlareAid'), ('Flare', 'Flare'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='heartattack',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('Behind the scenes', 'Behind the scenes'), ('FlareAid', 'FlareAid'), ('Flare', 'Flare'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='historicalalcohol',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('Behind the scenes', 'Behind the scenes'), ('FlareAid', 'FlareAid'), ('Flare', 'Flare'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='historicalallopurinolhypersensitivity',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('Behind the scenes', 'Behind the scenes'), ('FlareAid', 'FlareAid'), ('Flare', 'Flare'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='historicalanemia',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('Behind the scenes', 'Behind the scenes'), ('FlareAid', 'FlareAid'), ('Flare', 'Flare'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='historicalangina',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('Behind the scenes', 'Behind the scenes'), ('FlareAid', 'FlareAid'), ('Flare', 'Flare'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='historicalanticoagulation',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('Behind the scenes', 'Behind the scenes'), ('FlareAid', 'FlareAid'), ('Flare', 'Flare'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbleed',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('Behind the scenes', 'Behind the scenes'), ('FlareAid', 'FlareAid'), ('Flare', 'Flare'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='historicalchf',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('Behind the scenes', 'Behind the scenes'), ('FlareAid', 'FlareAid'), ('Flare', 'Flare'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='historicalckd',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('Behind the scenes', 'Behind the scenes'), ('FlareAid', 'FlareAid'), ('Flare', 'Flare'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcolchicineinteractions',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('Behind the scenes', 'Behind the scenes'), ('FlareAid', 'FlareAid'), ('Flare', 'Flare'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcyclosporine',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('Behind the scenes', 'Behind the scenes'), ('FlareAid', 'FlareAid'), ('Flare', 'Flare'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldiabetes',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('Behind the scenes', 'Behind the scenes'), ('FlareAid', 'FlareAid'), ('Flare', 'Flare'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldiuretics',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('Behind the scenes', 'Behind the scenes'), ('FlareAid', 'FlareAid'), ('Flare', 'Flare'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='historicalerosions',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('Behind the scenes', 'Behind the scenes'), ('FlareAid', 'FlareAid'), ('Flare', 'Flare'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfebuxostathypersensitivity',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('Behind the scenes', 'Behind the scenes'), ('FlareAid', 'FlareAid'), ('Flare', 'Flare'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfructose',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('Behind the scenes', 'Behind the scenes'), ('FlareAid', 'FlareAid'), ('Flare', 'Flare'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='historicalgout',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('Behind the scenes', 'Behind the scenes'), ('FlareAid', 'FlareAid'), ('Flare', 'Flare'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='historicalheartattack',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('Behind the scenes', 'Behind the scenes'), ('FlareAid', 'FlareAid'), ('Flare', 'Flare'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='historicalhypertension',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('Behind the scenes', 'Behind the scenes'), ('FlareAid', 'FlareAid'), ('Flare', 'Flare'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='historicalhyperuricemia',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('Behind the scenes', 'Behind the scenes'), ('FlareAid', 'FlareAid'), ('Flare', 'Flare'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='historicalibd',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('Behind the scenes', 'Behind the scenes'), ('FlareAid', 'FlareAid'), ('Flare', 'Flare'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='historicalleukocytosis',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('Behind the scenes', 'Behind the scenes'), ('FlareAid', 'FlareAid'), ('Flare', 'Flare'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='historicalleukopenia',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('Behind the scenes', 'Behind the scenes'), ('FlareAid', 'FlareAid'), ('Flare', 'Flare'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorgantransplant',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('Behind the scenes', 'Behind the scenes'), ('FlareAid', 'FlareAid'), ('Flare', 'Flare'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='historicalosteoporosis',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('Behind the scenes', 'Behind the scenes'), ('FlareAid', 'FlareAid'), ('Flare', 'Flare'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpolycythemia',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('Behind the scenes', 'Behind the scenes'), ('FlareAid', 'FlareAid'), ('Flare', 'Flare'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpvd',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('Behind the scenes', 'Behind the scenes'), ('FlareAid', 'FlareAid'), ('Flare', 'Flare'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='historicalshellfish',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('Behind the scenes', 'Behind the scenes'), ('FlareAid', 'FlareAid'), ('Flare', 'Flare'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstroke',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('Behind the scenes', 'Behind the scenes'), ('FlareAid', 'FlareAid'), ('Flare', 'Flare'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='historicalthrombocytopenia',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('Behind the scenes', 'Behind the scenes'), ('FlareAid', 'FlareAid'), ('Flare', 'Flare'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='historicalthrombocytosis',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('Behind the scenes', 'Behind the scenes'), ('FlareAid', 'FlareAid'), ('Flare', 'Flare'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltophi',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('Behind the scenes', 'Behind the scenes'), ('FlareAid', 'FlareAid'), ('Flare', 'Flare'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransaminitis',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('Behind the scenes', 'Behind the scenes'), ('FlareAid', 'FlareAid'), ('Flare', 'Flare'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='historicaluratekidneystones',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('Behind the scenes', 'Behind the scenes'), ('FlareAid', 'FlareAid'), ('Flare', 'Flare'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='historicalxoiinteractions',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('Behind the scenes', 'Behind the scenes'), ('FlareAid', 'FlareAid'), ('Flare', 'Flare'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='hypertension',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('Behind the scenes', 'Behind the scenes'), ('FlareAid', 'FlareAid'), ('Flare', 'Flare'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='hyperuricemia',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('Behind the scenes', 'Behind the scenes'), ('FlareAid', 'FlareAid'), ('Flare', 'Flare'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='ibd',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('Behind the scenes', 'Behind the scenes'), ('FlareAid', 'FlareAid'), ('Flare', 'Flare'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='leukocytosis',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('Behind the scenes', 'Behind the scenes'), ('FlareAid', 'FlareAid'), ('Flare', 'Flare'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='leukopenia',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('Behind the scenes', 'Behind the scenes'), ('FlareAid', 'FlareAid'), ('Flare', 'Flare'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='organtransplant',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('Behind the scenes', 'Behind the scenes'), ('FlareAid', 'FlareAid'), ('Flare', 'Flare'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='osteoporosis',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('Behind the scenes', 'Behind the scenes'), ('FlareAid', 'FlareAid'), ('Flare', 'Flare'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='polycythemia',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('Behind the scenes', 'Behind the scenes'), ('FlareAid', 'FlareAid'), ('Flare', 'Flare'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='pvd',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('Behind the scenes', 'Behind the scenes'), ('FlareAid', 'FlareAid'), ('Flare', 'Flare'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='shellfish',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('Behind the scenes', 'Behind the scenes'), ('FlareAid', 'FlareAid'), ('Flare', 'Flare'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='stroke',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('Behind the scenes', 'Behind the scenes'), ('FlareAid', 'FlareAid'), ('Flare', 'Flare'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='thrombocytopenia',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('Behind the scenes', 'Behind the scenes'), ('FlareAid', 'FlareAid'), ('Flare', 'Flare'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='thrombocytosis',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('Behind the scenes', 'Behind the scenes'), ('FlareAid', 'FlareAid'), ('Flare', 'Flare'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='tophi',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('Behind the scenes', 'Behind the scenes'), ('FlareAid', 'FlareAid'), ('Flare', 'Flare'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='transaminitis',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('Behind the scenes', 'Behind the scenes'), ('FlareAid', 'FlareAid'), ('Flare', 'Flare'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='uratekidneystones',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('Behind the scenes', 'Behind the scenes'), ('FlareAid', 'FlareAid'), ('Flare', 'Flare'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='xoiinteractions',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('Behind the scenes', 'Behind the scenes'), ('FlareAid', 'FlareAid'), ('Flare', 'Flare'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
    ]
