# Generated by Django 3.1.7 on 2021-09-19 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0005_auto_20210919_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alcohol',
            name='value',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], help_text='Do you have a history?', null=True),
        ),
        migrations.AlterField(
            model_name='bleed',
            name='value',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], help_text='Have you ever had a major bleed?', null=True, verbose_name='major bleed'),
        ),
        migrations.AlterField(
            model_name='cyclosporine',
            name='value',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], help_text='Do you have a history?', null=True),
        ),
        migrations.AlterField(
            model_name='diuretics',
            name='value',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], help_text='Do you have a history?', null=True),
        ),
        migrations.AlterField(
            model_name='heartattack',
            name='value',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], help_text='Have you ever had a heart attack?', null=True, verbose_name='heart attack'),
        ),
        migrations.AlterField(
            model_name='stroke',
            name='value',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], help_text='Have you ever had a stroke?', null=True, verbose_name='stroke'),
        ),
    ]
