# Generated by Django 3.1.7 on 2021-10-25 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0006_hyperuricemia'),
    ]

    operations = [
        migrations.AddField(
            model_name='alcohol',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('ContraindicationsProfile', 'ContraindicationsProfile'), ('FlareAid', 'FlareAid'), ('FlareDiagnosis', 'FlareDiagnosis'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='anticoagulation',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('ContraindicationsProfile', 'ContraindicationsProfile'), ('FlareAid', 'FlareAid'), ('FlareDiagnosis', 'FlareDiagnosis'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='bleed',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('ContraindicationsProfile', 'ContraindicationsProfile'), ('FlareAid', 'FlareAid'), ('FlareDiagnosis', 'FlareDiagnosis'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='chf',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('ContraindicationsProfile', 'ContraindicationsProfile'), ('FlareAid', 'FlareAid'), ('FlareDiagnosis', 'FlareDiagnosis'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='ckd',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('ContraindicationsProfile', 'ContraindicationsProfile'), ('FlareAid', 'FlareAid'), ('FlareDiagnosis', 'FlareDiagnosis'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='colchicineinteractions',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('ContraindicationsProfile', 'ContraindicationsProfile'), ('FlareAid', 'FlareAid'), ('FlareDiagnosis', 'FlareDiagnosis'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='cyclosporine',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('ContraindicationsProfile', 'ContraindicationsProfile'), ('FlareAid', 'FlareAid'), ('FlareDiagnosis', 'FlareDiagnosis'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='diabetes',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('ContraindicationsProfile', 'ContraindicationsProfile'), ('FlareAid', 'FlareAid'), ('FlareDiagnosis', 'FlareDiagnosis'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='diuretics',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('ContraindicationsProfile', 'ContraindicationsProfile'), ('FlareAid', 'FlareAid'), ('FlareDiagnosis', 'FlareDiagnosis'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='erosions',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('ContraindicationsProfile', 'ContraindicationsProfile'), ('FlareAid', 'FlareAid'), ('FlareDiagnosis', 'FlareDiagnosis'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='fructose',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('ContraindicationsProfile', 'ContraindicationsProfile'), ('FlareAid', 'FlareAid'), ('FlareDiagnosis', 'FlareDiagnosis'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='gout',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('ContraindicationsProfile', 'ContraindicationsProfile'), ('FlareAid', 'FlareAid'), ('FlareDiagnosis', 'FlareDiagnosis'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='heartattack',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('ContraindicationsProfile', 'ContraindicationsProfile'), ('FlareAid', 'FlareAid'), ('FlareDiagnosis', 'FlareDiagnosis'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='hypertension',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('ContraindicationsProfile', 'ContraindicationsProfile'), ('FlareAid', 'FlareAid'), ('FlareDiagnosis', 'FlareDiagnosis'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='hyperuricemia',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('ContraindicationsProfile', 'ContraindicationsProfile'), ('FlareAid', 'FlareAid'), ('FlareDiagnosis', 'FlareDiagnosis'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='organtransplant',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('ContraindicationsProfile', 'ContraindicationsProfile'), ('FlareAid', 'FlareAid'), ('FlareDiagnosis', 'FlareDiagnosis'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='shellfish',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('ContraindicationsProfile', 'ContraindicationsProfile'), ('FlareAid', 'FlareAid'), ('FlareDiagnosis', 'FlareDiagnosis'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='stroke',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('ContraindicationsProfile', 'ContraindicationsProfile'), ('FlareAid', 'FlareAid'), ('FlareDiagnosis', 'FlareDiagnosis'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='tophi',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('ContraindicationsProfile', 'ContraindicationsProfile'), ('FlareAid', 'FlareAid'), ('FlareDiagnosis', 'FlareDiagnosis'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='uratekidneystones',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('ContraindicationsProfile', 'ContraindicationsProfile'), ('FlareAid', 'FlareAid'), ('FlareDiagnosis', 'FlareDiagnosis'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='xoiinteractions',
            name='last_modified',
            field=models.CharField(blank=True, choices=[('ContraindicationsProfile', 'ContraindicationsProfile'), ('FlareAid', 'FlareAid'), ('FlareDiagnosis', 'FlareDiagnosis'), ('FamilyProfile', 'FamilyProfile'), ('MedicalProfile', 'MedicalProfile'), ('SocialProfile', 'SocialProfile'), ('ULT', 'ULT'), ('ULTAid', 'ULTAid')], max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='erosions',
            name='value',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], help_text='Do you have erosions on your x-rays?', null=True, verbose_name='Erosions'),
        ),
        migrations.AlterField(
            model_name='hyperuricemia',
            name='value',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], help_text='Do you have a history of elevated levels (> 9.0 mg/dL) of uric acid in your blood?', null=True, verbose_name='Hyperuricemia'),
        ),
        migrations.AlterField(
            model_name='tophi',
            name='value',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], help_text='Do you have gouty tophi?', null=True, verbose_name='Tophi'),
        ),
    ]
