# Generated by Django 3.1.7 on 2021-09-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0006_auto_20210919_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alcohol',
            name='value',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], help_text='Do you drink alcohol?', null=True, verbose_name='alcohol'),
        ),
        migrations.AlterField(
            model_name='gout',
            name='value',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], help_text='Do you have a family history of gout?', null=True),
        ),
        migrations.AlterField(
            model_name='heartattack',
            name='cabg',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], help_text='Have you had bypass?', null=True, verbose_name='cabg'),
        ),
        migrations.AlterField(
            model_name='heartattack',
            name='stent',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], help_text='Have you had stents placed?', null=True, verbose_name='stent'),
        ),
    ]
