# Generated by Django 3.1.7 on 2021-12-29 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0007_angina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='angina',
            name='value',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], help_text="Do you get <a href='https://www.heart.org/en/health-topics/heart-attack/angina-chest-pain' target='_blank'>angina</a>?", null=True, verbose_name='Angina (cardiac chest pain)'),
        ),
    ]
