# Generated by Django 3.1.7 on 2021-09-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0007_auto_20210920_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bleed',
            name='value',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], help_text='Have you ever had a bleed?', null=True, verbose_name='major bleed'),
        ),
    ]
