# Generated by Django 3.1.7 on 2021-09-22 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0008_auto_20210920_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fructose',
            name='value',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], help_text='Do you eat a lot of fructose such as the sugar found in soda/pop, processed candies, or juices?', null=True, verbose_name='fructose'),
        ),
        migrations.AlterField(
            model_name='shellfish',
            name='value',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], help_text='Do you eat a lot of shellfish?', null=True, verbose_name='shellfish'),
        ),
    ]
