# Generated by Django 3.1.7 on 2021-10-11 17:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BK', 'Book'), ('EJL', 'Electronic Journal'), ('JL', 'Journal'), ('WB', 'Website')], default='BK', max_length=3)),
                ('slug', models.CharField(max_length=128, unique=True)),
                ('author', models.CharField(max_length=512)),
                ('title', models.CharField(max_length=512)),
                ('year', models.IntegerField(default=2000)),
                ('series', models.CharField(blank=True, max_length=512, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('edition', models.IntegerField(blank=True, null=True)),
                ('isbn', models.CharField(blank=True, max_length=17, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('publisher', models.CharField(blank=True, max_length=128, null=True)),
                ('place', models.CharField(blank=True, max_length=128, null=True)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('accessed', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['author'],
            },
        ),
    ]
