# Generated by Django 3.1.7 on 2021-09-28 06:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('citations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='accessed',
            field=models.DateField(default=datetime.datetime(2021, 9, 28, 6, 42, 52, 11945, tzinfo=utc)),
        ),
    ]
