# Generated by Django 3.1.7 on 2021-09-28 07:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('citations', '0002_auto_20210928_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='accessed',
            field=models.DateField(default=datetime.datetime(2021, 9, 28, 7, 56, 50, 947923, tzinfo=utc)),
        ),
    ]
