# Generated by Django 3.1.7 on 2021-10-03 21:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('citations', '0003_auto_20210928_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='accessed',
            field=models.DateField(default=datetime.datetime(2021, 10, 3, 21, 40, 48, 200199, tzinfo=utc)),
        ),
    ]
