# Generated by Django 3.1.7 on 2021-10-06 20:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('citations', '0004_auto_20211003_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='accessed',
            field=models.DateField(default=datetime.datetime(2021, 10, 6, 20, 48, 51, 856100, tzinfo=utc)),
        ),
    ]
