# Generated by Django 3.1.7 on 2021-10-07 00:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('citations', '0009_auto_20211006_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='accessed',
            field=models.DateField(default=datetime.datetime(2021, 10, 7, 0, 42, 43, 1535, tzinfo=utc)),
        ),
    ]
