# Generated by Django 3.1.7 on 2022-01-21 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ultaid', '0001_initial'),
        ('ppxaid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ppxaid',
            name='ultaid',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ultaid.ultaid'),
        ),
    ]
