# Generated by Django 3.1.7 on 2022-02-12 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ppxaid', '0004_ppxaid_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ppxaid',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ppxaid_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
