# Generated by Django 3.1.7 on 2022-02-05 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flare', '0002_auto_20220205_1458'),
        ('flareaid', '0001_initial'),
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flareaid',
            name='anticoagulation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.anticoagulation'),
        ),
        migrations.AddField(
            model_name='flareaid',
            name='bleed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.bleed'),
        ),
        migrations.AddField(
            model_name='flareaid',
            name='ckd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.ckd'),
        ),
        migrations.AddField(
            model_name='flareaid',
            name='colchicine_interactions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.colchicineinteractions'),
        ),
        migrations.AddField(
            model_name='flareaid',
            name='diabetes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.diabetes'),
        ),
        migrations.AddField(
            model_name='flareaid',
            name='flare',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flare.flare'),
        ),
        migrations.AddField(
            model_name='flareaid',
            name='heartattack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.heartattack'),
        ),
        migrations.AddField(
            model_name='flareaid',
            name='ibd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.ibd'),
        ),
        migrations.AddField(
            model_name='flareaid',
            name='osteoporosis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.osteoporosis'),
        ),
        migrations.AddField(
            model_name='flareaid',
            name='stroke',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.stroke'),
        ),
    ]
