# Generated by Django 3.1.7 on 2021-12-11 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flare', '0011_flare_angina'),
        ('flareaid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flareaid',
            name='flare',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flare.flare'),
        ),
    ]
