# Generated by Django 3.1.7 on 2022-03-11 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flareaid', '0001_initial'),
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flareaid',
            name='anticoagulation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.anticoagulation'),
        ),
        migrations.AddField(
            model_name='flareaid',
            name='bleed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.bleed'),
        ),
        migrations.AddField(
            model_name='flareaid',
            name='ckd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.ckd'),
        ),
        migrations.AddField(
            model_name='flareaid',
            name='colchicine_interactions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.colchicineinteractions'),
        ),
    ]
