# Generated by Django 3.1.7 on 2021-10-24 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flareaid', '0002_auto_20211024_0917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flareaid',
            old_name='colchicine_contraindication',
            new_name='colchicine_interactions',
        ),
    ]
