# Generated by Django 3.1.7 on 2022-02-25 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flare', '0003_auto_20220225_2230'),
        ('flareaid', '0002_auto_20220225_2230'),
        ('history', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='flareaid',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flareaid_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flareaid',
            name='diabetes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.diabetes'),
        ),
        migrations.AddField(
            model_name='flareaid',
            name='flare',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flare.flare'),
        ),
        migrations.AddField(
            model_name='flareaid',
            name='heartattack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.heartattack'),
        ),
        migrations.AddField(
            model_name='flareaid',
            name='ibd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.ibd'),
        ),
        migrations.AddField(
            model_name='flareaid',
            name='osteoporosis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.osteoporosis'),
        ),
        migrations.AddField(
            model_name='flareaid',
            name='stroke',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.stroke'),
        ),
        migrations.AddField(
            model_name='flareaid',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
